### ISSUE TITLE
If you buy stack of block, you have 2 unussable

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#107]
^^ title

**Comment by Yannici** [comment]
I don't understand ...

**Comment by Granik24** [comment]
If I buy 1 stack of some block, I'll get 1 stack with 2 unussable blocks. If I use it, will disappear.

**Comment by Yannici** [comment]
Lol? I really don't know where this behaviour come from. Maybe fixed with the commit https://github.com/Yannici/bedwars-reloaded/commit/4e2194cb0635ac12b522d07d3f45950fabd18ce2

**Comment by Granik24** [comment]
You maybe can add feature, if you shift-click to buy that item to buy max one stack, not full inventory :D

**Comment by Yannici** [comment]
This is fixed.
