### ISSUE TITLE
Flind and Steel griefing arena

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#113]
If player buy Flint and Steel, he can grief arena.

**Comment by Yannici** [comment]
How do they griefing the arena? Does the fire from flint and steel will destroy blocks?

**Comment by Granik24** [comment]
Yes, they destroying arena blocks

**Comment by Granik24** [comment]
![2015-05-11_21 09 27](https://cloud.githubusercontent.com/assets/4377405/7572913/180887a2-f822-11e4-8c5e-b1c21e7f2aca.png)
Still not solved

**Comment by Yannici** [comment]
I'll check that.

**Comment by Yannici** [comment]
Tested that, I can't reproduce it. The fire doesn't break any blocks ...

**Comment by Yannici** [comment]
Ok, sorry. Fire won't remove so it griefes arena when game is stopped/waiting.

**Comment by Yannici** [comment]
Fixed with Version 1.1.4
