### ISSUE TITLE
Still problem with spawners

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#114]
Spawning bricks behind wall is not good i think
![2015-05-03_23 04 20](https://cloud.githubusercontent.com/assets/4377405/7446927/f12e3468-f1e8-11e4-8e97-b2220952bd5c.png)
![2015-04-30_21 30 31](https://cloud.githubusercontent.com/assets/4377405/7446928/f5b30fcc-f1e8-11e4-87a1-8e9b4168179d.png)

**Comment by Yannici** [comment]
I'll try to fix that asap.

**Comment by Granik24** [comment]
Still not fixed yet.
Now it doing big stack, that's not good.
![2015-05-06_15 32 21](https://cloud.githubusercontent.com/assets/4377405/7494071/cfba2dea-f405-11e4-9ca7-ffd0930494ca.png)

**Comment by Yannici** [comment]
Ok, I will change that ^^

**Comment by Granik24** [comment]
![2015-05-06_23 11 44](https://cloud.githubusercontent.com/assets/4377405/7503772/634a6d56-f445-11e4-9091-8c4f173120f5.png)
Next problem with that. Spawners are under water.

**Comment by Granik24** [comment]
Fixed!
