### ISSUE TITLE
Add teleporting gunpowder

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#115]
It can be good to add teleporting bled, what can you telepor to team base.

**Comment by Yannici** [comment]
Wtf is that? :D Gunpowder which let you teleport DIRECTLY to your spawn?

**Comment by Granik24** [comment]
Yea, in 10 second wil teleport you to team spawn. See on GommeHD

**Comment by Granik24** [comment]
Aghhh sorry, m bad :D

**Comment by Yannici** [comment]
Are you able to move while activating that teleport? And how much does it cost? Sorry, I can't join GommeHD at the moment.

**Comment by Granik24** [comment]
Yes, you able to move, but if you move, telepor will be stopped. It cost 12 iron ingots I think. And little detail, if teleport beginning, player will have circle particles.

**Comment by Yannici** [comment]
Okay, I'll think about it.

**Comment by Yannici** [comment]
Including in #135
