### ISSUE TITLE
Bedwars Crash Error Report

### ISSUE THREAD

**Issue by homedog21** [Yannici/bedwars-reloaded#124]
Server Specs:
Spigot 1.8 
Plugin Info:
BedwarsRel
Verison: 1.1.3

Issue:
Installed the plugin reload the server.
Worked perfect
I setup a map/arena Completed all the task added bed,team,spawners,loc1 and loc2, add the game, set lobby and main lobby. Setup a sign to join the game did
[bw]
test

and on the sign nothing game up on the sign it was blank but was still able to click on it and join the game.
![image](https://cloud.githubusercontent.com/assets/5883521/7547473/7a7b06ce-f5b3-11e4-8fff-121ccc5defa3.png)

When I joined the game and the rest of the players have joined. We clicked to start the game and it just started to crash out of no where I check the console and Console was getting spammed with error messages ever second. 
![image](https://cloud.githubusercontent.com/assets/5883521/7547460/266ad398-f5b3-11e4-946e-31a623fe090f.png)

So I had to disable it from it spamming my console.
![image](https://cloud.githubusercontent.com/assets/5883521/7547470/5bd0e13a-f5b3-11e4-87b2-4952d4aa1e15.png)

After I started it up and tried to join the game again, It said that their was a never a game created so it has deleted my saved game.
If any questions feel free to contact me at jonathanbluesword@gmail.com
Thank you for your support

**Comment by Yannici** [comment]
Hm I have to check that. Did you tried to recreate the game?

**Comment by Yannici** [comment]
Maybe you configured ressource spawners wrong in config.

**Comment by homedog21** [comment]
I will recheck everything in the config and send you a screenshot of it as well and try to recreate the game again. I will let you know how it goes. Thank you for the fast  response.

**Comment by homedog21** [comment]
I was able to recreate the game and i fully checked the config and everything was perfect but when i tried to join the game it still crashed the plugin and having the same error message as before.
Also as soon as I did /bw start test I get a error after it says You Started the game, players can now join!
![image](https://cloud.githubusercontent.com/assets/5883521/7555867/c3fefc66-f71f-11e4-93a6-e5845814fe3e.png)
Also I setup a sign and still nothing
comes up on the sign

**Comment by homedog21** [comment]
Also when i re enable it my game gets deleted again like last time.

**Comment by Granik24** [comment]
Do you using latest Spigot 1.8.3 or 1.8?
We have 1.8.3 at play.hryozivot.cz and everything works great with 200 players+

**Comment by homedog21** [comment]
I am using Spigot 1.8

**Comment by Granik24** [comment]
So can you please try to use 1.8.3? This is a compatibility problem I think

**Comment by homedog21** [comment]
Alright I will try in a little bit when i get a free chance

**Comment by homedog21** [comment]
It was perfect It was the whole Spigot version update that messed it all up. Now the only issus is build permisson they are not allowed to build anything

**Comment by Yannici** [comment]
The build permissions shouldn't be a problem with the plugin. Thanks for Granik24 for help. So this should be fixed ... If not, please comment.
