### ISSUE TITLE
New Permissions

### ISSUE THREAD

**Issue by TheCollerroller** [Yannici/bedwars-reloaded#127]
Pls add:

bw.vip.full - player's can join Full Matches
bw.vip.force - player's can forcestart the Match

Pls remove: 

# Permissions
permissions:
### Defines if VIP-Users can force start a game!
    vipCanStart: true

(it doesnt work for me)

**Comment by Granik24** [comment]
For me it works, but great idea!

**Comment by Yannici** [comment]
Good idea, I will add it to next version.
