### ISSUE TITLE
If some team win game, no message like "Player left game" and Mainlobby

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#13]
Hi, i have another bug.
If you win game, you have message "Congratz! Team "x" win the game!
It can be cool, disable message "Player "X" left the game"

Sreen: http://gyazo.com/63beb2b1d638697249a0b901087cccec

Another feature, you maybe can add command /bw setmainlobby. 
/bw setlobby only for Game lobby and /bw setmainlobby for server lobby. On the end of game, port the players to the mainlobby. :)

**Comment by Yannici** [comment]
Player left message is good, I think. With the spectator features your suggestion will be useless ;)

The mainlobby/gamelobby feature I will add soon.

**Comment by Granik24** [comment]
Cool, thank you ^^

**Comment by Yannici** [comment]
I think the player left message is correct here, because he's really leaving ;-)
