### ISSUE TITLE
Add custom permissions to buy special items

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#132]
It can be good to add permissions to buy special items. :)

**Comment by Yannici** [comment]
Why? Every player should buy everything. Hacking shouldn't be allowed ;)

**Comment by Granik24** [comment]
Sure, but its needed for premium players. I think some servers want this feature too.

**Comment by Yannici** [comment]
I want to add a option to set categories for premium players only.

**Comment by Yannici** [comment]
Added permissions to categories
