### ISSUE TITLE
Item Bug

### ISSUE THREAD

**Issue by TheCollerroller** [Yannici/bedwars-reloaded#138]
Ich hoffe du kannst deutsch :)

Zu meinem Problem: Items glitchen durch wände und wenn dort eine 2 dicke mauer ist und dies verhindert dann verschwinden bei mir die items einfach...
Hoffe du änderst noch etwas an dem Ressource system. :)

kleiner tipp: schau mal auf TheVace.net vorbei, soll jetzt keine werbung sein aber dort finde ich das Item-Spawn-System gut umgesetzt (selbst wenn man im team ist bekommt jeder spieler etwas ab).

**Comment by Granik24** [comment]
Why not in English? :(

**Comment by Yannici** [comment]
Ich empfehle dir die Spawner nicht direkt an der Wand zu machen bzw. beim Setzen etwas weiter von der Wand weg zu stehen, dadurch ist die Chance geringer, dass die Items in der Wand landen. Ich bin schon drauf und dran das zu fixen.

**Comment by Yannici** [comment]
Duplicate of https://github.com/Yannici/bedwars-reloaded/issues/114
