### ISSUE TITLE
Rescue-platform: Configuration

### ISSUE THREAD

**Issue by TheCollerroller** [Yannici/bedwars-reloaded#140]
New Confirguration:

  rescue-platform:
    break-time: 30
    using-wait-time: 0
    id: 95
    can break: true

**Comment by Yannici** [comment]
Thanks for the suggestion, I'll add that configuration soon.

**Comment by Yannici** [comment]
Added in https://github.com/Yannici/bedwars-reloaded/commit/badf61b3a1a318cad709afcd2afa6047513d6b0a
