### ISSUE TITLE
Reset map at the end of a game

### ISSUE THREAD

**Issue by aubri59** [Yannici/bedwars-reloaded#142]
Hi ! I really enjoy your plugin but when I do a game the construction of the bridge between platform are not reset and the bed are break and not replace, can you add a reset of the map please and your plugin will be perfect !
thanks.

**Comment by Yannici** [comment]
Sorry, then you didn't setup everything or something went wrong. A map reset is already implemented. Please read the the instruction carefully and be sure you have bukkit/spigot > 1.7 or > 1.8

**Comment by aubri59** [comment]
Okay, It's in the config.yml who I have to setup the map reset ? I don't find hit and yes I turn with bukkit 1.7.10

**Comment by Granik24** [comment]
Map reset is automatic. Reset will be before game start. :)

**Comment by aubri59** [comment]
Okay I go test, thanks :)

**Comment by Granik24** [comment]
No problem ;) If you have any question, write it :)

**Comment by aubri59** [comment]
Yeah it's good, the plugin reset the map after game :)
Thanks for the answers Granik24 and Yannici :)

**Comment by Yannici** [comment]
No problem!

**Comment by aubri59** [comment]
Yannici do you can create a plugin SheepWars please, I need this minigame but not plugin exist
