### ISSUE TITLE
TABLIST - BUG

### ISSUE THREAD

**Issue by VeratoxMC** [Yannici/bedwars-reloaded#143]
Hallo, wie ich in einem vorherigen Thread schon beschrieben habe, gibt es einen Tablist Bug bei der Spigot1649- Version, sprich 1.7 - 1.8. In diesem Thread will ich weiter auf diesen Bug hinweisen.

1. Ein Spieler joint dem BedWars server auf dem bereits 2Spieler sind die ihr Team ausgewählt haben.

![1](https://cloud.githubusercontent.com/assets/12533735/7733328/b175b690-ff2e-11e4-87f3-056e62c6dfe8.png)

2. Dieser Spieler wählt nun sein Team aus und wie man sieht ändert sich seine Farbe.

![2](https://cloud.githubusercontent.com/assets/12533735/7733346/c719a6c8-ff2e-11e4-91ff-4d6f628bdfc3.png)

3. Nachdem ein weiterer Spieler sein Team doch wieder gewechselt hat, ändert sich nun auch seine Farbe.

![3](https://cloud.githubusercontent.com/assets/12533735/7733366/d92f0970-ff2e-11e4-9f79-b849ccf7b2b9.png)

4. Sobald die Runde losgeht sieht man RECHTS im Scoreboard dass 3Teams vorhanden sind, jedoch in der Tablist nur 2Spieler markiert sind.

![4](https://cloud.githubusercontent.com/assets/12533735/7733378/eb925ba8-ff2e-11e4-9a6c-4252c54983bf.png)

Hoffentlich konnte dieser Thread das Problem etwas genauer beschreiben.

Gruß VeratoxMC.net

**Comment by Yannici** [comment]
Thanks for the detailed bug report. I'll check that. I think this is caused by the scoreboard of bukkit/minecraft, but I'll try to fix that.

**Comment by Yannici** [comment]
Okay, after I watched that screenshots, I see you got a prefix in your name, maybe done by a other plugin. This is why the name won't be colored in the team's color.

**Comment by VeratoxMC** [comment]
Ich halte es von einer Lösung den DISPLAYNAME zu ändern, genau das selbe im Chat prefix, da es sonnst schnell mal so aussehen kann.
![6](https://cloud.githubusercontent.com/assets/12533735/7733819/09f55c78-ff32-11e4-814f-a43b8bc8fb6b.png)

Und ich finde diesen Chatformat nicht sonderlich schön, eine verbesserung wäre:

"&8[&7@all&8] &?TEAM &8| &rDISPLAYNAME

Gruß VeratoxMC.net

**Comment by Yannici** [comment]
Das mit dem Displayname verstehe ich leider nicht. Überschreibe ich den Displaynamen, geht der Prefix verloren.

**Comment by VeratoxMC** [comment]
Dann reicht es wenn die von deinem Plugin überschrieben wird, wird ja kein großes Problem sein.

Gruß VeratoxMC.net

**Comment by Yannici** [comment]
Is this working with "overwrite-names" config?

**Comment by Yannici** [comment]
Möglicherweise gefixt, kann ich aber leider nicht bestätigen (in 1.2.0).

**Comment by VeratoxMC** [comment]
Der Bug wurde behoben, jedoch gibt es jetzt einen neuen.

Undzwar sagt er nach jeder Runde das die Betten nicht gesetzt wurden.
Wenn ich sie also setze dann geht eine Runde, nach einem Neustart geht es
aber nichtmehr.

**Comment by VeratoxMC** [comment]
Ja klar :)

2015-06-14 20:04 GMT+02:00 Yannici <notifications@github.com>:
