### ISSUE TITLE
Bungeemode problems

### ISSUE THREAD

**Issue by Gotak99** [Yannici/bedwars-reloaded#144]
Hi,
I have problems in bungee mode.
Player can join to the server, when the game si running.
And after player death they are not teleported to lobby server but to BedWars server spawn.
When the game ends it just says server closed and dont teleport players.
How I can solve it?
Thanks.

Sorry for my english.

**Comment by Yannici** [comment]
This sounds like you didn't set up the hub server correctly or the hub server couldn't be found.

**Comment by Yannici** [comment]
Can't reproduce that as an bug.

**Comment by Darkool** [comment]
Hello Yannici,that's not the problem, I know that bug, the problem is that bungee can't teleport all players fast, then server is closed and some player are yet on server, by this reason maybe you should add more cooldown on task after end game to give time to bungee for move players to hub ;)

**Comment by mariolars** [comment]
http://pastebin.com/FKYbiSKm  
Thanks for great plugin BTW.

**Comment by Yannici** [comment]
@Darkool You could make a pull request, but thanks, I will add that snippet.

**Comment by Yannici** [comment]
Added in 1.1.13
