### ISSUE TITLE
rescue-platform     last thing

### ISSUE THREAD

**Issue by TheCollerroller** [Yannici/bedwars-reloaded#146]
du hast item: BLAZE_ROD   zu der config hinzugefügt

kannst du auch block: Sandstone zur config hinzufügen?
(so das anstatt glass die platform zu sandstone wird)

**Comment by Yannici** [comment]
Jap, wird in der nächsten Version eingebaut.

**Comment by Yannici** [comment]
Fixed in 1.1.13
