### ISSUE TITLE
Breakable block

### ISSUE THREAD

**Issue by sami37** [Yannici/bedwars-reloaded#147]
Hello,

I am hosting a map where i use bedwars, but i had a problem, when game start player can't break the block like dirt, sand, stone etc.
I am looking for a version with configurable breakable block, do you think it's possible to do one?

**Comment by Yannici** [comment]
It is possible, but I think it isn't really good to add that ... But maybe I'll add that soon.

**Comment by brainscript** [comment]
But blocks like TALL_GRASS should be breakable.

**Comment by sami37** [comment]
A custom list in config or external file in each minigame should be greater. Of course with a backup mode like when player put block.

**Comment by Yannici** [comment]
Added with https://github.com/Yannici/bedwars-reloaded/commit/34d5e0a2191fa47acb5b81db448f9b771b301b04
