### ISSUE TITLE
Villagers despawn

### ISSUE THREAD

**Issue by Gotak99** [Yannici/bedwars-reloaded#148]
Hi, I dont know why but sometimes when players join the game in some teams is not villagers.
Can you please do something with it?

Thanks.

**Comment by Yannici** [comment]
I will check if I can do anything, but I can't promise.

**Comment by brainscript** [comment]
Same problem. The players just spam the chat:

**I've got no villager!!**
**My villager disappeared!!**
**Team Red stole my villager!!** :stuck_out_tongue_winking_eye:

I know it's no bug of your plugin, but you could fix this by removing and respawning the villagers every minute or every time a player dies.

**Comment by Yannici** [comment]
@brainscript So when it's not a fault of my plugin it is a misconfiguration of other plugins by the server administrator. Such workaround isn't a task of the bedwars plugin.

**Comment by Granik24** [comment]
@brainscript I don't have this problem anymore.

**Comment by Yannici** [comment]
Sorry, it's no bug of my plugin so I can't help. And it's bad to have this as an issue in github.
