### ISSUE TITLE
Custom respawn block

### ISSUE THREAD

**Issue by brainscript** [Yannici/bedwars-reloaded#150]
It would be cool to use another block (not a bed) as respawn block, because with this option you could create your own game type. :smile:
### Some examples
- server.address | :question: **GameName** | *BLOCK_TYPE*
- keinleben.net | :bread: **BackWars** | *BURNING_FURNANCE*
- UnderTheDom.de | :bulb: **LightsOut** | *REDSTONE_LAMP_ON*
- play.dustmc.net | :zzz: **BedWars** | *DIAMOND_BLOCK*
- mc.example.com | :ghost: **SoulWars** | *SOUL_SAND*

**Comment by Yannici** [comment]
Yeah, may add that in a later version.

**Comment by Granik24** [comment]
Wow, good idea!

**Comment by Yannici** [comment]
Added in 1.1.15
