### ISSUE TITLE
[Feature] Add /bw reload x

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#153]
It can be cool to reload only parts of plugin.
So, something like: /bw reload shop, /bw reload locale :)

**Comment by brainscript** [comment]
Good idea! Because when I just want to fix something in the shop while I'm ingame and then reload the game stops.

**Comment by Granik24** [comment]
Yea.. I have normally 180 player and when i want to edit something, its not cool..

**Comment by Yannici** [comment]
Adding in 1.1.15 (https://github.com/Yannici/bedwars-reloaded/commit/6e5c19e7516e7ec56e90960d802dbb3a692cd6a4)
