### ISSUE TITLE
Wall Protection issue

### ISSUE THREAD

**Issue by Darkool** [Yannici/bedwars-reloaded#155]
Hello I have an issue with protection wall, this is my log

http://pastebin.com/D42VAgBR

Im using spigot protocol hack 1.7-1.8

**Comment by Granik24** [comment]
Your config is bad. 
Use:
    width: 5
    height: 3
    distance: 2
in protection-wall config.

**Comment by Yannici** [comment]
Protection wall width has to be odd

**Comment by Darkool** [comment]
Oh, ok I can't use my old config, then my protection wall is null, thanks for your help. (Granik24 and Yannici)
