### ISSUE TITLE
Disable spawning mobs in lobby

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#156]
^^ - Title

**Comment by Granik24** [comment]
I using gamerule, yes. 
Dont have Multiverse on my server.

I think, this feature can be good. :)

**Comment by Yannici** [comment]
I can't do that in my plugin, because I can't calculate where the lobby is. I don't have a specific region for the lobby, so I don't know if the entity was spawn in the lobby or outside of the lobby in the world.
