### ISSUE TITLE
Bungeecord, bei 3 Spielern und mehr fliegt der letzte vom Server

### ISSUE THREAD

**Issue by KillaSeven** [Yannici/bedwars-reloaded#157]
Hey,

Ich habe folgendes Problem: Ich betreibe ein Netzwerk und lasse Bedwars reloaded im Bungee mode laufen. Läuft auch alles super, wir haben einige Testspiele gemacht und es lief gut. Das Problem ist allerdings folgendes: Sobald mehr als 2 Spieler am Spiel teilnehmen wird der letzte Spieler nach Ablauf der 10 Sekunden nicht in die Lobby geschickt, sondern er fliegt vom Server ( bleibt also bis der Server offline geht und restartet drauf ). Ich weiß nicht woran das liegt und was den Fehler genau produziert, vielleicht kannst du da ja genau helfen. Da der Rest funktioniert denke ich nicht das es an mir liegt :/.

Das läuft dann wie folgt: Team Blau scheidet zuerst aus -> Spieler spectatet. Team rot und Team gelb kämpfen - Team rot gewinnt. Team gelb muss spectaten bzw, da die Runde vorbei ist warten bis man in die Lobby geschickt wird. Team Blau ( 1. Verlierer ) und Team Rot ( gewinner ) landen nun in der Lobby des Bungeecord Servers. Team Gelb bleibt bis der Server herunter fährt auf dem Server und fliegt dann zurück ins Minecraft menü mit der Meldung "Server closed".

**Comment by Yannici** [comment]
Ist es egal wie viel Spieler in Team Gelb sind? Oder ist es immer nur 1 Spieler der dann nicht teleportiert wird?

**Comment by KillaSeven** [comment]
Hm, das müsste ich mal testen. Werde ich später machen und dir bescheid geben, bis jetzt war es immer nur einer weil wir 1er teams gemacht haben.

**Comment by KillaSeven** [comment]
Es ist egal wieviele Spieler im Team sind. Der Letzte aus dem Team der gestorben ist, bleibt aufm Server. War dann so:

Team Rot hat 2 Spieler -> Sterben als erstes
Team Gelb hat 2 Spieler -> Sterben als letztes, wobei Spieler B der letzte tot war
Team Grün gewinnt. Alle spieler außer Spieler B landen in der Lobby. Spieler B bleibt auf dem Server bis zum restart.

**Comment by Yannici** [comment]
Ok, danke, dann weiß jetzt was Sache ist und kann mir das mal anschauen ;)

**Comment by Yannici** [comment]
Sollte gefixt sein in 1.2.0
