### ISSUE TITLE
Add leave time

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#158]
I have idea to add delay timer (like GommeHD). If player leave ingame, then block connecting to arena for him for x seconds.

**Comment by Yannici** [comment]
OK, but why?

**Comment by Granik24** [comment]
Because some players are retarded and they just logging into games, want to full up team and after game start leaving this -.-

**Comment by yannickko** [comment]
Ja, das fände ich auch sehr gut.

wäre nice wenn derjenige dann X Minuten aus den Runden ausgeschlossen wird. (Also, dass er nicht joinen kann für X Minuten.)

**Comment by Granik24** [comment]
This feature isn't possible in global bungee networks, so I'll close it.
