### ISSUE TITLE
Add /leave

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#16]
Maybe you can add synonym for /bw leave

**Comment by Yannici** [comment]
I think this is useless, /leave or /bw leave, this is not a really big difference...

**Comment by Granik24** [comment]
When we tried to stream BedWars, 5 people asked how to leave. They said that /leave not working.  So, i'm posting it here. :)

**Comment by Yannici** [comment]
Just tell them ;-) They have to learn, that's what I think about it ^^
