### ISSUE TITLE
Shop Bug

### ISSUE THREAD

**Issue by Jojo1910** [Yannici/bedwars-reloaded#160]
Ich bin mir nicht sicher ob das nur bei mir der Fall ist oder auch bei dir aber im neuen Shop wird von jeder Kategorie das erste Item immer noch in die 1 Zeile gesetzt.

![2015-06-03_21 41 15](https://cloud.githubusercontent.com/assets/5858912/7969814/c327028e-0a39-11e5-81c7-95a8ee29d57f.png)

**Comment by Yannici** [comment]
Will be added in next update. I'll release it in the next few days.
