### ISSUE TITLE
Team exsistiert nicht

### ISSUE THREAD

**Issue by Jojo1910** [Yannici/bedwars-reloaded#162]
Noch ein Bug, wenn ein Team von Anfang an nicht existiert also keiner in dem Team ist dann wird ja schon mal das Bett gelöscht aber im Scoreboard stehet noch der grüne Hacken. Das fixt sich sogar von alein sobalt ein Bett abgebaut wird.

**Comment by Yannici** [comment]
Ah, danke, das wird gefixt ;)
