### ISSUE TITLE
Chest and other invetory blocks problem

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#165]
If you have some chests on map and place something ingame co chest, plugin don't remove that. Same with furnaces and other inventory blocks.

**Comment by Yannici** [comment]
Plugin don't remove chests? Or you mean chests directly placed ON the map?

**Comment by Yannici** [comment]
Fixed in https://github.com/Yannici/bedwars-reloaded/commit/4fd8db603978723c28fb9f7a7597b38702507f51
