### ISSUE TITLE
Add custom option for disable "Arena started" only ingame

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#166]
It can be cool to add option to disable "Arena started" ingame.

**Comment by Yannici** [comment]
What? There is a configuration to disable Global messages for starting game. "global-messages" to false

**Comment by Granik24** [comment]
Yea, but I want to disable it only ingame, not in lobby :)

**Comment by sebastianbinder** [comment]
@Granik24 Don't get the idea behind this one. Can you explain it to me more detailed?

**Comment by Granik24** [comment]
@sebastianbinder Closing it, cause this solving bungee mode of BW.
