### ISSUE TITLE
Disable plugins ingame

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#167]
It can be cool to disable plugins like: http://dev.bukkit.org/bukkit-plugins/echopet/ and http://dev.bukkit.org/bukkit-plugins/playerparticles/ ingame. It is possible?

**Comment by Yannici** [comment]
Possible yes. I think I have a little idea ;)

**Comment by Yannici** [comment]
OK, I don't think this is possible :(

**Comment by Granik24** [comment]
Really? :C

**Comment by Yannici** [comment]
Yes
