### ISSUE TITLE
Map builder in title

### ISSUE THREAD

**Issue by brainscript** [Yannici/bedwars-reloaded#170]
Please make it possible to display the map name (regionname) as title and the map builder (/bw setbuilder) as subtitle when the game starts. *(Config value for enabling and disabling)*
![Example screenshot](https://cloud.githubusercontent.com/assets/8706734/8020244/37ddaec2-0c72-11e5-987d-b380f8515270.png)

**Comment by Yannici** [comment]
Okay, I'll add that :)

**Comment by brainscript** [comment]
Thanks

**Comment by Granik24** [comment]
This is really good idea! Maybe same with winners team? Title: Team X win the game! Subtitle: Congratulations!

**Comment by Yannici** [comment]
Yes, I'll add that :P

**Comment by Granik24** [comment]
Nice :+1:

**Comment by Yannici** [comment]
Added in 1.2.0 (https://github.com/Yannici/bedwars-reloaded/commit/ce54fe29ef0b176582ce7438b51f2f3ce08c8f24)
