### ISSUE TITLE
LOCALE_NOT_FOUND

### ISSUE THREAD

**Issue by kradosser** [Yannici/bedwars-reloaded#173]
Ich brauche Hilfe bei dem Plugin, und zwar wenn ich in der config locale von "en" auf "de" ersetze (ohne Klammern) und den Server neustarte, erscheint überrall die Nachricht "LOCALE_NOT_FOUND"
Bitte um Hilfe!
-Danke!

**Comment by Yannici** [comment]
Ich schau mir das nachher an. Hat jemand anderes auch das Problem?

**Comment by Yannici** [comment]
Fixed in 1.1.15 (DE+CZ LOCALE FIX)
