### ISSUE TITLE
Silent leave

### ISSUE THREAD

**Issue by brainscript** [Yannici/bedwars-reloaded#178]
I'm scripting my hub/lobby system with the scripting language Denizen and I want a command wich gets executed when the player types `/hub` or `/lobby` and then they leave the current game. But when i use '/bw leave' it says that the player is not in a game sometimes (when they are not in a game :smile: ).

Please add `/bw sleave` or `/bw leave -s` which hides the 'You are not in a game ...' message but shows the 'You left the game message ...' if you were in a game.

**Comment by Granik24** [comment]
This is really good idea! :+1:

**Comment by Yannici** [comment]
Good idea, will add that to the next version ;)

**Comment by brainscript** [comment]
Thx

**Comment by Yannici** [comment]
I just removed the message directly, because I think it isn't needed. https://github.com/Yannici/bedwars-reloaded/commit/0945393b88f003da7310b35052ec770f827c9f6b
