### ISSUE TITLE
New Item in BedWars: "Gravity Bomb"

### ISSUE THREAD

**Issue by YouGamePlayHD** [Yannici/bedwars-reloaded#179]
Hi,
I think it would be cool to add a "Gravity Bomb" to BedWars, which sucks in all the blocks around it (not the world blocks) and then throws them away like TNT. It is usually a snowball or fire charge and it should also suck in and throw away players! See an example on gommed.net
Thanks!

**Comment by Yannici** [comment]
It's already on the to do list ^^
