### ISSUE TITLE
Problems with TNT

### ISSUE THREAD

**Issue by YouGamePlayHD** [Yannici/bedwars-reloaded#184]
Hi,
I have a problem with your plugin "Bedwars-Rel".
When I set "destroy-world-blocks" in the configuration to "false" the blocks still get destroyed by TNT.
And the worst thing is that those blocks do not regenerate afterwards! I'm using 1.2.0 and my server is running on Bukkit 1.8.
Thanks

**Comment by Yannici** [comment]
Then it isn't caused by my plugin, but a other plugin!

2015-06-23 16:21 GMT+02:00 YouGamePlayHD <notifications@github.com>:

**Comment by YouGamePlayHD** [comment]
I removed all plugins except for BedWarsRel and still blocks get destroyed by TNT and they don't get regenerated although I set "destroy-world-blocks" to "false".

**Comment by Yannici** [comment]
I can't reproduce that behaviour.

**Comment by YouGamePlayHD** [comment]
I fixed the error.
Thanks for your support
