### ISSUE TITLE
Bug with pvp

### ISSUE THREAD

**Issue by xxsnowxxbeast** [Yannici/bedwars-reloaded#185]
Hi, help me please!!! Players from my team can PvP with me!!! I don't known why?! Please help me fix this bug.

**Comment by xxsnowxxbeast** [comment]
Please add in config pvpinteam:true/false

**Comment by Yannici** [comment]
Did you enable friendlyfire? friendlyfire: false and nobody can hit you! Otherwise a other plugin is causing that behaviour.

**Comment by xxsnowxxbeast** [comment]
Thank you yannici
