### ISSUE TITLE
Dorfbewohner

### ISSUE THREAD

**Issue by Liveware16** [Yannici/bedwars-reloaded#187]
Bei mir bugt der Dorfbewohner weg wenn man gestorben ist

**Comment by Yannici** [comment]
Das liegt nicht an meinem plugin, sondern an einem anderem bzw. dem despawnen auf Entfernung.

**Comment by Liveware16** [comment]
Wie mach ich das weg

**Comment by Yannici** [comment]
Kann ich dir nicht sagen, weiß ich nicht.

**Comment by Liveware16** [comment]
Aber beim ne Plugin von Mcserverexpert war das nicht soo

**Comment by Yannici** [comment]
Dann hat sich seitdem was bei deinem Server geändert. Andere Plugins ...

**Comment by Liveware16** [comment]
Gibt es eins was das BW Plugin stört

**Comment by Yannici** [comment]
Kann ich dir nicht direkt sagen. Es gibt so viele Plugins, kann leider nicht alle auf Abhängigkeiten prüfen ... Manche sagen es sei Citizens.

**Comment by Liveware16** [comment]
Okay habe ich nicht drauf liegt es daran das permission nicht bereit ist aber ich uns meine Freunde sind Aale op

**Comment by Liveware16** [comment]
Man kann den Dorfbewohner schlagen

**Comment by Yannici** [comment]
Auch nur Problem von anderen Plugins .... Meine Güte.

**Comment by Liveware16** [comment]
Okay nähme ich das andere Plugin wieder da ist das nicht soo

**Comment by Yannici** [comment]
Dann wünsche ich dir viel Spaß dabei. Über 500 Server verwenden mein Plugin und haben nicht solche Probleme. Da würde ich mir schon Gedanken machen, dass du nicht etwas falsch machst.
