### ISSUE TITLE
Fehler beim Starten des Servers: Failed to register...

### ISSUE THREAD

**Issue by YouGamePlayHD** [Yannici/bedwars-reloaded#189]
Hallo,
ich benutze dein cooles BedWars-Plugin. Aber beim Starten vom Server bekomme ich folgende Fehlermeldung:
...
[09:25:33 ERROR]: [BedwarsRel] Plugin BedwarsRel v1.2.0 has failed to register e
vents for class io.github.yannici.bedwars.Listener.EntityListener because org/bu
kkit/event/entity/EntitySpawnEvent does not exist.
...
Das Plugin läuft dann aber auch. Ich wollte nur fragen, was das für eine Fehlermeldung ist. Ich benutze Minecraft 1.8 und Version 1.2.0 deines Plugins, sowie Java 1.8.0_45 und auf meinem Server sind folgende Plugins installiert:

BungeeServerSigns,
 WorldEdit,
 BedWarsLuckyBlockAddon,
 Essentials,
 EssentialsProtect,
 TeleportSigns,
 EssentialsChat,
 MultiverseCore,
 WorldGuard und
 BedWarsRel

Danke im Voraus!

**Comment by brainscript** [comment]
`org/bukkit/event/entity/EntitySpawnEvent does not exist`
Da existiert ein bestimmtes Ereignis nicht. Das liegt entweder an deiner CraftBukkit/Spigot-Version oder an EssentialsProtect, MultiVerse oder WorldGuard welche ja, davon gehe ich zumindest aus, dieses Event abbrechen, damit keine Monster spawnen.
Wieso BWRel das Event nicht findet, keine Ahnung, da musst du @Yannici fragen.

**Comment by YouGamePlayHD** [comment]
@brainscript 
Ok, dann warte ich bis er schreibt. Danke

**Comment by Yannici** [comment]
Hm das ist komisch. Sieht so aus als würde es das Event nicht geben bei deiner Spigot/Craftbukkit Version. Ich check mal ab welcher Version es dieses Event gibt, vielleicht gibt es das ab einer bestimmten Version noch nicht. Fixe ich bald.

**Comment by YouGamePlayHD** [comment]
Ich habe jetzt auf Spigot gewechselt und es funktioniert einwandfrei!
Danke für deinen Support!
