### ISSUE TITLE
Bungee mode join started game bug(?)

### ISSUE THREAD

**Issue by JANEXLEBJAKOT** [Yannici/bedwars-reloaded#190]
Hello.
If plugin is set up for using with BungeeCord (1 map - 1 server) and the match starts, and server is not full (15/20) for exapmle, other players in lobby stll can tp to this server via TeleportSigns. 
I think BedWarsReloaded should kick players who wants to join game while it (started\finished\otherstuff) so they will stay in lobby.

**Comment by Yannici** [comment]
Yes, I'll try to fix that soon.

**Comment by Yannici** [comment]
Maybe fixed with 1.2.1?

**Comment by JANEXLEBJAKOT** [comment]
Nope. Still can connect while game started.

Waiting for 1.2.2 :C

**Comment by Yannici** [comment]
Should be fixed in https://github.com/Yannici/bedwars-reloaded/commit/42c7e4d647972fb4b1736a1dd3ffc5f279f65780
