### ISSUE TITLE
[Suggestion] Auto Balancing teams.

### ISSUE THREAD

**Issue by JANEXLEBJAKOT** [Yannici/bedwars-reloaded#191]
IMO plugin needs to balance players in teams because it is not fair when RED (10/10) BLUE (3/10) GREEN (1/10). I thnink you got my idea. Thanks.

**Comment by Yannici** [comment]
Will be added soon.

**Comment by Yannici** [comment]
Added in https://github.com/Yannici/bedwars-reloaded/commit/3d4605a61ceb46c184f937fe12b72c6a743da201
