### ISSUE TITLE
Betten werden nicht von TNT zerstört

### ISSUE THREAD

**Issue by YouGamePlayHD** [Yannici/bedwars-reloaded#192]
Hallo,
wenn ich destroy-world-blocks auf false und destroy-beds auf true schalte, werden Betten trotzdem nicht von TNT zerstört. Ich benutze Version 1.2.0 deines Plugins, mein Server läuft auf Spigot 1.8.6.
Muss ich vielleicht noch irgendwas Anderes einstellen?
Meine Plugins:
BungeeServerSigns, WorldEdit, BedwarsLuckyBlockAddon, NoRain, Essentials, EssentialsProtect,
TeleportSigns, EssentialsChat, Multiverse-Core, WorldGuard, BedwarsRel
Danke im Voraus!

**Comment by Yannici** [comment]
Das checke ich. Danke für's melden.

**Comment by YouGamePlayHD** [comment]
Ist es ein Bug, dass Spieler keinen Schaden von TNT bekommen?

**Comment by Yannici** [comment]
Weiß ich nicht? Eigentlich sollten sie Schaden bekommen. Ist das bei dir nicht der Fall?

**Comment by YouGamePlayHD** [comment]
Nein

**Comment by Yannici** [comment]
Nach Programmierung ist das korrekt. Auch nach dem Testen funktioniert das hier einwandfrei. Ich denke es liegt an einem deiner Plugins. EssentialsProtect könnte ich mir vorstellen, dass du darin das allgemeine zerstören von Blöcken und verletzen von Spielern verhinderst und somit dann auch innerhalb von Bedwars.

**Comment by YouGamePlayHD** [comment]
Ich probiere es aus und entferne alle Plugins...

**Comment by YouGamePlayHD** [comment]
Muss ich destroy-world-blocks dafür erst auf true machen?

**Comment by YouGamePlayHD** [comment]
Es funktioniert erst, wenn ich destroy-world-blocks auf true stelle, aber dann werden ja auch die anderen Blöcke zerstört...

**Comment by YouGamePlayHD** [comment]
Jetzt funktioniert es gar nicht mehr: Blöcke werden zerstört (oder auch nicht), ausser dem Bett. Muss ich vielleicht auch noch das Bett zu "breakable blocks" hinzufügen?

**Comment by Yannici** [comment]
Eigentlich nein, aber du kannst es mal ausprobieren.
Ich werde das nachher nochmal testen, habe das nur über den Code nochmal nachvollzogen.

**Comment by YouGamePlayHD** [comment]
Wenn ich destroy-world-blocks und destroy-beds beide aiuf true stelle, funktioniert es. Allerdings sollen die Player nicht die RegionBlocks zerstören können. Ich habe den 1.8 Build von der getspigot-Seite.

**Comment by YouGamePlayHD** [comment]
Kannst du vielleicht eine Blacklist für TNT einfügen, also ungefähr so:
destroy-world-blocks = true
#If true, edit Blacklist
block-blacklist: []
oder
- 1
- 56 usw...

**Comment by Yannici** [comment]
Fixed with https://github.com/Yannici/bedwars-reloaded/commit/5d273868ef38d5839271d3c4c9c523ae8d9151c2
