### ISSUE TITLE
Spieler bekommen keinen Schaden von TNT

### ISSUE THREAD

**Issue by YouGamePlayHD** [Yannici/bedwars-reloaded#195]
Hi,
ich wollte noch etwas zum TNT sagen: Spieler bekommen keinen Schaden. Warum nicht? Ist das ein Bug? Wenn nicht, kannst du bitte eine Config hinzufügen: 
tnt-player-damage: boolean
Danke im Voraus!
MFG YouGamePlayHD

**Comment by Yannici** [comment]
Werde das beheben, danke.

**Comment by Yannici** [comment]
Kann ich leider nicht nachvollziehen, habe das Problem in keiner Spigot/Craftbukkit Version. Möglicherweise ein Plugin das dieses Verhalten erklären könnte?

**Comment by YouGamePlayHD** [comment]
Okay, irgendwie funktioniert es jetzt WTF!
Danke für deine Unterstützung!
