### ISSUE TITLE
Shop Bug & Evtl. Verbesserung.

### ISSUE THREAD

**Issue by TanteFranz** [Yannici/bedwars-reloaded#196]
Hi,
wenn man den Shop auf den alten umstellen möchte kann man keine Villager mehr nutzen.
Evtl. sollteste noch hinzufügen, dass der Gamemode in der Lobby der Runde noch gesetzt wird und alle Items aus dem Inventar genommen werden bevor man die Bedwarsitems bekommt.

Ansonsten tolle Arbeit =)

Edit: Version vergessen.
1.8.7

**Comment by Yannici** [comment]
Oha, dass muss ich gleich testen.
Eigentlich sollte das Inventar immer geleert werden wenn man in die Lobby kommt, der Gamemode ebenfalls.

**Comment by TanteFranz** [comment]
Ich hab eine weitere Meldung erstellt. Evtl. hängt das mit dem Shop und co. irgendwie zusammen.

**Comment by TanteFranz** [comment]
Ich habe Dir ein Video hochgeladen wo man den Shopfehler sieht. 
https://youtu.be/Zib2_ZFrChU

Das mit dem Inventar hat sich beim erneuten Joinen der Lobby erledigt. Keine Ahnung woran das lag.

Die verwendeten Daten (shop.yml, Game...) findest Du unter folgendem Link.
http://www.xup.in/dl,64048121/BedwarsRel.zip/

Ich hoffe mal des hilft Dir weiter.
Gruß: Der TanteFranz

**Comment by Yannici** [comment]
Dann müsstest du einen Error in der Konsole haben? Oder?

**Comment by TanteFranz** [comment]
In der Console wird mir nichts angezeigt, hab ich aus. Hab den Fehler trotzdem gefunden.
swords:
        item: GOLDEN_SWORD
        name: Schwerter
Ersetzt durch
swords:
        item: 283
        name: Schwerter

Server neu gestartet, /bw reload und es geht.
Auch die Spiele werden jetzt anscheinend nach dem Serverneustart mit dem Status "Gestoppt" geladen.

**Comment by Yannici** [comment]
GOLDEN_SWORD ist nicht der richtige Name bei Bukkit/Spigot, leider! Das ist GOLD_SWORD. Deswegen konnte er das nicht finden. Kann ich also hier erstmal schließen. Wenn nochmal was ist, bescheid geben.
