### ISSUE TITLE
Spectate Joinsign

### ISSUE THREAD

**Issue by yannickko** [Yannici/bedwars-reloaded#199]
Hallo: Mein Vorschlag das es auch ein Spectate Joinschild gibt.

Zum Beispiel:
[bwspectate]
Rush

Wenn man dann auf das Schild klickt kommt man dann als Spectator in die Arena.

Sollte natürlich nur gehen wenn die Runde läuft.

Oder, dass wenn man auf das normale Schild klickt wenn dort "Gestartet!" steht das man dann als Spectator in die Arena kommt.

**Comment by Yannici** [comment]
Gibt es schon. spectation-enabled auf true stellen.

**Comment by yannickko** [comment]
Und wie kommt man dann rein zum Spectaten?
Gibts dafür nen Command?
Oder ist das dann halt so, wenn man wenn die Runde läuft und auf das Schild klickt, dass man dann spectated?

**Comment by Yannici** [comment]
Korrekt
