### ISSUE TITLE
Leute aus Runde kicken.

### ISSUE THREAD

**Issue by yannickko** [Yannici/bedwars-reloaded#200]
Vorschlag:
Das man Leute mit z.B /bw kick <player> <reason> 
Aus der Runde kicken kann.

**Comment by Yannici** [comment]
Für OP's okay, werde ich hinzufügen.

**Comment by Yannici** [comment]
Hinzugefügt in https://github.com/Yannici/bedwars-reloaded/commit/f2fa10759f8d9e03f335174fd4f7f88dd57ca4ef
