### ISSUE TITLE
Vorschlag: Stats

### ISSUE THREAD

**Issue by YouGamePlayHD** [Yannici/bedwars-reloaded#201]
Hi,
es wäre cool, wenn du Stats, so wie auf rewinside.tv, mit einem Hologramm verknüpfen könntest.
Man sollte das Holo dann mit z.B. /bw sethologram hinzufügen und konfigurieren könnnen (Farbe, Anzeige, etc.)
Danke im Voraus,
YouGamePlayHD

**Comment by Yannici** [comment]
Ist in Planung, aber nicht ganz so einfach, leider!

**Comment by Yannici** [comment]
Schließe das hier, weil es dazu schon ein Issue gibt.
