### ISSUE TITLE
Team Auswahl über Armorstands

### ISSUE THREAD

**Issue by YouGamePlayHD** [Yannici/bedwars-reloaded#204]
Hi,
ich fände es cool, wenn man mit einem Command beim Setup von der Arena (z.B. /bw setselect [TEAM]) einen Armorstand hinzufügen könnte, der Lederrüstung und Name in der ausgewählten Teamfarbe hat. Wenn man ihn rechtsklickt, tritt man dem Team bei.
Danke im Voraus,
YouGamePlayHD

**Comment by Yannici** [comment]
Ja, wird bald hinzugefügt.

**Comment by yannickko** [comment]
Richtig coole Idee!!

Kannst du ungefähr sagen wann?

**Comment by Yannici** [comment]
Added in https://github.com/Yannici/bedwars-reloaded/commit/726bea625680a515eb29bcc730b2024faa6a03c6
