### ISSUE TITLE
In-Outgame Bug

### ISSUE THREAD

**Issue by Phil870** [Yannici/bedwars-reloaded#207]
Wenn eine Runde läuft und man zB. als OP in gamemode 1 währrend der Runde was an der Map verändert wird dies dannach nicht resettet

**Comment by Yannici** [comment]
Das ist auch völlig sinnlos während der Runde was zu verändern, vor allem im Gamemode 1. Das ist für mich kein Bug. /bw stop bitte machen, bevor man was an der Map verändern will.
