### ISSUE TITLE
Drop Bug

### ISSUE THREAD

**Issue by Phil870** [Yannici/bedwars-reloaded#208]
Kann sein das das nur bei mir ist aber seit dem neuesten Update droppen bei mir (trotz player-drops: true) Spieler keine items mehr

**Comment by Yannici** [comment]
Kann ich nicht nachvollziehen, habe diesen Fehler nicht.

**Comment by Phil870** [comment]
hmm ich hab den Fehler gefunden xD ich hab ein Hub Plugin, welches Drops verbietet, habe es deaktiviert, nun geht das droppen wieder ^^ trotzdem danke :D
