### ISSUE TITLE
Rettungsplattforum Bug

### ISSUE THREAD

**Issue by Phil870** [Yannici/bedwars-reloaded#209]
Wenn ich bei der Config als Rettungsplattform Block (der Block der spawnt) auf Slimeball setze kommt nur Glas, folgendes habe ich bereits ausprobiert: SLIME_BLOCK, SLIMEBLOCK, SLIME ,165 hoffe du kannst helfen

**Comment by Yannici** [comment]
Danke, ich prüfe das ;)

**Comment by Yannici** [comment]
Mit der ID funktioniert es komischerweiße nicht, aber wenn ich SLIME_BLOCK eingebe, funktioniert es.
