### ISSUE TITLE
Respawnblock Bug

### ISSUE THREAD

**Issue by Phil870** [Yannici/bedwars-reloaded#210]
Hey und danke nochmal das du dir die Zeit nimmst und alle 5 Bugs die durchliest, aber nun zu diesem Bug: Wenn der Respawnblock (bei Mir Seelaterne) abgebaut wird, aber eine neue auf die Position gesetzt wird kann man respawnen, da sollte so bleiben aber eventuell sollte man einfügen das dann rechts im Scoreboard das Kreuz wieder zum Haken wird sobald der "Ersatzblock" gesetzt wurde

**Comment by Yannici** [comment]
Danke für den Bugreport. Ich denke nicht, dass es so bleiben sollte, dass man einen Respawnblock neu setzen kann... Ich werde das fixen. ;)

**Comment by Phil870** [comment]
Okay, ich fands nur gut weil ich schonmal bei den Item Vorschlägen "Bett Replacer" schrieb, mit diesem "Bug" wär die Sache sogar fast schon erledigt gewesen. Aber hast recht besser ists wenn der Bug aus der Welt geschaffen wird ^^
