### ISSUE TITLE
Liquid Bug

### ISSUE THREAD

**Issue by Phil870** [Yannici/bedwars-reloaded#211]
So der 6te Bug, für die Bug-Suche hab ich insgesamt 3 Tage verbracht ^^

Wenn man sich (bei meinem Shop gibt es die) einen Wasser/Lava Eimer setzt wird er bei der nächsten Runde nicht resettet + man kann diesen Block nicht einsammeln (mit Eimer) oder zubauen (mit Blöcken)

So das wars jetzt, ich meld mich sobald ich wieder Bugs finde, aber ich hoffe das das nicht der Fall sein wird, aber trotzdem sehr gutes Plugin ^^ Bugs sind normal ob nunmal viele oder wenige, ich werd auch bald neue Spezialitem Vorschläge machen ;) bis dahin Tschau ^^

**Comment by Yannici** [comment]
Das ist absolut nicht für eine Bedwars-Runde angedacht! Es macht Rießenarbeit Wasser korrekt zurücksetzen lassen, deshalb ist es wirklich nicht zu empfehlen sowas im Shop anzubieten. Klar ist es möglich, aber das geht auf Kosten der Performance und da geht man lieber so einen Kompromiss ein. Trotzdem danke für die Bug-Suche.
