### ISSUE TITLE
Liquid Bug

### ISSUE THREAD

**Issue by Phil870** [Yannici/bedwars-reloaded#212]
Eigentlich habe ich dies schon geschrieben aber irgendwie wurde der Post gelöscht also nochmal:
Wenn ich in einer Runde einen Wasser/Lava Eimer benutze ist das/die Wasser/Lava nach dem Weltreset immernoch da und man kann es nicht durch eimer entfernen oder zubauen

Ich hoffe mal das ich keine weiteren Bugs finde, das Plugin ist super, es kommen regelmäßig Updates und co. Bugs sind normal und ich freu mich das es viele gibt die Bugs reporten ;)

**Comment by Yannici** [comment]
Du hast einfach die Antwort dort verpasst, ich habe den Issue geschlossen.
