### ISSUE TITLE
BUG: Shop bearbeiten nicht möglich

### ISSUE THREAD

**Issue by yannickko** [Yannici/bedwars-reloaded#215]
Wenn ich neue ( zusätzliche Items hinzufügen möchte, kann ich nach /bw reload garnichts mehr im Shop kaufen.

(Dort ist nurnoch der SlimeBall und der LavaEimer)

**Comment by YouGamePlayHD** [comment]
Dann steht bei dir in der Konsole mit Sicherheit ein Fehler: Syntax.
Das heißt, dass du irgendwas falsch eingerückt hast, oder "" vergessen oder so etwas. Uploade mal deine shop.yml
MFG
YouGamePlayHD

**Comment by yannickko** [comment]
Genauere Beschreibung:

Wenn ich zum Beispiel bei usefullstuff
am Ende
            - item1:
                item: GOLD_INGOT
                amount: 14
              reward:
                item: 368
                amount: 1
       
dabeischreibe

siehts nach /bw reload im Shop so aus;

http://workupload.com/file/RhUylpic

Entferne ich das wieder läufts..
Preise ändern geht.

**Comment by yannickko** [comment]
Hier meine shop.yml

### SHOP ###
### NOT ALLOWED CATEGORY MATERIAL: SLIME_BALL, SNOW_BALL, BUCKET, LAVA_BUCKET
### The categories (unique key!)
###### Categories:
###### item:
######  type: string or int
######  Itemname or Item-ID which should be 
######  displayed to represent the category
###### name: 
######  type: string
######  Name of the category
###### lore:
######  type: list<string>
######  The lore (description) the category should have.
###### order:
######  type: int
######  The order the categories will be displayed
######### Offers:
######### item1 (first trade item):
#########  item: 
#########   type: string or int
#########   Item-Name or Item-ID
#########  amount: 
#########   type: int
#########   The stack amount the item should have
#########  name:
#########   type: string (colorcodes with &)
#########   A specific name for the item
#########  enchants:
#########   key: Has to be the enchant-ID or enchant-name!
#########   value: The level of the enchant
#########  lore:
#########   type: list<string> (colorcodes with &)
#########   The lores this item should have
#########  meta:
#########   type: short (potion) or byte (any other item)
#########   The meta byte which should be added to the item
######### item2 (optional, second trade item): See item1
######### reward (reward item): See item1
shop:
    armor:
        item: DIAMOND_CHESTPLATE
        name: Rüstung 
        order: 10
        permission: bw.base
        lore:
            - Protect yourself with armor! Click here.
        offers:
            - item1:
                item: CLAY_BRICK
                amount: 1
              reward:
                item: LEATHER_HELMET
                amount: 1
                enchants:
                    0: 1
            - item1:
                item: CLAY_BRICK
                amount: 1
              reward:
                item: LEATHER_LEGGINGS
                amount: 1
                enchants:
                    0: 1
            - item1:
                item: CLAY_BRICK
                amount: 1
              reward:
                item: LEATHER_BOOTS
                amount: 1
                enchants:
                    0: 1
            - item1:
                item: IRON_INGOT
                amount: 1
              reward:
                item: 303
                amount: 1
                enchants:
                    0: 1
            - item1:
                item: IRON_INGOT
                amount: 3
              reward:
                item: 303
                amount: 1
                enchants:
                    0: 2
            - item1:
                item: IRON_INGOT
                amount: 7
              reward:
                item: 303
                amount: 1
                enchants:
                    0: 3
    swords:
        item: DIAMOND_SWORD
        name: Schwerter
        order: 20
        permission: bw.base
        lore:
            - Click here to get sword for attacking your enemies
        offers:
            - item1:
                item: CLAY_BRICK
                amount: 15
              reward:
                item: 280
                amount: 1
                enchants:
                    19: 1
            - item1:
                item: IRON_INGOT
                amount: 1
              reward:
                item: 283
                amount: 1
                enchants:
                    16: 1
            - item1:
                item: IRON_INGOT
                amount: 3
              reward:
                item: 283
                amount: 1
                enchants:
                    16: 2
            - item1:
                item: GOLD_INGOT
                amount: 6
              reward:
                item: 267
                amount: 1
                enchants:
                    16: 2
                    19: 1
    bows:
        item: 261
        name: Bögen
        order: 30
        permission: bw.base
        lore:
            - Prove yourself as a marksman with these wonderful bows
        offers:
            - item1:
                item: GOLD_INGOT
                amount: 3
              reward:
                item: 261
                amount: 1
                enchants:
                    51: 1
            - item1:
                item: GOLD_INGOT
                amount: 7
              reward:
                item: 261
                amount: 1
                enchants:
                    51: 1
                    48: 1
            - item1:
                item: GOLD_INGOT
                amount: 13
              reward:
                item: 261
                amount: 1
                enchants:
                    51: 1
                    48: 2

            - item1:
                item: GOLD_INGOT
                amount:
              reward:
                item: 262
                amount: 1

    pickaxes:
        item: DIAMOND_PICKAXE
        name: Spitzhacken
        order: 50
        permission: bw.base
        lore:
            - Destroy others blocks? Use these pickaxes.
        offers:
            - item1:
                item: CLAY_BRICK
                amount: 4
              reward:
                item: 270
                amount: 1
               
            - item1:
                item: IRON_INGOT
                amount: 2
              reward:
                item: STONE_PICKAXE
                amount: 1
               
            - item1:
                item: GOLD_INGOT
                amount: 1
              reward:
                item: IRON_PICKAXE
                amount: 1

                
    blocks:
        item: SANDSTONE
        name: Blöcke
        order: 60
        permission: bw.base
        lore:
            - Get to the others! Possible with blocks.
        offers:
            - item1:
                item: CLAY_BRICK
                amount: 1
              reward:
                item: 24
                meta: 2
                amount: 2
            - item1:
                item: CLAY_BRICK
                amount: 7
              reward:
                item: 121
                amount: 1
            - item1:
                item: IRON_INGOT
                amount: 3
              reward:
                item: 42
                amount: 1
            - item1:
                item: CLAY_BRICK
                amount: 15
              reward:
                item: 89
                amount: 4
            - item1:
                item: CLAY_BRICK
                amount: 4
              reward:
                item: 20
                amount: 1 
         
    usefulstuff:
        item: TNT
        name: Nützliche Sachen
        order: 70
        permission: bw.base
        lore:
            - Looking for useful stuff? Here are some!
        offers:
            - item1:
                item: GOLD_INGOT
                amount: 3
              reward:
                item: TNT
                amount: 1
            - item1:
                item: IRON_INGOT
                amount: 7
              reward:
                item: 259
                amount: 1
            - item1:
                item: IRON_INGOT
                amount: 1
              reward:
                item: 54
                amount: 1
            - item1:
                item: GOLD_INGOT
                amount: 2
              reward:
                item: 130
                amount: 1
            - item1:
                item: GOLD_INGOT
                amount: 4
              reward:
                name: '&cRettungsplattform'
                lore:
                    - Rette dich vor dem Abstürzen
                    - mit der Rettungsplattform
                item: 369
                amount: 1
            - item1:
                item: IRON_INGOT
                amount: 6
              reward:
                name: '&7Trap'
                lore:
                    - Tritt ein Gegner drauf, wirst du informiert
                    - "und er kann sich nur eingeschränkt bewegen."
                item: 287
                amount: 1
            - item1:
                item: IRON_BRICK
                amount: 16
              reward:
                name: '&4Schutzmauer'
                lore:
                    - "Aktiviere es und erhalte sofort eine"
                    - "5x3 große Mauer vor dir!"
                item: BRICK
                amount: 1
            - item1:
                item: IRON_INGOT
                amount: 4
              reward:
                name: '&fTeleportationspuder'
                lore:
                    - "Aktiviere dieses Pulver und du wirst"
                    - "in 6 Sekunden an den Spawn teleportiert."
                    - "Achtung: Bewegen bricht den Vorgang ab!"
                item: 289
                amount: 1
            - item1:
                item: CLAY_BRICK
                amount: 64
              reward:
                name: '&cTNT-Schaf'
                lore:
                    - "Aktiviere das TNT-Schaf! Es wird"
                    - "auf den nächsten Gegner zugehen"
                    - "und nach 8 Sekunden explodieren!"
                item: MONSTER_EGG
                amount: 1
                
                - item1:
                item: GOLD_INGOT
                amount: 14
              reward:
                item: 368
                amount: 1
               
    drinks:
        item: POTION
        name: Tränke
        order: 80
        permission: bw.base
        lore:
            - Not enough? Use these potions and you'll feel better!
        offers:
            - item1:
                item: IRON_INGOT
                amount: 3
              reward:
                item: 373
                amount: 1
                meta: 8197
            - item1:
                item: IRON_INGOT
                amount: 6
              reward:
                item: 373
                amount: 1
                meta: 8229
            - item1:
                item: IRON_INGOT
                amount: 8
              reward:
                item: 373
                amount: 1
                meta: 8194
            - item1:
                item: GOLD_INGOT
                amount: 9
              reward:
                item: 373
                amount: 1
                meta: 8201
            - item1:
                item: GOLD_INGOT
                amount: 14
              reward:
                item: 373
                amount: 1
                meta: 8193

**Comment by yannickko** [comment]
Und das sagt die Log dazu

 in 'string', line 202, column 15:
                - item1:
                  ^
expected <block end>, but found BlockEntry
 in 'string', line 208, column 15:
                  - item1:
                  ^

**Comment by YouGamePlayHD** [comment]
Ja, eindeutig Syntax-Fehler:
Bei deinem neuen Eintrag muss das "- item1:" genau unter den anderen stehen. Außerdem sollte keine leere Zeile zwischen den Einträgen sein!
Es muss bei dir so aussehen:
         - item1:
            item: CLAY_BRICK
            amount: 64
          reward:
            name: '&cTNT-Schaf'
            lore:
                - "Aktiviere das TNT-Schaf! Es wird"
                - "auf den nächsten Gegner zugehen"
                - "und nach 8 Sekunden explodieren!"
            item: MONSTER_EGG
            amount: 1
         - item1:
            item: GOLD_INGOT
            amount: 14
          reward:
            item: 368
            amount: 1
MFG,
YouGamePlayHD

**Comment by yannickko** [comment]
Werde ich später mal nachsehen (bin am Handy)

Hatte aber auch alles schon getestet mit / ohne Zeile frei dazwischen etc.

**Comment by yannickko** [comment]
Und was failt beim Scorebord rechts?
http://workupload.com/file/SB5kCXRv
