### ISSUE TITLE
Entfernen von den Teamklammern

### ISSUE THREAD

**Issue by YouGamePlayHD** [Yannici/bedwars-reloaded#216]
Hi,
könntest du vielleicht mit "overwrite-names = true" eine Funktion koppeln, die die Teamklammern löscht?
Das heißt:
1.) overwrite-names = false
     "[BedWars] YouGamePlayHD [Blau] ist gestorben"
2.) overwrite-names = true
     "[BedWars] YouGamePlayHD ist gestorben"
Danke im Voraus!
YouGamePlayHD

**Comment by Yannici** [comment]
Werde ne weitere Config hinzufügen :P

**Comment by Yannici** [comment]
Added in https://github.com/Yannici/bedwars-reloaded/commit/84eba496b0814c6d0b1d4d53f5db2f3f699a8485
