### ISSUE TITLE
Spiele werden nach Neustart des Servers nicht geladen.

### ISSUE THREAD

**Issue by TanteFranz** [Yannici/bedwars-reloaded#218]
Moin,

wenn ich den Server neu starte werden die Spiele nicht geladen.
Meldung aus dem Log: "Das Laden des Spiels 'bw1' hat einen Fehler verursacht!"
Bei Eingabe von bw reload laufen die Spiele allerdings an.

**Comment by Yannici** [comment]
Den gameblock verändert? Also den respawnblock?

**Comment by TanteFranz** [comment]
Negativ hab die Map nicht verändert.

**Comment by Yannici** [comment]
Vielleicht kannste mir mal dein game-Ordner samt Map in ein Archiv packen und zukommen lassen, dann kann ich das mal debuggen :)

**Comment by TanteFranz** [comment]
Wie kann ich Dich am besten erreichen?
Ich wäre unter kontakt@fcdev.org erreichbar.

**Comment by TanteFranz** [comment]
Das Problem besteht auch in der Version 1.2.5.

**Comment by Icecrown-wow** [comment]
Hab das selbe Problem.

**Comment by sebastianbinder** [comment]
@TanteFranz @Icecrown-wow 
Ist das Problem noch aktuell? Oder kann man den Issue hier schließen? Sollte ich von euch nichts mehr hören, werde ich der Ordnung halber den Issue hier in einer Woche schließen.

**Comment by TanteFranz** [comment]
Bei mir funktioniert es.
