### ISSUE TITLE
Stacking deaktivieren

### ISSUE THREAD

**Issue by YouGamePlayHD** [Yannici/bedwars-reloaded#221]
Hi
es wäre schön, wenn du eine Config hinzufügst, die einstellen lässt, ob Stacking aktiviert oder deaktiviert werden sollte.
Danke im Voraus,
YouGamePlayHD

**Comment by Granik24** [comment]
You can use spigot settings, right? If google translate saying that, what you mean.. :D

**Comment by Yannici** [comment]
Stacking von was?

**Comment by YouGamePlayHD** [comment]
Stacking von allen Items (Gekaufte Items, Ressourcen) könnte deaktiviert werden, aber im Inventar sollten sich Ressourcen stacken können. (Beispiel: gommehd.net)

**Comment by Yannici** [comment]
Musst du selbst einstellen in den Spigot-Einstellungen (spigot.yml). Kann man innerhalb eines Plugins nicht!

**Comment by Granik24** [comment]
Use this in spigot.yml:

    merge-radius:
      item: 0
