### ISSUE TITLE
Kategorien nicht in anderen Reihen möglich

### ISSUE THREAD

**Issue by YouGamePlayHD** [Yannici/bedwars-reloaded#222]
Hi,
ist weiß nicht, ob es ein Bug ist, aber ich kann keine Kategorien in der zweiten oder dritten (vierten, ...) Reihe erstellen (order: 12). Kannst du, wenn das kein Bug sein sollte, bitte eine Möglichkeit hinzufügen, die erlaubt, Kategorien auch in anderen Reihen als nur in der ersten anzulegen?
Danke im Voraus,
YouGamePlayHD

**Comment by Yannici** [comment]
Nein. Macht für mich keinen Sinn.
Die Kategorien werden nacheinander angereiht. Die Konfiguration "order" bedeutet nicht die Stelle an der die Kategorie angezeigt werden soll, sondern in welcher Reihenfolge die Kategorien angezeigt werden sollen. Egal welche Zahl du dort eingibst, die Kategorien werden nach dieser Eigenschaft sortiert.
