### ISSUE TITLE
Villager eggs problem

### ISSUE THREAD

**Issue by Gotak99** [Yannici/bedwars-reloaded#223]
Hi,
Villagers sometimes despawn.
I created a kit with villager egg to keep players to spawn it when its dewspawned.
But now when they spawn villager with spawn egg, it spawn sheep with TNT head.
Why?

**Comment by Yannici** [comment]
Because eggs are used for tnt-sheeps ...
I will fix that in next version to spawn tnt-sheeps only with sheep-eggs ;)

**Comment by Yannici** [comment]
Fixed with https://github.com/Yannici/bedwars-reloaded/commit/cd9a1d91ac568a7f9432c9bff0988e39696e2568
