### ISSUE TITLE
Zerstören von Blöcken durch Feuer

### ISSUE THREAD

**Issue by YouGamePlayHD** [Yannici/bedwars-reloaded#227]
Hi,
ich fände es cool, wenn man mithilfe eines Commands ingame immer bei jeder Arena einstellen könnte, ob in dieser Arena Blöcke durch Feuer zerstört werden können (Beispiel, wo so was sinnvoll wäre: Map PirateCraft, also da die Feuerbälle sollten Blöcke zerstören können). Dies könntest du z.B. so machen:
*/bw fire [Arena] [boolean]*
Danke im Voraus,
YouGamePlayHD

**Comment by Yannici** [comment]
Nein, sorry.
