### ISSUE TITLE
Neues Shopsystem

### ISSUE THREAD

**Issue by YouGamePlayHD** [Yannici/bedwars-reloaded#228]
Hi,
könntest du eine Config machen, die ein neues Shopsystem festlegt:
Wenn man im Villagershop ganz normal im Hauptmenü ist, und auf eine Kategorie klickt, sollte sich nochmals so ein Fenster (wie im Hauptmenü) öffnen, in dem man die Items angezeigt bekommt. Die Überschrift des Shops könnte dann [Shopname] > [Kategorie] sein. Im neuen Fenster sollten dann die Katergorien nicht mehr angezeigt werden. Ein Bespiel hierzu gibt es auf *TheVace.net*
MFG
YouGamePlayHD :+1:

**Comment by Yannici** [comment]
Unnötig und unflexibel.
