### ISSUE TITLE
Remove other players in Tablist

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#23]
Ingame, it can be cool to remove all other players from Tablist.

**Comment by Yannici** [comment]
I'll looking for fixing this

**Comment by Granik24** [comment]
How about that request? It can be cool to add it ;)

**Comment by Yannici** [comment]
Isn't really important, it can be done with other plugins. I will do that later, after milestone v1.1.0

**Comment by brainscript** [comment]
@Granik24 Look at [this](http://dev.bukkit.org/bukkit-plugins/worldisolate/) or [that](http://dev.bukkit.org/bukkit-plugins/worldisolation/).

**Comment by Yannici** [comment]
He already got something like that. But it should be nice the bedwars plugin will do that ... I'll still checking this.

**Comment by Granik24** [comment]
@brainscript I have my own plugin for chat separate and PerWorldTablist for TAB.

**Comment by Granik24** [comment]
This can be done by other plugins.
