### ISSUE TITLE
PERMISSIONS

### ISSUE THREAD

**Issue by GoliDa** [Yannici/bedwars-reloaded#230]
On the bukkit.org website. Write down a list of your permissions! PLEAS!

I try to find them about 4 hours!

I rate your plugin 5/5 stars very good job. Want to donate later to you BB

**Comment by Prozessor** [comment]
Permissions? https://github.com/Yannici/bedwars-reloaded/wiki/Permissions

:D

**Comment by Yannici** [comment]
Oh god ...
