### ISSUE TITLE
Sign not clickable for join

### ISSUE THREAD

**Issue by sebastianbinder** [Yannici/bedwars-reloaded#237]
Hi. Habe leider das Problem, dass ich nur als OP mit Rechtsklick auf das Schild in die Runde joinen kann. Ohne OP-Rechte geht es nur mittels Befehl. Schon mal irgendwo aufgetreten oder irgendwelche Lösungsvorschläge?

**Comment by YouGamePlayHD** [comment]
Das ist ein Problem deiner Einstellungen am Server. In der server.properties:
spawn-protection=0
MFG
YouGamePlayHD :+1:

**Comment by sebastianbinder** [comment]
Danke ^^
Da hätte ich ja auch selbst draufkommen können. Doofer Fehler von mir…. Aber so funktioniert es natürlich :+1:
