### ISSUE TITLE
Item Schutzmauer does not work

### ISSUE THREAD

**Issue by Gotak99** [Yannici/bedwars-reloaded#241]
Hi, item Schutzmauer does not work for me.
I alway get this error: http://pastebin.com/pYpBf6fP.

**Comment by Yannici** [comment]
Read the first line! And you will know what it is ...

**Comment by Gotak99** [comment]
Okay but how I can set it?
In your tutorial is just this.

 - item1:
                item: CLAY_BRICK
                amount: 64
              reward:
                name: '&4Schutzmauer'
                lore:
                    - "Aktiviere es und erhalte sofort eine"
                    - "5x3 große Mauer vor dir!"
                item: BRICK
                amount: 1

**Comment by Yannici** [comment]
It's in config.yml. Under "specials" you find "protection-wall" and then "width". Set it to something odd (like 5)

**Comment by Gotak99** [comment]
Oh, sorry.
