### ISSUE TITLE
Bedwars Spiele können nicht gestartet werden!

### ISSUE THREAD

**Issue by HobbyzockerLP** [Yannici/bedwars-reloaded#242]
Hey Yannici,
ich kann seit dem Update keine Bedwars Spiele starten als OP oder sonst irgendjemand...
Da steht nur "Spiel starten..." :(
Kann mir jemand helfen?

**Comment by Yannici** [comment]
Gibt's ein Error in der Console?

**Comment by HobbyzockerLP** [comment]
Die Konsole wird zugespammt... DerText ist so lang das ich ihn nicht ganz lesen kann... Kann man den irgendwo im server ordner lesen? Dann könnte ich dir den Bericht schicken.
MFG

**Comment by Yannici** [comment]
Weiß ich nicht genau. Ich meine es gibt eine Log-Datei, ja.

**Comment by Pixelspass** [comment]
Hab das selbe Problem. 

Hier mal ein Auszug aus dem Log mit Version 1.2.2:

18:01:40 BedWars: Spiel 'cargo' wurde erfolgreich geladen!
18:02:08 CONSOLE: ERROR]: Could not pass event InventoryClickEvent to BedwarsRel v1.2.2
18:02:09 CONSOLE: java.lang.IllegalArgumentException: Player list names can only be a maximum of 16 characters long
18:02:09 CONSOLE: Source) ~[?:?]
18:02:09 CONSOLE: Source) ~[?:?]
18:02:09 CONSOLE: Source) ~[?:?]
18:02:09 CONSOLE: Source) ~[?:?]
18:02:10 CONSOLE: ERROR]: Could not pass event InventoryClickEvent to BedwarsRel v1.2.2
18:02:10 CONSOLE: java.lang.IllegalArgumentException: Player list names can only be a maximum of 16 characters long
18:02:10 CONSOLE: Source) ~[?:?]
18:02:10 CONSOLE: Source) ~[?:?]
18:02:10 CONSOLE: Source) ~[?:?]
18:02:10 CONSOLE: Source) ~[?:?]

Das wiederholt sich dann immer wieder.

Mit Version 1.2.3:

18:27:42 CONSOLE: ERROR]: Could not pass event PlayerCommandPreprocessEvent to BedwarsRel v1.2.3
18:27:42 CONSOLE: Source) ~[?:?]
18:27:42 CONSOLE: Method) ~[?:1.8.0_45]
18:27:42 CONSOLE: [INFO] Pixelspass issued server command: /bw reload
18:27:42 CONSOLE: ERROR]: null
18:27:42 CONSOLE: exception executing command 'bw' in plugin BedwarsRel v1.2.3
18:27:43 CONSOLE: Source) ~[?:?]
18:27:43 CONSOLE: Source) ~[?:?]
18:27:43 CONSOLE: Source) ~[?:?]
18:27:51 CONSOLE: ERROR]: Could not pass event BlockIgniteEvent to BedwarsRel v1.2.3
18:27:51 CONSOLE: Source) ~[?:?]

**Comment by HobbyzockerLP** [comment]
Also bei mir steht auch immer, dass die Spiele erfolgreich geladen werden, aber in der Wartelobby kann ich das Spiel nicht starten.  Bei meiner Konsole steht eigentlich auch was in deiner Konsole steht, aber bei mir nur etwas mehr spam :D

**Comment by Yannici** [comment]
@Pixelspass Der erste Fehler den du hast, kannst du mit "teamname-on-tab" auf "false" fixen. Das funktioniert in der 1.7 nicht. Die weiteren, spamenden Fehler sind gefixt in der nächsten Version.

Workaround: Server 1x mit Version 1.8 starten, dann wieder stoppen und mit der alten Version wieder starten.

**Comment by HobbyzockerLP** [comment]
Wie ist es mit 1.8.3? Mein Server läuft auf 1.8.3

**Comment by Yannici** [comment]
Dann ist es defintiv ein anderer Fehler als @Pixelspass hat. Bitte Error zukommen lassen. Anders kann ich das nicht analysieren.

**Comment by HobbyzockerLP** [comment]
Hier der Error:
[21:26:23] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to HubBasics v3.0.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot_server.jar:git-Spigot-2f787bd-501372f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_server.jar:git-Spigot-2f787bd-501372f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_server.jar:git-Spigot-2f787bd-501372f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_server.jar:git-Spigot-2f787bd-501372f]
	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [spigot_server.jar:git-Spigot-2f787bd-501372f]
	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:193) [spigot_server.jar:git-Spigot-2f787bd-501372f]
	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:189) [spigot_server.jar:git-Spigot-2f787bd-501372f]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:697) [spigot_server.jar:git-Spigot-2f787bd-501372f]
	at net.minecraft.server.v1_8_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot_server.jar:git-Spigot-2f787bd-501372f]
	at net.minecraft.server.v1_8_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot_server.jar:git-Spigot-2f787bd-501372f]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_server.jar:git-Spigot-2f787bd-501372f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot_server.jar:git-Spigot-2f787bd-501372f]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot_server.jar:git-Spigot-2f787bd-501372f]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot_server.jar:git-Spigot-2f787bd-501372f]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot_server.jar:git-Spigot-2f787bd-501372f]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot_server.jar:git-Spigot-2f787bd-501372f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at me.Fabricio20.Bukkit.Listeners.HubChest.CHEST_RightClickListener.getAllChests(CHEST_RightClickListener.java:36) ~[?:?]
	at me.Fabricio20.Bukkit.Listeners.HubChest.CHEST_RightClickListener.onRightClick(CHEST_RightClickListener.java:21) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot_server.jar:git-Spigot-2f787bd-501372f]
	... 18 more

**Comment by Yannici** [comment]
Hast ein Fehler in der shop.yml!

**Comment by HobbyzockerLP** [comment]
Ich sehe dort keinen Fehler...
Ich hab den Shop sehr gründlich bearbeitet...
Ich schau nochmal nach...aber in der Konsole steht alles erfolgreich geladen! Ich schick dir die shop.yml nachher ;)

**Comment by Yannici** [comment]
Der Shop wird beim Starten des Spiels geladen und nicht beim Laden des Spiels ;) Von dem her, ist klar, dass das Spiel erfolgreich geladen wird. Versuch mal den Inhalt der shop.yml hier: http://www.yamllint.com/ zu validieren.

**Comment by HobbyzockerLP** [comment]
OK werde es machen. Aber ich hatte mal in der shop.yml auch mal paar Fehler und konnte das Spiel starten, aber ich konnte nur den shop nicht aufmachen, mehr war es auch nicht...

**Comment by HobbyzockerLP** [comment]
Hey Yannici, hab die shop.yml validiert. Dort steht "Valid YAML". Also hab ich keinen Fehler gemacht....

Hier wenn du dich selbst überzeugen willst:
shop:
  armor:
    item: CHAINMAIL_CHESTPLATE
    name: "Rüstung"
    order: 10
    permission: bw.base
    lore:
    - Protect yourself with armor! Click here.
    offers:
    - item1:
        item: CLAY_BRICK
        amount: 1
      reward:
        item: LEATHER_HELMET
        amount: 1
        enchants:
          0: 1
    - item1:
        item: CLAY_BRICK
        amount: 1
      reward:
        item: LEATHER_LEGGINGS
        amount: 1
        enchants:
          0: 1
    - item1:
        item: CLAY_BRICK
        amount: 1
      reward:
        item: LEATHER_BOOTS
        amount: 1
        enchants:
          0: 1
    - item1:
        item: IRON_INGOT
        amount: 6
      item2:
        item: GOLD_INGOT
        amount: 4
      reward:
        name: '&aMagnetschuhe'
        lore:
        - Trage diese Schuhe und erhalte 33%
        - Wahrscheinlichkeit auf keinen Knockback!
        item: IRON_BOOTS
        amount: 1
    - item1:
        item: IRON_INGOT
        amount: 1
      reward:
        item: 303
        amount: 1
        enchants:
          0: 1
    - item1:
        item: IRON_INGOT
        amount: 3
      reward:
        item: 303
        amount: 1
        enchants:
          0: 2
    - item1:
        item: IRON_INGOT
        amount: 7
      reward:
        item: 303
        amount: 1
        enchants:
          0: 3
  swords:
    item: GOLD_SWORD
    name: Schwerter
    order: 20
    permission: bw.base
    lore:
    - Click here to get sword for attacking your enemies
    offers:
    - item1:
        item: CLAY_BRICK
        amount: 12
      reward:
        item: 280
        amount: 1
        enchants:
          19: 1
    - item1:
        item: IRON_INGOT
        amount: 1
      reward:
        item: 268
        amount: 1
        enchants:
          16: 1
          34: 3
    - item1:
        item: IRON_INGOT
        amount: 3
      reward:
        item: 283
        amount: 1
        enchants:
          16: 2
          34: 3
    - item1:
        item: IRON_INGOT
        amount: 8
      reward:
        item: 283
        amount: 1
        enchants:
          16: 2
          19: 1
          34: 3
    - item1:
        item: GOLD_INGOT
        amount: 5
      reward:
        item: 267
        amount: 1
        enchants:
          16: 2
          19: 1
          34: 3
  bows:
    item: 261
    name: "Bögen"
    order: 30
    permission: bw.base
    lore:
    - Prove yourself as a marksman with these wonderful bows
    offers:
    - item1:
        item: GOLD_INGOT
        amount: 3
      reward:
        item: 261
        amount: 1
        enchants:
          51: 1
    - item1:
        item: GOLD_INGOT
        amount: 7
      reward:
        item: 261
        amount: 1
        enchants:
          51: 1
          48: 1
    - item1:
        item: GOLD_INGOT
        amount: 13
      reward:
        item: 261
        amount: 1
        enchants:
          51: 1
          48: 1
          49: 1
    - item1:
        item: GOLD_INGOT
        amount: 13
      reward:
        item: 261
        amount: 1
        enchants:
          51: 1
          50: 1
          49: 1
    - item1:
        item: GOLD_INGOT
        amount: null
      reward:
        item: 262
        amount: 1
  eat:
    item: GRILLED_PORK
    name: Essen
    order: 40
    permission: bw.base
    lore:
    - Are you hungry? Get something to eat.
    offers:
    - item1:
        item: CLAY_BRICK
        amount: 3
      reward:
        item: GRILLED_PORK
        amount: 1
    - item1:
        item: GOLD_INGOT
        amount: 2
      reward:
        item: 322
        amount: 1
    - item1:
        item: IRON_INGOT
        amount: 1
      reward:
        item: 354
        amount: 1
  pickaxes:
    item: IRON_PICKAXE
    name: Spitzhacken
    order: 50
    permission: bw.base
    lore:
    - Destroy others blocks? Use these pickaxes.
    offers:
    - item1:
        item: CLAY_BRICK
        amount: 8
      reward:
        item: WOOD_PICKAXE
        amount: 1
        enchants:
          32: 1
          34: 1
    - item1:
        item: IRON_INGOT
        amount: 2
      reward:
        item: STONE_PICKAXE
        amount: 1
        enchants:
          32: 2
          34: 2
    - item1:
        item: GOLD_INGOT
        amount: 1
      reward:
        item: IRON_PICKAXE
        amount: 1
        enchants:
          32: 3
          34: 3
  blocks:
    item: SANDSTONE
    name: "Blöcke"
    order: 60
    permission: bw.base
    lore:
    - Get to the others! Possible with blocks.
    offers:
    - item1:
        item: CLAY_BRICK
        amount: 1
      reward:
        item: 24
        meta: 2
        amount: 2
    - item1:
        item: CLAY_BRICK
        amount: 7
      reward:
        item: 121
        amount: 1
    - item1:
        item: IRON_INGOT
        amount: 3
      reward:
        item: 42
        amount: 1
    - item1:
        item: CLAY_BRICK
        amount: 15
      reward:
        item: 89
        amount: 4
    - item1:
        item: CLAY_BRICK
        amount: 4
      reward:
        item: 20
        amount: 1
  usefulstuff:
    item: TNT
    name: "Nützliche Sachen"
    order: 70
    permission: bw.base
    lore:
    - Looking for useful stuff? Here are some!
    offers:
    - item1:
        item: GOLD_INGOT
        amount: 3
      reward:
        item: TNT
        amount: 1
    - item1:
        item: GOLD_INGOT
        amount: 1
      reward:
        item: 259
        amount: 1
    - item1:
        item: IRON_INGOT
        amount: 2
      reward:
        item: 54
        amount: 1
    - item1:
        item: GOLD_INGOT
        amount: 1
      reward:
        item: 130
        amount: 1
    - item1:
        item: CLAY_BRICK
        amount: 16
      reward:
        item: 30
        amount: 1
    - item1:
        item: CLAY_BRICK
        amount: 2
      reward:
        item: 65
        amount: 1
  drinks:
    item: POTION
    name: "Tränke"
    order: 80
    permission: bw.base
    lore:
    - Not enough? Use these potions and you'll feel better!
    offers:
    - item1:
        item: IRON_INGOT
        amount: 3
      reward:
        item: 373
        amount: 1
        meta: 8197
    - item1:
        item: IRON_INGOT
        amount: 5
      reward:
        item: 373
        amount: 1
        meta: 8229
    - item1:
        item: IRON_INGOT
        amount: 7
      reward:
        item: 373
        amount: 1
        meta: 8194
    - item1:
        item: GOLD_INGOT
        amount: 8
      reward:
        item: 373
        amount: 1
        meta: 8201
    - item1:
        item: GOLD_INGOT
        amount: 7
      reward:
        item: 373
        amount: 1
        meta: 8193
  Special:
    item: EMERALD
    name: "Spezial"
    order: 90
    permission: bw.base
    lore:
    - Sicher dir Vorteile gegenueber Anderen!
    - item1:
        item: GOLD_INGOT
        amount: 3
      reward:
        name: '&cRettungsplattform'
        lore:
        - "Rette dich vor dem Abstürzen"
        - mit der Rettungsplattform
        item: 369
        amount: 1
    - item1:
        item: IRON_INGOT
        amount: 5
      reward:
        name: '&7Trap'
        lore:
        - Tritt ein Gegner drauf, wirst du informiert
        - "und er kann sich nur eingeschränkt bewegen."
        item: 287
        amount: 1
    - item1:
        item: CLAY_BRICK
        amount: 64
      reward:
        name: '&4Schutzmauer'
        lore:
        - Aktiviere es und erhalte sofort eine
        - "5x3 große Mauer vor dir!"
        item: BRICK
        amount: 1
    - item1:
        item: GOLD_INGOT
        amount: 13
      reward:
        item: 368
        amount: 1
    - item1:
        item: IRON_INGOT
        amount: 6
      reward:
        name: '&fTeleportationspuder'
        lore:
        - Aktiviere dieses Pulver und du wirst
        - in 6 Sekunden an den Spawn teleportiert.
        - 'Achtung: Bewegen bricht den Vorgang ab!'
        item: 289
        amount: 1
    - item1:
        item: CLAY_BRICK
        amount: 64
      reward:
        name: '&cTNT-Schaf'
        lore:
        - "Aktiviere das TNT-Schaf! Es wird"
        - "auf den nächsten Gegner zugehen"
        - "und nach 30 Sekunden explodieren!"
        item: MONSTER_EGG
        meta: 91		
        amount: 1

**Comment by Yannici** [comment]
Der Fehler sagt aus, dass etwas nicht mit dem Shop stimmt. Es muss nicht unbedingt an der Formatierung liegen. Vielleicht verwendest du auch ein Meta-Value oder Items, die Bukkit/Spigot bzw. das Plugin nicht finden kann. Ist somit auf jeden Fall kein Fehler seitens des Plugins, sondern seitens des Anwenders (in dem Fall du).

**Comment by HobbyzockerLP** [comment]
Hab den Fehler selber gefunden... das war nicht amount:0...
