### ISSUE TITLE
Games can't load in Java 8

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#243]
Hello, I updated my server to Java 8 and if i hit /bw list, it saying "No existing map".
It's caused by Java 8, if I downgrade to Java 7, it works.

Thanks,
Granik24, www.hryozivot.cz

**Comment by Yannici** [comment]
I^'m testing the plugin in Java 8 the whole time! It's loading the games properly. So... can't reproduce that problem.

**Comment by Granik24** [comment]
There is problem with existing games. Sorry for my delayed respond.

**Comment by sebastianbinder** [comment]
@Granik24 - at the moment I'm screening all the issues. Is this one still a problem or resolved?

**Comment by Granik24** [comment]
@sebastianbinder Still not resolved.

**Comment by Granik24** [comment]
Probably solved. ;)
