### ISSUE TITLE
Villager ohne Shop

### ISSUE THREAD

**Issue by xeruck** [Yannici/bedwars-reloaded#245]
Moin,
ich habe jetzt mehrere Welten und alle Dorfbewohner durch getestet.
Aber meine Dorfbewohnen öffnen für ein bruchteil einer Sekunde den Pluginshop.
und wechseln dann direkt zum Vanilla Shop.

Das Plugin läuft mit Multiverse auf einer Seperaten map.

**Comment by Yannici** [comment]
Welche Minecraft Version?

**Comment by xeruck** [comment]
2 Versionen getestet.
1.8.5
1.8.7

Beide das gleiche problem.

**Comment by Yannici** [comment]
Da kann ja nur das Problem eines anderen Plugins der Übeltäter sein. Kann ich sonst nicht anders nachvollziehen. Noch nie jemand ein solches Problem gemeldet - von dem her ein weiteres Indiz dafür, dass es wohl an deinen anderen Plugins/Konfigurationen liegt.

**Comment by xeruck** [comment]
ich werde micha uf die suche begeben.
aber eigt. ist kein plugin vorhanden, das auf die villager shops zugreift.

**Comment by Yannici** [comment]
Das höre ich ganz oft ... und dann ist es doch "komischerweise" ganz anders ;)

**Comment by xeruck** [comment]
ja, es sind gleich 5 Plugins die den Shop angreifen.
ServerSigns
LogBlock
Lift
LWC
BuyRegion

hast du eine möglichkeit für mihc, den Shop andersweitig anzusteuern?

**Comment by Yannici** [comment]
Bisher nicht. Liegt also nicht an meinem Plugin und ich glaube es ist auch nicht unbedingt die Aufgabe meines Plugins sich darum zu kümmern, alle Abhängigkeiten zu berücksichtigen ;) Dafür sind ja die Server-Administratoren da.

**Comment by xeruck** [comment]
Das ist richtig. 
War nur eine Frage, hätte ja sein können das man die Items über Comands ansteuern kann und somit anders Handeln könnte^^

**Comment by xeruck** [comment]
Ich möchte dir noch sagen, wie ich das Problem gelöst habe, falls andere Leute das selbe Problem bekommen.

Mir hat es geholfen mit citizens einen npc zu erstellen --type villager.
Dieser NPC besitzt keinen Shop und somit wird der Bedwars Shop angezeigt.

es reicht vllt. schon einen Villager per Commandblocks zu erstellen, der keinen Shop besitzt.

gruß,
-Xeruck
