### ISSUE TITLE
[BedWars] Ideen

### ISSUE THREAD

**Issue by NikitaBanane04** [Yannici/bedwars-reloaded#246]
Ich habe paar Ideen und verbesserungen die man machen könnte :  

 /forcemap <map> - Damit man die Map ändern kann .

/start - Das der CountDown von 5 abzählt und nicht gleich startet .

Ein Voting System .

Ein Achievment System .

Das ChatSystem bischen besser machen , zum Beispiel wenn man /stats eingibt kann man diese     Binde Striche nicht weg machen .

----------[Stats]-------------   <--- Möchte das diese Striche weg sind  = [Stats] und nicht = ---[Stats]----
 Kills: 0
 Death: 0
 KD/r: 0
Wins : 0
Lose : 0

Das "SetBuilder" Der bauer (ersteller) der map auch im chat angezeigt wird .  

Habe natürlich noch mehr ideen , fallen mir grade aber nicht mehr ein .

**Comment by yannickko** [comment]
Dafür gibt es doch schon den Start Diamanten. Und soweit ich weiß steht ein Voting und Archivment System schon auf der ToDO von @Yannici

**Comment by Yannici** [comment]
Der Bauer der Map kann ich noch in den Chat einfügen. Ansonsten sind die Ideen leider eher unnötig oder stehen auf meiner ToDo-Liste wie @yannickko richtig erkannt hat.

**Comment by brainscript** [comment]
Das mit den Stats kann man doch ändern .... :neutral_face: Einfach die Sprachdatei bearbeiten.
