### ISSUE TITLE
Größe der Map

### ISSUE THREAD

**Issue by YouGamePlayHD** [Yannici/bedwars-reloaded#247]
Hi,
ist es möglich einen Code ($mapsize$) einzufügen, mit dem man auf dem Joinschild (oder im Title vom Scoreboard etc.) die Größe der Map im Format "AMOUNT_OF_TEAMS x PLAYERS_PER_TEAM" anzeigen kann? (Beispiel: GommeHD.net, rewinside.tv)
MFG
YouGamePlayHD :+1:

**Comment by Yannici** [comment]
Möglich schon, aber nicht ganz so trivial. Dadurch dass man im Plugin die Teams dynamisch setzen kann (d.h. es könnte auch ein Team mit 2 Spielern und ein Team mit 4 Spielern geben), ist es schwierig das dann anzeigen zu lassen. Man könnte zwar prüfen, ob alle Teams gleich viele Spieler haben, aber das geht dann gegen meine Ideologie der "voll-individuellen Konfiguration".

**Comment by Yannici** [comment]
Außerdem könnte man das ja auch im Region-Name verankern.

**Comment by Yannici** [comment]
Eher nicht so nötig dafür eine Extrafunktion einzubauen.
