### ISSUE TITLE
Spiel startet nicht

### ISSUE THREAD

**Issue by yannickko** [Yannici/bedwars-reloaded#248]
Hi,
bei mir startet das Spiel irgendwie nicht.
Egal ob mit Start Dia oder wenn der Countdown auf 0 gezählt hat :O
Benutze Spigot 1.8.7

**Comment by Yannici** [comment]
Mehr Details bitte ... Damit kann ich überhaupt nichts anfangen ... Error Logs etc.?

**Comment by yannickko** [comment]
Hey, hat sich erledigt war ein (ziemlich blöder) Fehler von mir, der dieses Verhalten verursacht hat.
