### ISSUE TITLE
Auto-Balance funktioniert nicht

### ISSUE THREAD

**Issue by NitroxydeX** [Yannici/bedwars-reloaded#249]
Hey Yannici!

Irgendwie scheint Auto-Balance nicht zu funktionieren. Es spielt dabei keine Rolle, ob es nur für eine Map oder Global gesetzt ist, die Spieler werden nicht automatisch auf die Teams verteilt. Irgendeine Idee?

**Comment by Yannici** [comment]
Idee habe ich keine, werde es später nochmal testen.

**Comment by NitroxydeX** [comment]
Alles klar.

**Comment by NitroxydeX** [comment]
Gibt's schon neue Infos dazu?

**Comment by Yannici** [comment]
Sobald ich zu Hause bin, werde ich testen. Sorry für die Verzögerung!

**Comment by Yannici** [comment]
Funktioniert bei mir ... Gerade nochmal getestet.

**Comment by NitroxydeX** [comment]
Was brauchst du denn für Informationen? Es wird halt nicht gebalanced, obwohl global und für Game gesetzt getestet.

**Comment by Yannici** [comment]
Welche Minecraft-Version? Stehen Errors im Log? Sorry, kann das nicht nachvollziehen. Bei mir passt alles.

**Comment by NitroxydeX** [comment]
Spigot 1.8.7, keine Errors.

**Comment by Yannici** [comment]
Nicht dass ich wüsste. Das heißt bei dir ist global-autobalance auf true?

**Comment by NitroxydeX** [comment]
genau.

**Comment by Yannici** [comment]
Sorry, keine Ahnung, funktioniert bei mir einwandfrei mit jeder Minecraft Version.

**Comment by xion87** [comment]
Same bug, player are not balanced, example 10 player in red team and 1 in blue and 5 in green, global balance do nothing
