### ISSUE TITLE
Umlaut Problems

### ISSUE THREAD

**Issue by helptiger** [Yannici/bedwars-reloaded#25]
Auf Deutsch: Umlaute werden inGame nicht korrekt angezeigt, Beispiele:
kein Texturepack, etc.
![umlaute 1](https://cloud.githubusercontent.com/assets/10258902/7119816/1008feee-e209-11e4-92f5-771d73271047.png)
![umlaute 2](https://cloud.githubusercontent.com/assets/10258902/7119815/10086d6c-e209-11e4-8b35-bd43553f9a79.png)
![umlaute 3](https://cloud.githubusercontent.com/assets/10258902/7119820/100bd498-e209-11e4-942e-edf5c94e6f87.png)
![umlaute 4](https://cloud.githubusercontent.com/assets/10258902/7119817/10090650-e209-11e4-9998-e87aa9182031.png)
![umlaute 5](https://cloud.githubusercontent.com/assets/10258902/7119819/100b839e-e209-11e4-8639-06f69965a9ca.png)
![umlaute 6](https://cloud.githubusercontent.com/assets/10258902/7119818/1009ac0e-e209-11e4-8a72-c1769870a136.png)

**Comment by Yannici** [comment]
Als unicode speichern (UTF-8).

**Comment by helptiger** [comment]
Wenn du Zeit hast, komm mal bitte kurz auf den ts, ist einfacher zu erklären. lg
