### ISSUE TITLE
Bungeecord Zurück zum HUB server funktioniert nicht!

### ISSUE THREAD

**Issue by logtainment** [Yannici/bedwars-reloaded#252]
Hallo,
ich verweise zu:
https://github.com/Yannici/bedwars-reloaded/issues/251#issuecomment-126888903

wie kann ich das ändern? Aber über den Lobbyserver kann man /server bw machen

**Comment by Yannici** [comment]
Bitte keine Issues mehr zu diesem Problem erstellen! Hier sollen nur Issues erstellt werden, die mit dem Plugin zu tun haben. Es geht hier nicht um Bungeecord. Wie du BungeeCord korrekt installierst etc. wird hier nicht erklärt.

**Comment by logtainment** [comment]
Hallo, ich habe Bungeecord installiert! Kannst du mir nicht helfen, warum es nicht geht! Ich kann /bungee machen und /server -..

**Comment by Yannici** [comment]
Nein kann ich nicht, weil es nicht an meinem Plugin liegt.

**Comment by logtainment** [comment]
Ja aber ich hab doch Bungee

**Comment by logtainment** [comment]
Na zu -..... um zu antworten ! ES LIEGT AN DEM PLUGIN

**Comment by Yannici** [comment]
Es liegt nicht am Plugin. Es kann nicht sein dass über 300 Server mit diesem Plugin auf Bungee laufen und AUSGERECHNET dein Server mit meinem Plugin + BungeeCord funktioniert nicht ;)

**Comment by yannickko** [comment]
Ich bin ein totaler Pluginnoob aber selbst ich habe das Plugin schon mit BungeeCord zum laufen gebracht, sodass alles funktioniert hat. Wenn du alles richtig einstellst wird es gehen.
Und @Yannici wird es garantiert besser wissen wie du.

**Comment by Phil870** [comment]
Und ich für meinen Teil wusste garnicht wie ich BungeeCord einrichte usw... nach 10 Minuten (~5 Minuten Tutorial) Hatte ich dann alles eingerichtet und es lief (!) Buggfrei

**Comment by yannickko** [comment]
Ich will ihm nichts unterstellen aber ich glaube er gehört zu den Leuten die denken sie müssen die BungeeCord.jar in den Minecraft Pluginorder machen :D

**Comment by logtainment** [comment]
@yannickko Erstens ich habe schon lange Bungeecord und viele Server. Es lag nur daran, dass Bungeecord nicht geupdated war. Und kannst du es besser?

**Comment by Yannici** [comment]
Nicht streiten ;) Alles okay.

**Comment by yannickko** [comment]
@logotainment @Yannici Entschuldigung. :)
