### ISSUE TITLE
Kann keine TNT-Schafe spawnen...

### ISSUE THREAD

**Issue by mycraft1099** [Yannici/bedwars-reloaded#254]
Liegt wohl an diesem Error... "Severe: [BedwarsRel] Plugin BedwarsRel v1.2.5 has failed to register events for class io.github.yannici.bedwars.Listener.EntityListener because org/bukkit/event/entity/EntitySpawnEvent does not exist."

Ich hab mal in der server.jar nachgeschaut und da gibt es unter diesem Pfad wirklich keine EntitySpawnEvent.class aber eine CreatureSpawnEvent.class
Auch umbenennen bringt nichts.

Ich benütze CraftBukkit 1.8 (von hier: getspigot.org) und die neuste Version deines Plugins.

**Comment by mycraft1099** [comment]
Liegt wohl an Bukkit... mit spigot gehts

**Comment by Yannici** [comment]
Hm, ich werde mir das mal anschauen. Möglicherweise liegt das wirklich an einem nicht vorhandenen Event in Bukkit (Craftbukkit). Danke für's melden.

**Comment by Yannici** [comment]
Fixed in https://github.com/Yannici/bedwars-reloaded/commit/1e81be016f004baa02775227ae4bd25c39e8b3ae
