### ISSUE TITLE
Server geht immer nach Spiel aus und startet nicht neu!

### ISSUE THREAD

**Issue by logtainment** [Yannici/bedwars-reloaded#255]
Hallo,
mit Bungee geht alles wieder. Aber nach einem Spiel geht der Server immer aus und startet nicht neu. Mein Start Script heißt start.sh

**Comment by Yannici** [comment]
Du musst in diesem start.sh einen Neustart erzwingen, sobald der Server beendet. Nutzt du Spigot? Wenn ja, kannst du auch ein Restart-Script einrichten. Wie das genau funktioniert, musst du auf Spigotmc.org nachschauen.
