### ISSUE TITLE
Win Title nicht ändert sich nicht!

### ISSUE THREAD

**Issue by HobbyzockerLP** [Yannici/bedwars-reloaded#256]
Beim Win Title steht immer der alte Text, obwohl ich den geändert habe... im chat wird es aber richtig angezeigt! Ich denke das ist ein Bug.

**Comment by Yannici** [comment]
Alles korrekt gespeichert? /bw reload config bzw. /bw reload probiert?

**Comment by HobbyzockerLP** [comment]
Den Fehler habe ich schon lange.... nichts hilft

**Comment by Yannici** [comment]
Komisch, teste ich mal. Kannst du als Beispiel mal den eingestellten Text der config geben und vllt. ein Screenshot von dem, was du angezeigt bekommst?

**Comment by yannickko** [comment]
Selbes Problem. Hat mich auch schon länger gewundert warum der Text sich nicht geändert hat.

**Comment by Yannici** [comment]
Ok, ich weiß woran das nun liegt ;) Der Win-Title müsst ihr in der locale ändern, nicht in der config. Der Text wird aus _ingame_ => _title_ => _win-title_ und _win-subtitle_ gezogen!
