### ISSUE TITLE
Maps laden nach Neustart nicht

### ISSUE THREAD

**Issue by Icecrown-wow** [Yannici/bedwars-reloaded#270]
Moin. Wenn der Spigot Server neu startet, muss ich immer erst das Bedwars Plugin neu laden, dass er mir die Map lädt.

Das ist mit nem Netzwerk ziemlich nervig, da ich nach dem restart immer auf den Server muss, und das Plugin neu laden muss :(

**Comment by Yannici** [comment]
Welches Multiworld Plugin nutzt du? Multiverse-Core?

**Comment by Icecrown-wow** [comment]
Nein. Multiworld.

**Comment by YouGamePlayHD** [comment]
Hast du schon /bw save gemacht?

**Comment by Icecrown-wow** [comment]
Die Maps werden nach jedem Manuellem /bw reload geladen. Beantwortet sich also von selbst.

**Comment by Yannici** [comment]
Hm, da scheint irgendwo eine Abhängigkeit zu fehlen während BW geladen wird ... kannst du mir mal eine Plugin-Liste geben, die auf dem BW-Server läuft?

**Comment by Icecrown-wow** [comment]
Multiworld, Und dein Bedwars Plugin. Mehr nicht :)

(Ich hab mal Multiverse anstatt Multiworld Installiert. Mit Multiverse klappt es problemlos.

**Comment by Yannici** [comment]
Schon ziemlich komisch. Wie ist denn der korrekte Name vom Multiworld-Plugin in der Pluginliste? Heißt das auch korrekt "Multiworld".

**Comment by Icecrown-wow** [comment]
Mache ich :)

**Comment by sebastianbinder** [comment]
@Icecrown-wow Was ist hier der Stand der Dinge? Hat sich das Problem gelöst? Bitte um kurzes Feedback. Andernfalls werde ich den Issue in einer Woche schließen.
