### ISSUE TITLE
BedWars BUG | Please HELP ME!!!!

### ISSUE THREAD

**Issue by Tamiyami** [Yannici/bedwars-reloaded#274]
When I play BedWars team to team, I kill the second team two men, but the game does not end! Help please!

**Comment by Tamiyami** [comment]
Я имею в виду, что такие nachalasya игру хорошо играть, я играю убиты противоборствующей команды, в команде было двое мужчин, я их убил но они играют снова, они убили их снова появилась.

**Comment by Tamiyami** [comment]
I mean here is that such started game play well, I play killed the opposing team as well, the team had two men I killed them but they play again, they killed them appeared again.

**Comment by Yannici** [comment]
You already have an issue! Stop spaming with "HELP ME!!!!!"
