### ISSUE TITLE
Shop bug?

### ISSUE THREAD

**Issue by ritolika** [Yannici/bedwars-reloaded#281]
![2015-08-18_12 58 03](https://cloud.githubusercontent.com/assets/9406612/9327356/ce1ca7b6-45a8-11e5-8673-b3918f22e39f.png)
So i made a new map and when testing my shop doesn't come up anymore this just comes up ^^^^

**Comment by HobbyzockerLP** [comment]
Your shop.yml has an error! I had this problem ,too.

**Comment by Yannici** [comment]
This often comes up, when your shop.yml has an error like @HobbyzockerLP already said.

**Comment by sebastianbinder** [comment]
@ritolika Have you solved the problem? If not, please give us an update on this issue or I'll close this one in one week.
