### ISSUE TITLE
Chat Prefix Probleme etc.

### ISSUE THREAD

**Issue by HobbyzockerLP** [Yannici/bedwars-reloaded#283]
1) Ich hab ein Chatprefix Plugin, das mit Pex zusammen arbeitet. Mein Chatformat: '$group %p: %m'
Der Chatprefix hat keine Anzeigefehler, aber was mich stört ist, dass der Chatprefix in bedwars auch mitübernommen wird! Der Bedwars Chatprefix wird nicht angezeigt!
2) Schafe folgen Spectatoren (hab den neuesten Build) und fusetime buggt. Hab auf 45.0 gestellt, aber Schafe  explodieren nach kurzer Zeit....

**Comment by Yannici** [comment]
1) Probier mal mit "overwrite-names" auf "true".
2) Da scheinst du wohl nicht den neusten Build zu haben ... Wurde hier gefixt: https://github.com/Yannici/bedwars-reloaded/commit/bb2d94b9189dea14b3814b3416842ca6a62373e2. Fusetime-Bug fixe ich.

**Comment by HobbyzockerLP** [comment]
Overwrite names ist immer an bei mir.... und ich hab den neusten Build...

**Comment by HobbyzockerLP** [comment]
Ich probiers mal mit den Build von heute, mal sehen ob es geht :)

**Comment by Yannici** [comment]
Puh ... immer diese Prefixes. Ich kann nicht auf alle Plugins Rücksicht nehmen. Mein Plugin versucht das Beste. Vielleicht liegt es an dem display-name-fix.

**Comment by HobbyzockerLP** [comment]
$displayname$? Weiß nicht was du genau meinst ^^

**Comment by Yannici** [comment]
Ich weiß glaube schon wie ich das fixen könnte :P

**Comment by HobbyzockerLP** [comment]
Sags mir xD

**Comment by Yannici** [comment]
Das muss ich im Java-Code machen ;) Keine Sorge.

**Comment by HobbyzockerLP** [comment]
Einige Neuigkeiten? @Yannici

**Comment by Yannici** [comment]
Nein. Hatte die letzten Wochen Urlaub, habe da nichts getan, sorry. @HobbyzockerLP

**Comment by HobbyzockerLP** [comment]
Schon was gemacht? @Yannici
