### ISSUE TITLE
Help can not be placed blocks in game [1.2.7]

### ISSUE THREAD

**Issue by WillCraftero** [Yannici/bedwars-reloaded#288]
Hello! I compiled the latest version of the plugin, and the plugin works normally, but when I go into an arena not allow me to place blocks , you help me please to solve this 
Thanks!

**Comment by Yannici** [comment]
Make sure you have disabled spawn-protection in the server.properties!

**Comment by HobbyzockerLP** [comment]
Kann bei einer Map auch keine Blöcke setzen, bei allen anderen geht es... Kann nicht an der Map liegen, da ich dort alles veränder kann, wenn ich mich dorthin teleportiere.

**Comment by Yannici** [comment]
Did you set the region correctly?

**Comment by HobbyzockerLP** [comment]
Eigentlich schon, kann echt sein, dass ich da ein Fehler gemacht habe^^, werde die location überarbeiten!

**Comment by LoLoLP1** [comment]
Habe ich auch gemacht.

**Comment by sebastianbinder** [comment]
@HobbyzockerLP Ist dieser Issue noch relevant? Bitte um kurzes Feedback. Sonst werde ich diesen in einer Woche schließen um ein bisschen Ordnung hier zu schaffen :)

**Comment by sebastianbinder** [comment]
@WillCraftero Is this issue still unresolved? Please give me an update on this or I'll close the issue in one week. Thank you!

**Comment by HobbyzockerLP** [comment]
@sebastianbinder  hat sich schon lange geklärt^^, diesen issue habe ich nicht erstellt.
