### ISSUE TITLE
World Reset!

### ISSUE THREAD

**Issue by jass01** [Yannici/bedwars-reloaded#295]
Hello i just want to say i have a problem with the plugin , the blocks after the end of the game remain and the map doesent reset automaticly , i need help 
reply 
i just need a automatic plugin who reset automaticly the worlds after the end of the game or when one teams wins

**Comment by HobbyzockerLP** [comment]
The world will reset after game start!

**Comment by jass01** [comment]
Nope Nothing Bro... i tried to play again but nothing 
-Any Help? Update to 1.2.7?

**Comment by Granik24** [comment]
So, okay.
Do you have well adjusted loc1 and loc2 position?
Can you send me your plugin list? 
What version od BedWarsRel you ussing?

**Comment by jass01** [comment]
yeah i tryed to adjust the loc1 and loc2 and my plugin list are very simple just basic like worldedit , worldeditgui, Multiverse-core , Bedwars Rel 1.2.6

**Comment by jass01** [comment]
the blocks that the players used before in game remain afer new game

**Comment by Granik24** [comment]
So, update to latest WE 6.1.
Any error log in console?

**Comment by KukyMan** [comment]
Ahoj, Granííku :D Na našem serveru máme region nastavený dobře (jinak by tam nešlo stavit) a taky se nám to občas neresetne.. Může být problém v tom že máme na serveru 43 pluginů ?

Jo, a ještě, kdyby jsi mě odpověděl, kolik máte na HoZ pluginů ?
