### ISSUE TITLE
BungeeCord: RestartScript

### ISSUE THREAD

**Issue by MinecraftProXX** [Yannici/bedwars-reloaded#298]
Kann mir jemand ein RestartSkript für Linux geben um nach der Runde den Server neuzustarten?
Alle die ich probiert habe funktionieren nicht richtig und das in der Wiki ist für Windoof..

**Comment by megadampfnudel** [comment]
Benutz doch die Restart Funktion von Spigot und als Startupscript das:

#!/bin/bash
java -Xmx1G -jar spigot_server.jar

Funktioniert bei mir auch super.

**Comment by MinecraftProXX** [comment]
ok

**Comment by yannickko** [comment]
@megadampfnudel Reicht das? Muss das nicht mit screen gemacht werden damit es läuft?

**Comment by megadampfnudel** [comment]
@yannickko Ja das funktioniert. Ich starte einfach den Server über das Skript und dann läufts wenn die Runde vorbei ist startet der Server neu. Screen hab ich am Anfang gemacht aber braucht man nicht unbedingt.
