### ISSUE TITLE
Veränderungen vornehmen

### ISSUE THREAD

**Issue by Timmitechniker** [Yannici/bedwars-reloaded#299]
Darf ich mit diesem Plugin ein anderes Game betreiben? Damit meine ich: Die Wörter ändern und ein paar Funktionen hinzufügen? Wenn ja wäre das echt cool da ich nichts anderes passendes gefunden habe.Du kannst dir das Game ja mal ansehen.  LG Timmitechniker

Server IP:  Join.starmineMC.net
Game Name: Wars of Planets

**Comment by HobbyzockerLP** [comment]
Im Plugin kannst du alles Konfigurieren!
Die Wörter kannst du natürlich andern, dafür gibt es die Locale. Aber neue funktionen einfügen... Da bedienst du dich an Yannicis code...

**Comment by Timmitechniker** [comment]
Darum Frage ich ja ob ich dies darf :D ... oder muss ich ein ganz eigenes Plugin machen

**Comment by Yannici** [comment]
Ich sehe es leider nicht so gerne. Manche haben mir dafür auch schon eine "Abfindung" bezahlt, was ich begrüße. Ansonsten sollten jegliche Funktionen mitgeteilt werden, um so entscheiden zu können, ob es Sinn machen würde, dies dem Plugin hinzuzufügen (pull request). Außerdem sollte bei geändertem Code __immer__ irgendwo klar und deutlich mein Name stehen, sodass klar erkenntlich ist, dass es sich um eine veränderte Version __meines__ Plugins handelt.

**Comment by Timmitechniker** [comment]
Das heißt .. ich muss ein Plugin schreiben was mit deinem NICHTS zutun hat aber in irgendeiner weise die Funktion erfüllt

 oder ich schreibe hier das Vorhaben:
 Ich habe ein Spiel bei dem man Craften muss dies ist aber nicht möglich. Darf ich diese Funktion ändern? Wenn nein dann macht wohl das von Oben sinn.

**Comment by Yannici** [comment]
Dann mache ich einfach ein config-Eintrag, bei dem das Craften ein- bzw. ausgeschaltet werden kann in der nächsten Version. Dann bist du glücklich und musst nicht an meinem Code basteln und eine Copyright-Information hinzufügen ^^

**Comment by Timmitechniker** [comment]
Ja das wäre echt mega... Danke :D
