### ISSUE TITLE
Problem with signs

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#30]
Hi, 
I have little problem with Signs. 
My arena name is "FloatingHouses". This is too much long for 1 line.

You maybe can set it to format 

[bw]
game

**Comment by Granik24** [comment]
Or you can set /bw setdisplayname. That should be cool. You can create arena name "fh" and set display name to "Floating Houses". ID of that arena = "fh" Name = "Floating Houses"

**Comment by Yannici** [comment]
Thank you, I'll think about it :)

**Comment by Yannici** [comment]
Fixed in commit: https://github.com/Yannici/bedwars-reloaded/commit/1d2b48865240ec79e9dfd913de79f73167840066

**Comment by Granik24** [comment]
It can be cool to have name of arena, no of world :)
