### ISSUE TITLE
Custom lobby items

### ISSUE THREAD

**Issue by ETblaky** [Yannici/bedwars-reloaded#301]
There's anyway to give custom items to the player when it's waiting in the lobby ? i'd like to give them a sword for choose their kit.
obs: Sorry for my bad english, i'm brazilian =)

**Comment by Granik24** [comment]
That's good idea! :+1:

**Comment by brainscript** [comment]
:heavy_plus_sign::+1:

**Comment by yannickko** [comment]
+1

**Comment by sebastianbinder** [comment]
Duplicate - included in #294
