### ISSUE TITLE
Can't set Blocks in the Game

### ISSUE THREAD

**Issue by LoLoLP1** [Yannici/bedwars-reloaded#304]
When I'm in the game I can not place blocks, if I'm not in the game already. Wonder why ?

**Comment by HobbyzockerLP** [comment]
Du kannst auch deutsch schreiben, dein englisch versteht man nicht! 
Du hast bestimmt die Regionen nicht richtig gesetzt, ist mir auch mal passiert. Welche Plugins hast du noch auf deinem Server?

**Comment by LoLoLP1** [comment]
Ok bin deutscher

**Comment by LoLoLP1** [comment]
Meine Plugins

**Comment by LoLoLP1** [comment]
Chais, iConomy, NoteBlockAPI, EasyJetpack, ZAVAutoMessager, Vault, PermissonsEx, Multiverse-Core, Modifyworld, MChat, BedwarsRel, ItemStay, ChestShop, ChestIcon

**Comment by Phil870** [comment]
Ich würde mal darauf tippen das du bei PEX den Usern die Rechte bei Modifyworld Blöcke zu setzen nicht gegeben hast.. da du aber selbst keine Blöcke setzen kannst.. hm versuch mal wie HobbyzockerLP schon schrieb, die Regionspunkte neu zu setzen ( /bw setregion gamename loc1/loc2)

**Comment by HobbyzockerLP** [comment]
Du musst die Regionspunkte diagonal setzen! Einen über der Map einen unter der Map.

**Comment by HobbyzockerLP** [comment]
Hier eine"Skizze":
https://wiki.nitrado.net/de/images/9/98/WorldEdit-Cuboid.png

**Comment by LoLoLP1** [comment]
Aha

**Comment by LoLoLP1** [comment]
Ok

**Comment by HobbyzockerLP** [comment]
Diesmal nicht gescheitert?
Close this Issue! Bringt nichts, wenn du es offen lässt.
