### ISSUE TITLE
Item Frames can be broken, so item gets into inventory

### ISSUE THREAD

**Issue by sebastianbinder** [Yannici/bedwars-reloaded#306]
Hi. Ich habe auf meiner Map zu Dekozwecken Item Frames (halt diese Bilderrahmen inkl. Items "drin") platziert. Sinn davon ist natürlich nicht, dass die Spieler an den Inhalt kommen sollen, sondern es handelt sich ausschließlich im Deko. Platziert man nun jedoch an einem Block einen solchen Rahmen, kann der Spieler zwar nicht den Block dahinter abbauen, da dieser ja durch das Spiel geschützt ist, aber er kann bspw. einen Block Sandstein direkt davor platzieren, sodass der Rahmen zerstört wird und dieser inklusive Inhalt droppt. Das ist nicht gut so und wäre schön, wenn das behoben werden kann - bspw. indem man keinen Block in das Feld des Rahmens setzen darf… Besten Dank und viele Grüße :)

**Comment by sebastianbinder** [comment]
@Yannici Welcher Issue ist denn das "duplicate" - habe nämlich nach einem solchen Bug bisher schon gesucht, aber mit der Suche nichts gefunden. Und hätte gerne den Fortschritt mit Milestones und Commits verfolgt :) Und nebenbei mal ein Lob für dieses grandiose Plugin!!!

**Comment by Yannici** [comment]
#233 Mehr oder weniger dasselbe. Zwar nicht in diesem Szenario, würde aber dazu passen. Darum merge ich das hier mal.

**Comment by sebastianbinder** [comment]
Okay danke für die Info :)
