### ISSUE TITLE
"an internal error occurred while attempting to perform this command"

### ISSUE THREAD

**Issue by ArrowCrafter** [Yannici/bedwars-reloaded#309]
Das hinzufügen von Spielen klappt, aber das erstellen von teams nicht.
Da kommt ich die Meldung: "an internal error occurred while attempting to perform this command"

**Comment by Yannici** [comment]
Die Team-Farben falsch eingegeben? Oder anstatt Team-Farbe, die Team-Farbe eingegeben?

**Comment by ArrowCrafter** [comment]
Es sollte alles richtig sein: ./bw addteam BWPlatzangst8x1 RED Rot 1

**Comment by ArrowCrafter** [comment]
Oh Mann....
Du hattest recht. Ich habe RED und Rot vertauscht...
