### ISSUE TITLE
Some error in console

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#31]
I have this error in console: http://pastebin.com/gSGrmgqu
IDK why

**Comment by Yannici** [comment]
I'll check that.

**Comment by Yannici** [comment]
When this error happen?

**Comment by Granik24** [comment]
I don't know. I'll try to test it at home. (now im at school.)

**Comment by helptiger** [comment]
Same on 1.8.1
http://pastebin.com/t50HA2ay

**Comment by Yannici** [comment]
Würde es gern nachstellen, weiß aber nicht wie. Wird der gleiche error sein wie @Granik24 schon gepostet hatte.

**Comment by Granik24** [comment]
I have next error. Using command /bw addteam TheCrystal Modri blue 5 
Error: http://pastebin.com/2h3kWnih

**Comment by Yannici** [comment]
Fixed that error: https://github.com/Yannici/bedwars-reloaded/issues/31#issuecomment-93589889

**Comment by Yannici** [comment]
Fixed the errors in commit https://github.com/Yannici/bedwars-reloaded/commit/ad1c4a61c2bcf21627ca4554f6b0f290567fa221
