### ISSUE TITLE
Respawn Schutzzeit deaktivieren & Shop Items

### ISSUE THREAD

**Issue by ArrowCrafter** [Yannici/bedwars-reloaded#312]
Ich habe zwei Fragen:
1. Wenn man stirbt ist man ein paar Sekunden lang unverwundbar bzw. man kann nicht geschlagen werden. Kann man das deaktivieren?
2. Wenn ich eigene Items in der config hinzufügen möchte klappt das nicht. 
Mache ich irgendwas falsch? 
Ich kopiere das:
- item1:
                item: GOLD_INGOT
                amount: 2
              reward:
                item: IRON_PICKAXE
                amount: 1
                enchants:
                    32: 1
und füge es dann wieder ein und ersetze dann die Sachen. Doch das Problem ist das im Notepad die Zeile "item1" Rot wird und dann anschließen im Spiel auch nicht funktioniert.

Edit:
Das komische ist das das nicht das einzigste Plugin ist wo das nicht mit dem hinzufügen geht. Wenn ich z.B bei PermissionsEx bei den permissions.yml was hinzufügen möchte mit einem - wir das direkt Rot angezeigt und funktioniert auch nicht.

**Comment by brainscript** [comment]
@ArrowCrafter Einfach die NPP-Optionen wie unten gezeigt anpassen:
![optionsnpp](https://cloud.githubusercontent.com/assets/8706734/10116359/ef857844-6432-11e5-8056-2b3cc8c83bd0.PNG)

**Comment by ArrowCrafter** [comment]
Danke :)

**Comment by HobbyzockerLP** [comment]
Beim bearbeiten einer yaml Datei muss ganz am Rand gehen und dann einfügen.

**Comment by HobbyzockerLP** [comment]
Respawn protection auf 0 setzen in der bw config und in den Server properties.

**Comment by ArrowCrafter** [comment]
Hab ich schon gemacht

**Comment by Yannici** [comment]
Die Unverwundbarkeit ist nicht das Problem meines Plugins. Ich glaube Essentials verursacht solch ein Verhalten, mein Plugin jedenfalls nicht. Ich kann das auch nicht verhindern.
