### ISSUE TITLE
[IDEEN] für noch bessere Spiele

### ISSUE THREAD

**Issue by TechPlayHD** [Yannici/bedwars-reloaded#320]
•Wenn man Gewinnt kommt ein Feuerwerk auf
•~~Es gibt eine Enderperle im Shop~~ _Kann man selbst hinzufügen._
•~~Der Shop wird automatisch mit der Sprache des Plugins übersetzt!~~ _Finde ich nicht unbedingt notwendig. Das Übersetzen dauert keine 2 Minuten._
•~~Wenn das Bett  von jemanden abgebaut wurde steht als Titel "Dein Bett wurde abgebaut!~~ _Vorschlag existiert bereits_

**Comment by Yannici** [comment]
I edited your ideas.

**Comment by TechPlayHD** [comment]
Thank you!

Can't you speak German?

**Comment by Yannici** [comment]
Siehe oben ... Ich hätte deine Ideen nicht auf Deutsch beantworten können, wenn ich kein Deutsch können würde.

**Comment by TechPlayHD** [comment]
Ups!

Sorry ;(

**Comment by TechPlayHD** [comment]
Kann ich die Config.YML mit der von Github erstzen?

**Comment by Yannici** [comment]
Ähm, ja, aber ich weiß nicht wieso das nötig wäre.

**Comment by sebastianbinder** [comment]
@TechPlayHD ist es für dich okay, wenn ich den Issue schließe? Weil wir haben mit Issue #375 einen Feature Request der nur das Feuerwerk fordert und es wäre somit übersichtlicher. Die Implementierung werde ich auch sicher bald übernehmen.
