### ISSUE TITLE
Problem in restarting server

### ISSUE THREAD

**Issue by Creeper96** [Yannici/bedwars-reloaded#323]
I have some BedWars servers in bungeemode and they work fine.
After a number of games, the server didn't restart, but still enabled, but the motd of the plugin tell that the server is going to be rebooted.
Players can enter into and break and grief everything.
In console i don't have any error

**Comment by Yannici** [comment]
Try to use the latest build from http://ci.yannici.de/job/BedwarsRel/lastSuccessfulBuild/
It has a new config `full-restart` in the `bungeecord` section. Try to turn it off. It doesn't restart the server anymore.

**Comment by sebastianbinder** [comment]
@Creeper96 Is this one here solved? If yes, please close the issue (or I'll do it for you in one week).
