### ISSUE TITLE
Erweiterung

### ISSUE THREAD

**Issue by Wullverin** [Yannici/bedwars-reloaded#325]
Hi ich Hätte ein paar gute Ideen
1.)
Eine gute Erweiterung währe auch das man die Ressourcen nicht mehr ins inventar bekommt sondern als XP gutgeschrieben bekommt (Die Werte per Config einstellbar) damit das Inventar nicht immer zugemüllt wird und man mit dem Ressourcen im Shop einkaufen kann.

Nicht verbrauchte Ressourcen können per Gutschein Item an Teammitglieder weitergegeben werden bzw in Kisten eingelagert werden(Werte am besten auch per Config einstellbar).

2.) Eine möglichkeit um die Items die von den Resourcenspawner gedroppt werden anzupassen.
z.B. Statt Bronze ein anderes Item zuweißen.

MFG
Wullverin

**Comment by Yannici** [comment]
1) Unnötig
2) Gibt es schon.
