### ISSUE TITLE
Bug with arena join and leave

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#33]
I tried to join and leave arena 3x and it seems like arena started but it stucked in the lobby. 
After that, it writing "Teleportation to loby in..."

Screen: http://gyazo.com/0c3d85ce71e35bd2ed346269e6af2ccd
Screen 2: http://gyazo.com/8fea2e3ab3eb803c9fb6dc4e35c9f100

It's on my server, online nonstop. If you want, you can check it out. Thanks for support.

**Comment by Yannici** [comment]
What about a /reload? Then it should work again ...
I can't figure out why this is happen, but I will try to fix it.

**Comment by Yannici** [comment]
Can you reproduce that? And how can I reproduce that?

**Comment by Yannici** [comment]
I think that is a problem with the changed countdown starter in commit https://github.com/Yannici/bedwars-reloaded/commit/a2f85268eafc1f24300d427ac9f82824688f1d48
Every team has at least one player to start the lobby countdown!

**Comment by Granik24** [comment]
You can reproduce it: 
Join to arena, leave arena. Join to arena, leave arena.
After that, arena start writing "Teleport to lobby"

**Comment by Yannici** [comment]
Fixed with commit https://github.com/Yannici/bedwars-reloaded/commit/1ecbfbccfde1e2522d651a296537694074254a56
