### ISSUE TITLE
Request: EntityDamageEvent

### ISSUE THREAD

**Issue by sebastianbinder** [Yannici/bedwars-reloaded#333]
Hi @Yannici,
wenn ich https://github.com/Yannici/bedwars-reloaded/blob/master/src/io/github/yannici/bedwars/Listener/EntityListener.java#L166 und https://github.com/Yannici/bedwars-reloaded/blob/master/src/io/github/yannici/bedwars/Listener/EntityListener.java#L189 richtig interpretiere, dann können dadurch nur Spieler Schaden bekommen, oder?
Könntest du das irgendwie analog zu der Config in https://github.com/Yannici/bedwars-reloaded/blob/master/config.yml#L180 gestalten, dass man da Entities listen kann, die bspw. in meinem Fall, das Anti-Hack-Plugin spawnt und somit dann Schaden nehmen dürfen?
Wäre aus Performancegründen echt super, weil es werden in einer langen Runde echt viele Entities gespawnt.
Danke :)

**Comment by Yannici** [comment]
Das siehst du so richtig. Kann ich hinzufügen, ja.

**Comment by sebastianbinder** [comment]
Das wäre echt super :) Danke schon mal!
