### ISSUE TITLE
Remove Shop

### ISSUE THREAD

**Issue by AnOwner** [Yannici/bedwars-reloaded#334]
Hello ! I've download your plugin but i don't very like your Shop, i prefer my other shop plugin.
How can i disable the shop ?
Sorry for my bad english, i'm french.
Thanks you :)

**Comment by Yannici** [comment]
This is not possible. I don't know what is wrong with the shop?

**Comment by AnOwner** [comment]
Ni, sorry finally i choose your shop because i did't like because it was in Germany, now i translate un french ;)

**Comment by Yannici** [comment]
Well done ^^
