### ISSUE TITLE
Cant Break The Eggs

### ISSUE THREAD

**Issue by TrizzGR** [Yannici/bedwars-reloaded#342]
anyone cant break the eggs ith pickaxe without pickaxe when they are bricked they goes back to place and nothing happens please help

**Comment by Yannici** [comment]
Learn english, I don't understand anything.

**Comment by TrizzGR** [comment]
We start game normally but when we reach enemie's egg its undestroyable

**Comment by HobbyzockerLP** [comment]
Do you mean the spawn egg which can spawn mobs?

**Comment by TrizzGR** [comment]
No I mean the dragon egg

**Comment by Yannici** [comment]
Dragon egg is still no block! This cannot be used as a game block ...

**Comment by HobbyzockerLP** [comment]
You can break dragon eggs with pistons.
