### ISSUE TITLE
Chest Problem

### ISSUE THREAD

**Issue by AnOwner** [Yannici/bedwars-reloaded#344]
Hello ! I've a problem, i set correctly the game (i think), i set loc1 and loc2 and i have 2 teams: Bleu(BLUE) and Rouge(RED). When i start the game, my friend place items in the BLUE chest and me in the RED chest. When we leaved, we back to the game: my friend didn't have items and me yes.
How can i fix it ? 
Thanks you ! :)

**Comment by sebastianbinder** [comment]
Hi @AnOwner. There is already issue #291 talking about the same problem and @Yannici is investigating and trying to fix this bug.

**Comment by Yannici** [comment]
See #291
