### ISSUE TITLE
Fricking Compass Game Menu

### ISSUE THREAD

**Issue by TrizzGR** [Yannici/bedwars-reloaded#346]
![2015-11-12_21 00 09](https://cloud.githubusercontent.com/assets/15716486/11128139/a4491a7a-8980-11e5-9fa8-27bccfd3e718.png)
Dear Yanicii your plugin is perfect and works awesome but please tell me how to remove this game menu from compass i cant find any option in config.yml please tell me i beg you i cant handle it anymore

**Comment by Yannici** [comment]
What? I don't know what this menu is?!

**Comment by TrizzGR** [comment]
If I will press one of eggs it will take me to bedwars lobby to choose team please I'm sure there is a way to remove it

**Comment by Yannici** [comment]
I don't know these eggs!!! Never have implemented it!
