### ISSUE TITLE
HubMagic Unterstützung einfügen und  Commands ohne bw

### ISSUE THREAD

**Issue by megadampfnudel** [Yannici/bedwars-reloaded#347]
Hey,
Hab ne Frage bzw. eher einen Vorschlag, ob du HubMagic Unterstützung für BungeeCord hinzufügen kannst. Weil man sonst immer auf eine bestimmte Lobby gemovet wird, und wenn ich an der grad was ändere hab ich auf der Lobby whitelist an und die Spieler werden komplett gekickt. Hab schon n paar Plugins gesehen die das haben. Wäre echt nice hoffe du bekommst das hin 
LG MegaDampfnudel

EDIT: Es wäre auch nice wenn im BungeeCord Modus die Commands kein bw vorne dran stehen haben, falls das möglich ist.

**Comment by sebastianbinder** [comment]
@megadampfnudel Schau dir bitte die Konversation in #387 an. Eine solche Anpassung wird es nicht geben. Ich hoffe du verstehst die Hintergründe.
