### ISSUE TITLE
Plz Help Me With Shop What Did I Rong?

### ISSUE THREAD

**Issue by blijgozertje** [Yannici/bedwars-reloaded#351]
[shop.txt](https://github.com/Yannici/bedwars-reloaded/files/43008/shop.txt)
Tell Me What I Need To Change!

**Comment by sebastianbinder** [comment]
First of all it needs to be a .yml file.

**Comment by blijgozertje** [comment]
It is but i cant upload a .yml file

**Comment by sebastianbinder** [comment]
A really common problem with .yml files in general is wrong indentation. Make sure the indentation always is two spaces (no tabs / one space more / one space less).

Fyi, you can paste the content of your .yml file directly here and style it as a .yml code snippet with markdown.

Then: Is there any error showing up on your console?
And: What is your actual problem? The shop is not loading? The game is not starting?

**Comment by blijgozertje** [comment]
The shop is not loading

This is Log console
org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) 25.11 17:00:10 [Server] WARN at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) 25.11 17:00:10 [Server] WARN at io.github.yannici.bedwars.Main.loadShop(Unknown Source) 25.11 17:00:10 [Server] WARN at io.github.yannici.bedwars.Commands.ReloadCommand.execute(Unknown Source) 25.11 17:00:10 [Server] WARN at io.github.yannici.bedwars.BedwarsCommandExecutor.onCommand(Unknown Source) 25.11 17:00:10 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) 25.11 17:00:10 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) 25.11 17:00:10 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) 25.11 17:00:10 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) 25.11 17:00:10 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) 25.11 17:00:10 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) 25.11 17:00:10 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) 25.11 17:00:10 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) 25.11 17:00:10 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 25.11 17:00:10 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266) 25.11 17:00:10 [Server] WARN at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) 25.11 17:00:10 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) 25.11 17:00:10 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) 25.11 17:00:10 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)

**Comment by Yannici** [comment]
Yes, this looks like a corrupt shop.yml. Send your shop.yml or upload it on a file-sharing website.

**Comment by blijgozertje** [comment]
https://www.mediafire.com/?nsybvbc2bhnx4p5

**Comment by Yannici** [comment]
You have a space before "drinks", so there are 5 spaces => ERROR
