### ISSUE TITLE
BedWars Save Error

### ISSUE THREAD

**Issue by RedRikudo** [Yannici/bedwars-reloaded#355]
Hi,
Your plugin is very helpful, but I have a big problem ; 
I'm able to create arena and setup them, but when I use the /bw save [Arena] command, it tell me it worked in game, but in the Console it say "Invalid Argument".
And the problem is, when I reload or stop the server, the arenas aren't saved ...

Can you help me ? 
Thanks.

**Comment by RedRikudo** [comment]
@Yannici @sebastianbinder @siOnzeeSlav @Granik24 @nostrumg Help Me Please :'(

**Comment by sebastianbinder** [comment]
@RedRikudo: Is your game called "[Arena]"? Or "Arena"? Maybe there is an error with the brackets in the name.

**Comment by nostrumg** [comment]
What's the output of /bw list?

**Comment by RedRikudo** [comment]
@nostrumg When I do /bw list after the stop restart it show anything. @sebastianbinder The name of the arena is 2x1*1, maybe it's a problem with the little star (I don't know if it mean something in English = *) I Will Try witch other name, thanks you !

**Comment by RedRikudo** [comment]
Thanks You so much, It's Now Working !
Good Bye :+1:

**Comment by sebastianbinder** [comment]
@RedRikudo, don't forget to close the issue...

**Comment by RedRikudo** [comment]
Sorry :/
