### ISSUE TITLE
Spieler werden nicht in Arena teleportiert

### ISSUE THREAD

**Issue by sebastianbinder** [Yannici/bedwars-reloaded#357]
Hi @Yannici, bräuchte dringend deine Hilfe, weiß leider nicht mehr weiter…
Die Spieler joinen eine Runde, der Countdown läuft. Theoretisch sollten die Spieler ja dann am Ende vom Countdown in die Arena geportet werden, aber irgendwie klappt das in **1.2.8** bei mir nicht mehr. Und das inzwischen überall und ständig. Ich hab leider keine Ahnung, wie dieser Fehler zustande kommt, aber vielleicht hast du ja Ideen...
```
[15:27:19 INFO]: [BedWars] Das Spiel 'Halloween' hat begonnen!
[15:27:19 INFO]: XXXX lost connection: Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer
[15:27:19 INFO]: XXXX lost connection: Internal Exception: java.io.IOException: Error while write(...): Connection reset by peer
```
**Edit 09.12.15 - 17:20 Uhr**: aber manchmal auch:
```
[17:17:41 INFO]: [BedWars] Das Spiel 'Halloween' hat begonnen!
[17:17:41 INFO]: XXXX lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe
[17:17:41 INFO]: XXXX lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe
```
**Edit 09.12.15 - 19:33 Uhr**: Interessant ist, dass die Spieler erst in die Arena (auf Gameserver) geportet werden, dann aber wieder zurück in die Lobby (auf selbigem Gameserver) und dann vom Server gekickt und somit auf den Hub (weil Fallback-Server, wenn man von Gameserver gekickt wird) von BungeeCord. Fehler tritt nur auf, wenn es mehrere (ungefähr mindestens eine Hand voll) Spieler sind.
**Edit 10.12.15 - 08:20 Uhr**: Inzwischen habe ich herausgefunden, dass der Fehler bei 1.2.7 nicht auftritt und nur bei 1.2.8 - mal testen welcher Build von 1.2.8 noch geht und ab wann der Fehler kommt…
**Edit 10.12.15 - 08:26 Uhr**: Jenkins Build [232](http://ci.yannici.de/job/BedwarsRel/232/) geht noch, aber ab [233](http://ci.yannici.de/job/BedwarsRel/233/) tritt der Fehler auf.

**Comment by sebastianbinder** [comment]
@Ybrin, kannst du mal deine Commits [8da23e4](https://github.com/Yannici/bedwars-reloaded/commit/8da23e4f79876042b3b47d542cfe88de435fd1a9), [23e38b8](https://github.com/Yannici/bedwars-reloaded/commit/23e38b836fc7e0c036853df0576770539023ed89), [4ad8fc6](https://github.com/Yannici/bedwars-reloaded/commit/4ad8fc673b9e78d2ec5d2ed9a9f45b83a5d5ab98) und [d30da23](https://github.com/Yannici/bedwars-reloaded/commit/d30da2384302d070e90c321075d4cc54108fbc32) überprüfen? Ich mag ja niemanden etwas unterstellen, aber diese Commits könnten durchaus was mit dem Fehler zu tun haben. Kann es sein, dass das Plugin denkt, dass das Spiel schon läuft und in der gleichen Zeit aber noch Spieler in die "Arena"-Welt teleportiert werden? Also somit das ``PlayerChangedWorldEvent`` im ``GameState.RUNNING`` aufgerufen wird und diese Spieler dann aus dem Spiel geworden werden? Dies würde erklären, warum der Fehler nur auftritt, wenn es mehrere Spieler sind und eigentlich auch immer nur die zuletzt teleportierten Spieler wieder aus dem Spiel fliegen.

**Comment by sebastianbinder** [comment]
@Yannici, wie groß ist denn grundsätzlich die Wahrscheinlichkeit, dass [hier in der Game.java](https://github.com/Yannici/bedwars-reloaded/blob/4ad8fc673b9e78d2ec5d2ed9a9f45b83a5d5ab98/src/io/github/yannici/bedwars/Game/Game.java#L249)
```
247   this.teleportPlayersToTeamSpawn();
248   
249   this.state = GameState.RUNNING;
```
zu schnell hintereinander ausgeführt wird, dass ``state`` schon auf ``RUNNING`` ist, bevor alle Spieler zum ``TeamSpawn`` teleportiert wurden? Ich kenne mich da in den Hintergründen von Java noch zu wenig aus. Immerhin entwickle ich erst zwei Monate oder so jetzt in Java ^^ Aber ich denke doch nicht, dass Zeile 249 darauf wartet, dass wirklich alles davor (insbesondere Zeile 247) erledigt ist, oder?

**Comment by Ybrin** [comment]
@sebastianbinder Ich werde mir das heute Nachmittag anschauen aber `IOException` klingt eher weniger nach meinen Änderungen. Ist trotzdem möglich weil ich es leider für Bungeecord nicht testen konnte. Wie gesagt ich schaue es mir heute an...

**Comment by Yannici** [comment]
`IOException` kommt eher von BungeeCord (`broken pipe`), aber kann dadurch verursacht werden, wenn zu schnell hin- und her teleportiert wird o.ä. Ich könnte mir vorstellen, dass es an den Änderungen von @Ybrin liegt. Die Theorie, die @sebastianbinder hat könnte sogar noch irgendwo stimmen. Der Teleport von Minecraft läuft nämlich asynchron. D.h. wenn man die `teleport()`-Methode des Players aufruft, dann wird nicht darauf gewartet bis der Spieler tatsächlich teleportiert wurde. Möglicherweise ist dann der Ablauf zu schnell. Wie ich das aber abfangen kann ist die Frage. Ich kann ja nicht einfach ein Sleep des Threads einbauen, das wäre ja unschön. Tricky ...

**Comment by sebastianbinder** [comment]
@Ybrin und @Yannici - danke für eure Kommentare dazu schonmal. Bei der ``IOException`` habe ich halt am Anfang erstmal natürlich an falsche Schreibrechte auf meinem Server und an alles mögliche andere gedacht, aber letztlich konnte ich alles ausschließen.
Ich nehme aber insofern mein Kommando zurück, dass es ein Problem ist, dass die beiden Methoden zu schnell hintereinander ausgeführt werden.
```
if(!game.getPlayerSettings(change.getPlayer()).isTeleporting()) {
  game.playerLeave(change.getPlayer(), false);
} else {
  game.getPlayerSettings(change.getPlayer()).setTeleporting(false);
}
```
Man würde nur gekickt werden, wenn man ``isTeleporting()`` auf ``false`` hat. Aber das bekommt jeder Spieler vor dem Teleport auf ``true`` gesetzt. Also kann es das auch schon nicht mehr sein. Ich verzweifle….
Ich zweifle auch gerade schon wieder daran, dass es ab diesem genannten Build auftritt. Weil manchmal klappt der Teleport eben und bei manchen Spielern nicht. Und das ist einfach so zufällig, dass ich immer nur Vermutungen aufstellen kann.
Ich frage mich einfach nur wie es zustande kommt, dass man von der Lobby auf dem Gameserver in die Arena geportet wird, dann wieder in die Lobby zurück und dann diese ``IOException`` auftritt. Ich bin ja auch in Kontakt mit dem Entwickler von ``AntiAura``. Dessen Plugin hatte auch ein Update und ich habe ihm auch das Szenario geschildert und er meinte er hätte jetzt einfach mal so implementiert, dass beim WorldChange alle Checks von seinem Plugin kurz deaktiviert werden, damit ich testen kann ob es an ``AntiAura`` liegt, aber seine Änderung hat nichts bewirkt und dann würden ja auch alle Spieler abgefangen und gekickt werden und nicht immer nur einzelne…
Ich freue mich, wenn ihr mir Vorschläge und Ideen liefert um was es hier gehen könnte, aber ich erwarte natürlich keines Falls, dass ihr hier groß Zeit opfert. Weil letztlich ist Bedwars-Rel OpenSource und die einzelnen Zeilen Code debuggen kann ich im Zweifel schon auch selbst……

**Comment by sebastianbinder** [comment]
Was ich definitiv inzwischen sagen kann:
Bedwars-Rel 1.2.7 funktioniert mit AntiAura
Bedwars-Rel 1.2.8 funktioniert nicht mit AntiAura
Bedwars-Rel 1.2.8 funktioniert ohne AntiAura
Jetzt ist natürlich die Frage wo man ansetzt. Grundsätzlich funktioniert ja AntiAura (siehe Bedwars-Rel 1.2.7), aber jetzt funktioniert es nicht mehr. Aber Bedwars-Rel 1.2.8 ohne AntiAura funktioniert ja auch. Also beides scheint an sich zu laufen, bloß nicht gemeinsam. Aber ich glaube der Entwickler von AntiAura hat einfach ein bisschen mehr Zeit und dem sein Plugin kostet immerhin auch etwas, sodass ich den auf jeden Fall einmal primär weiter nerve…

**Comment by Ybrin** [comment]
@sebastianbinder Ist überhaupt kein Problem, ich wollte mich sowieso wieder mal ein bisschen mit BedwarsRel auseinandersetzen, dann fixe ich halt bugs...Grundsätzlich ist es einmal super zu wissen dass das Problem wohl an der Inkompatibilität von BedwarsRel und AntiAura liegt. Ich werde mal da ansetzen und ein paar Tests durchführen. Sobald ich neue Infos habe melde ich mich...

**Comment by sebastianbinder** [comment]
@Ybrin super :)
Der Entwickler von AntiAura spamt heute auch schon ständig Updates in der Hoffnung, dass er das fixt :)
https://www.spigotmc.org/resources/antiaura-hack-blocker-1-7-1-8-compatible.1368/history

**Comment by sebastianbinder** [comment]
@Yannici @Ybrin
Es lag wohl letztlich an AntiAura, denn der Entwickler hat ein Update veröffentlicht, das die Kompatibilität wieder hergestellt hat. Trotzdem ein fettes Danke euch beiden für's fleißige Mitdenken!
