### ISSUE TITLE
Item stacking

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#36]
It can be cool turn off item stacking in game.

**Comment by Yannici** [comment]
What do you mean? Isnt that useless?

**Comment by helptiger** [comment]
you could use another pl for that

**Comment by Granik24** [comment]
If you have stack on, it's causing some bugs. On GommeHD spawners spawning no-stack items. 

@helptiger Can you send me some plugin please?

**Comment by helptiger** [comment]
http://dev.bukkit.org/bukkit-plugins/stackableitems/

**Comment by helptiger** [comment]
and this http://dev.bukkit.org/bukkit-plugins/perworldtablist/ to filter the players in tab

**Comment by helptiger** [comment]
... this one http://dev.bukkit.org/bukkit-plugins/bst-world-chat/ to separate chat from other worlds/games

**Comment by Granik24** [comment]
It can be set in Spigot.yml. 
@helptiger Thank you for that plugins!
