### ISSUE TITLE
Setup für BungeeCord

### ISSUE THREAD

**Issue by Hollo1001** [Yannici/bedwars-reloaded#361]
Hallo,
Ich habe eine Frage/Problem, wie genau nutze ich das plugin für bungeecord.
Soll ich das plugin auf BungeeCord oder auf jedem einzelnen server installieren?
Beim versuch als Bungeecord plugins istallierte sich kein Ordner.
Bitte um nochmalige bessere erklärung.
MFG Hollo1001

**Comment by Yannici** [comment]
Jeder einzelne Server. Ein Server = Ein BW Game

**Comment by Hollo1001** [comment]
Wie kann ich dann serverübergreifende Joinschilder machen?

**Comment by Yannici** [comment]
Mit TeleportSigns z.B.

**Comment by sebastianbinder** [comment]
@Hollo1001 - hast du noch weitere Fragen? Wenn deine Anliegen geklärt sind, dann schließe bitte diesen Issue. Danke :)

**Comment by sebastianbinder** [comment]
@Hollo1001 Wenn du keine Fragen mehr hast, werde ich den Issue in einer Woche schließen.
