### ISSUE TITLE
Map Reset doesn't work | Map wird nicht zurückgesetzt

### ISSUE THREAD

**Issue by elitru** [Yannici/bedwars-reloaded#366]
English:
Hello!
I love your plugin it is really nice there is only one problem: the map reset doesn't work!
Waht should I do i need this plugin for my server and the map reset is very important! Please help me!
Elias

German:
Hallo!
Ich liebe dein Plugin alles geht wunderbar nur der Map reset nicht! Was soll ich tun das Plugin ist sehr wichtig für meinen Server! Bitte hilf mir!
Elias

**Comment by sebastianbinder** [comment]
Hi @elitru - gehen wir das Ganze mal langsam an. Meistens liegt es an anderen Plugins oder irgendwelchen fehlerhaften Konfigurationen. Auch ein Absturz (Crash) deines Servers kann das Zurücksetzen verhindern.
Welche Plugins laufen denn auf deinem Server? Hast du testweise schon einmal alle anderen Plugins als BedwarsRel entfernt?

**Comment by elitru** [comment]
Ich habe 23 Plugins danke schon mal jetzt für die Hilfe Ich habe:
zChat, SG, EW, Skywars, infoplugins, worldedit, colored signs, multioverese-core, und so ein paar weiter die hier aber sicher nichts verändern!

**Comment by elitru** [comment]
wroldguard doch nicht mehr ups

**Comment by sebastianbinder** [comment]
@elitru - kannst du kurz mal dein Setup noch erklären? BungeeCord mit einzelnen Spigot Instanzen? Oder nur ein einzelner großer Spigot-Server (was die vielen Plugins erklären würde)

"und so ein paar weiter die hier aber sicher nichts verändern!" - sag bitte sowas niemals.

Hast du BedwarsRel auf deinem Server ohne die ganzen anderen Plugins schon einmal getestet?

**Comment by elitru** [comment]
ja habe ich war das gleiche
ich haben einen einzelen 
und die anderen können nix verändern sind nur für den chat
komm doch drauf dann siehst du es selber

**Comment by elitru** [comment]
ich muss mir sonst leider ein anderes plugin besorgen

**Comment by elitru** [comment]
die map resetet erst wenn ich /bw reload mache aber das ist ein minigames server ich bin nicht immer on das geht so nicht

**Comment by sebastianbinder** [comment]
@elitru steht was relevantes im Logfile?

**Comment by elitru** [comment]
ne leider nicht und auch nicht in der konsole alles geht nur der map reset nicht warum???

**Comment by sebastianbinder** [comment]
@elitru und dass ein /bw reload den Reset fixt ist sehr interessant… Einerseits weil ich das bisher nicht wusste (eigentlich ist es ja dafür da, um das Plugin neu zu initialisieren) und andererseits, da es zeigt, dass das Plugin an sich den Reset schafft und es von irgendwo anders geblockt wird :)

**Comment by elitru** [comment]
ja hab sogar ausprobiert : bin in die jeweilige map gegangen die blöcken waren da dann /bw reload
und sie sind vor mir verschwunden

**Comment by elitru** [comment]
willst du mal schnell auf den server

**Comment by sebastianbinder** [comment]
@elitru ohne deine Server-Adresse kann ich nicht draufschauen. Vielleicht schaffe ich es heute oder morgen spätestens mal. Auch wenn ich mir nicht sicher bin, ob das viel hilft, wenn ich mal auf den Server schaue. Aber wenn du auf mein Netzwerk mal schaust (bedwars.network), siehst du, dass es an sich funktioniert. Und ich habe nur BedwarsRel und ein Permission-Plugin und ein AntiHack-Plugin auf meinem Gameserver.

Aber bitte: Teste vorher mal deine Konfiguration des Servers indem du temporär alle anderen Plugins deaktivierst. Bspw. einfach kurz Server stoppen, dann im Plugin-Ordner einfach den .jar Dateien die Rechte entfernen und wenn es dann funktioniert, einzeln jedes Plugin wieder hinzufügen bis der Fehler wieder auftritt. Das ist einfach Standard-Debugging um Kompatibilitätsprobleme auszuschließen. Wenn es dann immer noch nicht geht, dann kann man versuchen die Kompatibilität zu schaffen.

**Comment by elitru** [comment]
ok danke
IP:84.200.24.200:28840

**Comment by sebastianbinder** [comment]
@elitru Schon Neuigkeiten bzgl. deiner Plugin-Tests?

**Comment by sebastianbinder** [comment]
@elitru - wenn das Thema erledigt ist, dann schließe bitte den Issue hier wieder.

**Comment by sebastianbinder** [comment]
@elitru Hat sich die Sache erledigt? Wenn nein, dann bitte ich um Rückmeldung oder schließe bitte den Issue. Andernfalls werde ich ihn in einer Woche der Ordnung halber selbst schließen.
