### ISSUE TITLE
Map resetting don't works

### ISSUE THREAD

**Issue by Poweringg** [Yannici/bedwars-reloaded#367]
When game ends, placed blocks (sandstone,glass etc) don't disappear... 

i'm runing on:
"git-Spigot-fdc1440-53fac9f" version 1.8.8

**Comment by sebastianbinder** [comment]
Hi @Poweringg, are there any plugins on your server preventing the reset? Which plugins are installed? Have you already tried BedwarsRel without ANY other plugin installed? Are you running on Bungeecord or just one Spigot server? Which version of BedwarsRel is installed?

**Comment by Poweringg** [comment]
I'm running on bungeecord, version of BedwarsRel is: 1.2.7
And here is my plugins:
![pl](https://cloud.githubusercontent.com/assets/15527318/11951189/21705e6e-a88f-11e5-8b8c-2d303f5a02e9.png)

**Comment by sebastianbinder** [comment]
> Have you already tried BedwarsRel without ANY other plugin installed?

Any answer for this one here? Because you are using a lot of other plugins…

**Comment by Granik24** [comment]
There can be problem with Residence, or with Multiverse. Try to look into that configs or disable that plugins.

**Comment by sebastianbinder** [comment]
@Poweringg, any news? If yes, then tell us and if your problem is resolved, please close the issue.

**Comment by sebastianbinder** [comment]
@Poweringg I didn't get any feedback from you. I'll close this issue in one week if you don't give us an update on this.
