### ISSUE TITLE
[BUG (?)] Multiple players joining quickly -> Invisible to each other

### ISSUE THREAD

**Issue by sebastianbinder** [Yannici/bedwars-reloaded#384]
Might be a bug or not. I am investigating but need feedback from other users if they are experiencing the same issue:
When using a party system and the party leader joins the game lobby, of course, all the other players are getting teleported into the game, too. BUT: It seems like BedwarsRel then messes up visibility of players. Some of the players can't see each other in the game lobby (even in tablist) and then they aren't visible in game as well.
Steps to reproduce (if you don't have a party system): Use /send command from Bungeecord to send a bunch of people (maybe current server) to one of your game servers.
Need feedback: Is the same happening on your servers?

**Comment by sebastianbinder** [comment]
@Granik24 ? :)

**Comment by Granik24** [comment]
@sebastianbinder Approved, same problem on our servers.

**Comment by itsfaraaz** [comment]
I am having the same problem. Just added this to my network and did a huge beta test yesterday. We found a lot of glitches and this was one of them.

**Comment by Yannici** [comment]
Is this a minecraft problem? Or bedwars? I can't imagine that any players will be set visible when joining to a game. Only spectators while game is running ...

**Comment by sebastianbinder** [comment]
@Yannici - good question. I don't really know. I'll have a closer look on it soon. Maybe it simply helps to set players visible to each other on join. This "bug" is happening and at least we need to try to fix it. If it is a Spigot problem we'll find out :)

**Comment by Yannici** [comment]
I can remember in spigot documentation there is a hint, that players should be set visible/invisible 1 tick AFTER joining to server. If you want to make pull request, remember that please ;)

**Comment by sebastianbinder** [comment]
Good to know. Thank you @Yannici :)

**Comment by sebastianbinder** [comment]
Just for documentation:
Possible Solution 1: Hide all players on join and then show all players again (tested and works).
Possible Solution 2: Preload chunks of lobby (I found this on the Internet - not sure how this should solve the problem, but it's worth a try).
Possible Solution 3: Resend player packages from server to client (seems to be the best if it works - example: https://gist.github.com/aadnk/3773860).

**Comment by Yannici** [comment]
Maybe we can just copy the code from the source you posted ;-)

**Comment by sebastianbinder** [comment]
Haha, of course that's what I am going to do this afternoon.
But those methods need the server jars and not only the spigot api. Is there anything I need to keep in mind when importing the classes? How does this work with compatibility to different minecraft server versions?

**Comment by sebastianbinder** [comment]
Okay. Possible solution 3 is not working :/ Really tried a lot with it.
Did some more research on the internet and solution number 1 really seems to be the safest. I'm gonna work with that now.

**Comment by sebastianbinder** [comment]
Hi all ( @Granik24 @itsfaraaz @Yannici ),
please have a look on my commit in branch "issue-369". This should fix the bug in issue #369 as well as the problem with players being invisible from this issue here.
Please test it for me, I just tried it locally a couple of times with 4 players joining at the same time via Bungeecord /send command. I really need your feedback on this. Please have a look at the performance as well, because there are a couple of more ``if`` now, since I also extracted some repeating code concerning players' game mode and their visibility in external methods to keep the code dry.

**Comment by Granik24** [comment]
@sebastianbinder Will try it in few hours. Thanks for that! :)

**Comment by sebastianbinder** [comment]
My personal test results in "live" environment:
It works, but it takes a bit to much time for a player being killed without having a bed being set invisible for the remaining players. Trying to improve that.
But I'm gonna wait for your test results.

**Comment by sebastianbinder** [comment]
New build: http://ci.sebastianbinder.com/job/Bedwars-Rel/5/

**Comment by sebastianbinder** [comment]
For those of you who are able to run Java 8 builds: Have a look at my latest build on jenkins (http://ci.sebastianbinder.com/job/Bedwars-Rel/10/) with nice performance fixes.

**Comment by sebastianbinder** [comment]
http://ci.sebastianbinder.com/job/Bedwars-Rel/15/ (finally it's a java 7 build, so it should work with java 7 and 8 this time)

**Comment by Granik24** [comment]
@sebastianbinder Works as well. ;)
