### ISSUE TITLE
[Critical] Player invisible?

### ISSUE THREAD

**Issue by itsfaraaz** [Yannici/bedwars-reloaded#386]
Hello Everyone,

We did some beta testing today and found a lot of glitches. One of them is that when players respawn, they are invisible as shown in this video: https://m.youtube.com/watch?v=n7OdnnF4AcI

Anyone have a fix for this?

Thanks,
Faraaz

**Comment by HobbyzockerLP** [comment]
Use the latest version of minecraft!

**Comment by itsfaraaz** [comment]
@HobbyzockerLP

I am using version 1.8.8 and running it on Java 7. Can you link me to the one your using?

Thanks,
Faraaz

**Comment by HobbyzockerLP** [comment]
I mean minecraftversion, not server version...
Use the latest version of minecraft in your launcher

**Comment by itsfaraaz** [comment]
@HobbyzockerLP

Okay, but not all users use that version of Minecraft and it would be a pain to force over hundreds of users to upgrade to 1.8.8. Is there a way I can develop a fix for this?

Thanks,
Faraaz

**Comment by HobbyzockerLP** [comment]
Nope, that is a minecraft bug! All users need to update their minecraft version! Is that a problem?!

**Comment by itsfaraaz** [comment]
@HobbyzockerLP

It isn't a problem, it's just something that will annoy users.

Thanks,
Faraaz

**Comment by AbstractSpectrum** [comment]
This can't be a minecraft version bug, it has to be the plugin because in regular minecraft, without the plugin, players re spawn fine. It must be a plugin bug.

**Comment by itsfaraaz** [comment]
@sebastianbinder @Yannici Any ideas on how this can be fixed?

**Comment by sebastianbinder** [comment]
@itsfaraaz Be patient. This project is open source and for free. There are more important things like university (and much more). I'm always trying to fix as many issues as possible, but this can take weeks or months. So feel free to take a look at the code yourself or wait a bit. You opened the issue only 15 hours ago…
I'm pretty sure I can have a look on this while fixing #384 - but actually I've never seen your "bug" before, so it might be hard for me to debug.

**Comment by itsfaraaz** [comment]
@sebastianbinder Sorry for being impatient. That's fine, I will look into it myself. Just didn't know where to start.

Thanks
Faraaz

**Comment by HobbyzockerLP** [comment]
Es ist kein Bug vom Plugin! Es ist ein bekannter minecraft Bug der seit der 1.8.3 gefixt wurde!

**Comment by sebastianbinder** [comment]
@itsfaraaz please check on the following build (http://ci.sebastianbinder.com/job/Bedwars-Rel/15/) and tell me if you can still reproduce this issue while running this build.
