### ISSUE TITLE
[enhancement] multiple hub

### ISSUE THREAD

**Issue by Toshka17** [Yannici/bedwars-reloaded#387]
Could you add support for a randomly several hubs sending?

**Comment by sebastianbinder** [comment]
I think, this is not something a bedwars plugin needs to do. Use or write a Bungeecord plugin that listens to ServerConnect events and then balances the amount of players.

**Comment by Toshka17** [comment]
Just randomly, not balancing, it will be very helpful. This plugin is very popular and servers typically use a lot of lobby for the game.

**Comment by sebastianbinder** [comment]
But if it's urgent to use different lobbies, how do your players randomly getting connected to one of your lobby servers when they are for example joining your server from the minecraft server list or from another minigame? You should simply add a plugin to your server hooking into the ServerConnectEvent.
A bedwars plugin is responsible for offering a bedwars game. But it isn't responsible for spreading your players all over your server network. That's two different things…
But nevertheless: @Yannici what to you think about this?

**Comment by Yannici** [comment]
I'm with you @sebastianbinder . Nevermind @Toshka17 , but I think a bedwars plugin shouldn't be responsible for spread playes, like @sebastianbinder said.
