### ISSUE TITLE
Warteraum Chat ist in der Lobby lesbar + 'Das Spiel xxx hat begonnen ist ebenfalls für jeden lesbar

### ISSUE THREAD

**Issue by cubenex** [Yannici/bedwars-reloaded#388]
Problem steht im Titel. Meinen Warteraum Chat der BW Lobby kann jeder mitlesen + jeder in der Lobby kriegt eine Benachrichtigung, dass das Spiel xxx losgegangen ist. Würde gerne beides komplett voneinander trennen.
http://pastebin.com/rxYtZ6Hn

**Comment by brainscript** [comment]
Es wäre vielleicht mal nützlich sich mal mit Markdown auseinander zu setzten, was ja sogar oben rechts im Textbereich "vorgeschlagen" wird. Dort kann man nachlesen dass man Code bzw. Configs, etc. speziell formatieren kann bzw. soll. Dann würde man bei deiner Config vielleicht auch irgendetwas erkennen ...
```
So sieht dass dann ORDENTLICHer aus.
```
https://guides.github.com/features/mastering-markdown/

**Comment by sebastianbinder** [comment]
Hey @cubenex, könntest du netterweise deine Config mittels Markdown als Code markieren? Wie das geht findest du unter https://guides.github.com/features/mastering-markdown/#examples
Dann wäre das alles besser lesbar und dann schaue ich mir mal an, ob ich etwas finde. Danke dir!

**Comment by sebastianbinder** [comment]
@brainscript war wohl schneller :/

**Comment by cubenex** [comment]
http://pastebin.com/rxYtZ6Hn

**Comment by cubenex** [comment]
Passt es so?

**Comment by cubenex** [comment]
So das Problem besteht weiterhin, allerdings habe ich noch eine weitere Frage. Welches Kommando wird beim Rechtsklick auf ein Schild ausgegeben? Brauche den Befehl, damit mein Party and Friends Plugin ordentlich funktioniert.
- /bw join xxx ist es schon einmal nicht, weil dort nichts passiert.
Kann man auch irgendwie die Teleportschilder ausstellen so, dass nur noch die Live Anzeige steht und alles per CommandSigns geregelt wird?

**Comment by Yannici** [comment]
@cubenex Kein Kommando wird da ausgeführt. Das Plugin bearbeitet den Klick auf ein Schild selbst und fügt den Spieler dem Spiel hinzu. Du kannst aber das Bedwars-Event "BedwarsPlayerJoinEvent" oder "BedwarsPlayerJoinedEvent".

**Comment by cubenex** [comment]
Hmm schade, dass dies nicht einfacher ist, aber hab immer noch das Problem, dass die Chats der Lobby + die Nachricht "Das Spiel wurde gestartet" alle sehen aufm gesamten Server

**Comment by Yannici** [comment]
Da gibt es einen Config-Eintrag `global-messages: true`. Den mal auf `false` stellen, falls noch nicht getan.

**Comment by cubenex** [comment]
Schon seit gestern erledigt mehrere Restarts trotzdem noch die Nachrichten.

**Comment by Yannici** [comment]
Dann scheint da wohl ein anderes Plugin am Werk zu sein, das das Chatverhalten beeinflusst.

**Comment by cubenex** [comment]
http://abload.de/img/unbenannt3fuk1.png

**Comment by Yannici** [comment]
Denkst du ich kenn jedes einzelne Plugin? Ich denke nicht, dass es meine Aufgabe ist hie rjetzt das Plugin rauszufinden, dafür ist immerhin der Administrator verantwortlich. In deinem Fall bist das wohl du.

**Comment by cubenex** [comment]
Alles klar. Naja gibt ja auch noch alternativen trotzdem danke für den ganzen Support :)

**Comment by Yannici** [comment]
Kein Problem.

**Comment by cubenex** [comment]
Ich werds jetzt einmal auf einem Vanilla Server ohne andere Plugins ausprobieren. Wenn es dort klappt dann muss ich mal meine Plugins durchschauen. Falls nicht liegt es definitiv am Plugin

**Comment by cubenex** [comment]
Auf dem Spigot Server gleiches Problem nur anders. Chat wird nicht angezeigt es lag am Chatmanager, allerdings wird selbst auf dem leeren Server die Teamfarbe für alle Spieler angezeigt

**Comment by sebastianbinder** [comment]
@cubenex Danke für deine Unterstützung. Dann wäre ja Problem 1 schon einmal aus der Welt.
Wie meinst du das mit "auf dem leeren Server die Teamfarbe für alle Spieler angezeigt"?

**Comment by cubenex** [comment]
Das Problem mit der Tabliste ist kein wirkliches Problem, da man dies mit SimplePerWorldTablist regeln kann, aber nun ist das Problem mit dem Chat wieder da.
http://abload.de/img/unbenanntoauvd.png

**Comment by cubenex** [comment]
Sobald ich ingame bin sieht man keinen Chat mehr. Das Problem befindet sich nur in der Warte-Lobby.

**Comment by cubenex** [comment]
Kleine Info zum Screenshot. Der linke Spieler ist nicht im Bedwars Game und steht einfach nur rum. Der Rechte wartet in der Lobby und hat "Hallo" geschrieben, aber der Linke konnte es mitlesen.

**Comment by sebastianbinder** [comment]
@cubenex Wie kommt ein Spieler überhaupt in die Wartelobby, wenn das Spiel läuft? Das ist glaube ich nicht der Sinn des Erfinders. Ich hätte das so verstanden, dass es eine Wartelobby pro Spiel gibt…

**Comment by cubenex** [comment]
Es kommt keiner in die Wartelobby ohne zu joinen. Es gibt ebenfalls nur eine Wartelobby pro Spiel. Ich habe lediglich einen kleinen Test Server aufgesetzt und mal schnell ein Test Spiel erstellt.

**Comment by sebastianbinder** [comment]
Hast du ``seperate-game-chat: true``?

**Comment by cubenex** [comment]
Ja

**Comment by sebastianbinder** [comment]
Mir scheint es gerade so, als wäre das so herum gar nicht implementiert. Theoretisch dürftest du als Spieler in einer Runde nicht lesen können, was die anderen Leute auf deinem Server schreiben. Dass das auch andersherum so funktionieren sollte, macht natürlich Sinn und jetzt so auf dem ersten Blick kann ich das in [PlayerListener, Zeile 497](https://github.com/Yannici/bedwars-reloaded/blob/master/src/io/github/yannici/bedwars/Listener/PlayerListener.java#L497) ff. nicht erkennen (sorry @Yannici, falls ich hier daneben liege). Aber ich muss mir das alles mal in Ruhe ansehen. So spontan auf dem iPad in der Uni ist das nicht so einfach :)
Aber bitte gedulde dich da ein wenig und rechne nicht mit einem Fix in den nächsten Tagen.

**Comment by cubenex** [comment]
Ist egal hab ne lösung. Ist zwar ziemlich viel gebastelt, aber irgendwie klappt es doch. Simpleperworldtablist in Kombination mit SimpleWorldChat hat die Lösung gebracht ^^

**Comment by sebastianbinder** [comment]
Okay. Aber egal ist es natürlich nicht :) Ein Bug, der gefunden wurde, muss behoben werden :) Also ich schau mir das mal bei Gelegenheit wie gesagt genauer an.

**Comment by cubenex** [comment]
Danke :+1:

**Comment by Yannici** [comment]
Habs eigentlich auf den ersten Blick gesehen

**Comment by sebastianbinder** [comment]
@cubenex Hast du dir den Fix einmal angesehen und getestet? Bitte um Feedback.

**Comment by sebastianbinder** [comment]
@cubenex Sprichst du noch mit uns? :)

**Comment by cubenex** [comment]
Ahh sry habe keine E-mail Benachrichtigungen erhalten ! Ich werde es direkt testen. :)

**Comment by sebastianbinder** [comment]
@cubenex Achso :) Mach das - wir freuen uns auf dein Feedback!

**Comment by sebastianbinder** [comment]
@cubenex - Wie sieht es aus?

**Comment by cubenex** [comment]
Der Chat funktioniert nun, aber die Welt resettet sich ab und zu nicht.
Plugins sind Essentials PermissionsEx und worldedit.
Am 02.02.2016 10:06 vorm. schrieb "Sebastian Binder" <
notifications@github.com>:

**Comment by sebastianbinder** [comment]
@cubenex Okay. Dann ist dieser Issue hier ja gelöst. Das mit dem Reset der Welt wurde schon in vielen Issues erläutert, wieso er ab und zu fehlschlägt. Das ist einfach zu zufällig um hier etwas ändern zu können.
