### ISSUE TITLE
Holograms Doppelt

### ISSUE THREAD

**Issue by cubenex** [Yannici/bedwars-reloaded#391]
Guten Tag, 
ich melde mich mal wieder hier :-D.
Noch eine Frage hätte ich. Wie kann man den Bug beheben, dass ab und an die Holograms doppelt erscheinen und so unlesbar werden?

**Comment by sebastianbinder** [comment]
Im Sinne von #337 oder anders? Ohne Beispiele ist sowas immer echt schwer :/

**Comment by Yannici** [comment]
ProtocolLib installieren.

**Comment by cubenex** [comment]
Protocollib hat es gelöst. :)

**Comment by cubenex** [comment]
So. ProtocolLip hat es doch nicht gebracht. Sie sind einfach ab und an unlesbar, da sie doppelt sind ich kann gar nicht mehr Angaben nennen. Ich könnte höchstens meine Config posten. http://pastebin.com/cP2MxEDz

**Comment by cubenex** [comment]
http://imgur.com/7uSTQG7

**Comment by sebastianbinder** [comment]
Ist das Thema noch aktuell @cubenex ?
