### ISSUE TITLE
Bungeecord fehler

### ISSUE THREAD

**Issue by luctv** [Yannici/bedwars-reloaded#394]
Hallo ich glaube ich habe einen Bug gefunden, und zwar wenn man Ingame /hub macht also damit man in die Lobby kommt. Verlällst zwar der Spieler den Server aber das plugin zeigt ihn immer noch Ingame und das geht so lang bis am ende nur er am server ist und nur mehr fehler meldungen kommen

Ich bitte um Lösung

LG

**Comment by HobbyzockerLP** [comment]
/bw leave! Im neuesten build kann man auch hub machen...

**Comment by luctv** [comment]
Okay diese kann man auch schon downloaden oder?

**Comment by HobbyzockerLP** [comment]
Nein ist illegal.
http://ci.yannici.de/job/BedwarsRel/250/

**Comment by luctv** [comment]
habe jzt die neueste build installiert aber /hub geht immer noch nicht also es ist immer noch der gleiche  fehler

**Comment by Yannici** [comment]
Sollte normalerweise funktionieren. Wenn du die Welt dabei wechselst? Oder ist das diesselbe Welt auf der man /hub macht und BW spielt?

**Comment by luctv** [comment]
Ich habe für jede map einen eigenen Server mit /hub komme ich wieder auf dem lobby server

**Comment by HobbyzockerLP** [comment]
Bei Bungeecord ist das anders, glaub da muss man in der config fallbacksever bestimmen.

**Comment by luctv** [comment]
Okay aber wenn ich /hub ingame mach wird man zwar zur lobby teleportiert aber das bedwars plugin erkennt ihn noch immer

**Comment by sebastianbinder** [comment]
@luctv 
Wenn du allein Spigot (ohne Bungeecord) nutzt, dann musst du /bw leave machen oder einen Command-Alias für /hub erstellen, der dann /bw leave ausführt
Wenn du Spigot mit Bungeecord nutzt, dann kannst du /hub problemlos ausführen, sofern du ein Plugin hast, das diesen Command auf deinem Bungeecord implementiert.
BedwarsRel alleine unterstützt den Command /hub nicht.
