### ISSUE TITLE
Don`t click event for Member on sign

### ISSUE THREAD

**Issue by ZockerWelt** [Yannici/bedwars-reloaded#396]
Normal players can not access the signs to enter the bedwars game

**Comment by Granik24** [comment]
@ZockerWelt That's not fault of BedWars plugin, but there will be something bad with your plugin configuration.

**Comment by ZockerWelt** [comment]
at which config it could be?

**Comment by Granik24** [comment]
Post here your plugin list.

**Comment by ZockerWelt** [comment]
what for ?

**Comment by Granik24** [comment]
Because I can't help you without that.

**Comment by sebastianbinder** [comment]
@ZockerWelt please disable spawn protection in your server config.

**Comment by ZockerWelt** [comment]
I try it times out

**Comment by sebastianbinder** [comment]
@ZockerWelt okay. Auf Englisch kommen wir hier nicht weiter. Was willst du uns sagen? Und bei Gelegenheit mal: https://github.com/Yannici/bedwars-reloaded/wiki/HowTo:-Write-an-Issue

**Comment by ZockerWelt** [comment]
alos ich habe das problem das spieler die kein op haben nicht die bedwars schilder zum joinen nutzen können

**Comment by sebastianbinder** [comment]
@ZockerWelt - okay. Dann garantiere ich dir, dass es, wenn du in deiner Server-Config die spawn-protection auf 0 setzt, klappt.

**Comment by ZockerWelt** [comment]
okay. Danke für die hilfe :) ich probiere es gleich mal

**Comment by ZockerWelt** [comment]
danke es lag echt an der spawn-protection!! DDANKE :)
