### ISSUE TITLE
Duration for Potions

### ISSUE THREAD

**Issue by HobbyzockerLP** [Yannici/bedwars-reloaded#400]
I would like to modify the duration of Potions :)
Is there are already a possibility to modify the durability of potions?

**Comment by HobbyzockerLP** [comment]
Sorry I mean duration^^

**Comment by sebastianbinder** [comment]
Has been added in https://github.com/Yannici/bedwars-reloaded/issues/447#issuecomment-191627048 - will be published with release 1.3.0
