### ISSUE TITLE
ASKE

### ISSUE THREAD

**Issue by superstoffer12** [Yannici/bedwars-reloaded#404]
how do i can make bye the shop a enchanted golden apple plase can you help me whit this

**Comment by HobbyzockerLP** [comment]
I can't understand you.

**Comment by superstoffer12** [comment]
how I was in the shop to make an enchantment golden apple I then make a so Niewe shop item and then I want that a enchantmet golden appel or notch aplle

**Comment by sebastianbinder** [comment]
Have you tried the following? @superstoffer12 
```yml
reward:
  item: 322
  meta: 1
```

**Comment by superstoffer12** [comment]
Thx mate for helping whit this problem THX

**Comment by superstoffer12** [comment]
how do i can make de blocks size of the spawn 
small

**Comment by sebastianbinder** [comment]
@superstoffer12 what do you mean? :) I don't really get it...

**Comment by superstoffer12** [comment]
nofing
