### ISSUE TITLE
[Enhancement] Drop NMS code

### ISSUE THREAD

**Issue by sgdc3** [Yannici/bedwars-reloaded#411]

**Comment by Yannici** [comment]
I don't understand that ^^

**Comment by sgdc3** [comment]
@Yannici What do you mean?

**Comment by Yannici** [comment]
What does "Drop NMS code" mean?

**Comment by sgdc3** [comment]
A pure API usage is more easy to manage and upgrade.

**Comment by sebastianbinder** [comment]
I understand it :)

@Yannici NMS code ist der Code, der ohne API verwendet wird, also wenn man direkt die Server-Source einbindet. Also immer wenn man bspw. den CraftPlayer hat.

**Comment by Yannici** [comment]
Ich weiß was der NMS Code ist, aber den kannst du ja wohl nicht wegnehmen?

Ok, I understand now, but this is not possible. There are features where NMS Code is needed, because Spigot/Bukkit doesn't provide enough API-Features to handle that.

**Comment by sebastianbinder** [comment]
Haha, okay :)

**Comment by sgdc3** [comment]
@Yannici What do you need?

**Comment by Yannici** [comment]
@sgdc3 Everything what's in https://github.com/Yannici/bedwars-reloaded/tree/master/src/io/github/yannici/bedwars/Com/v1_8_R3 for example.

Titles, Custom-Single-Particles, Custom Pathfinders etc. aren't possible without NMS.

**Comment by sgdc3** [comment]
One simple solution: ProtocolLib ;)

**Comment by Yannici** [comment]
I'm not a fan of using external APIs ;) So, sorry.

**Comment by sgdc3** [comment]
Titles: https://github.com/IntellectualSites/PlotSquared/tree/74a967b535767cb079be6c4a6cae1e6ab0802b4a/src/main/java/com/plotsquared/bukkit/titles

**Comment by sgdc3** [comment]
Remember alto that you shouldn't host spigot jars on a public repo.

**Comment by sgdc3** [comment]
@Yannici What's the issue with particles? playEffect should work fine :/

**Comment by Yannici** [comment]
PlotSquared using Reflection to get the NMS packages. I could use that too, but it would be a lot of extra code. Also I need to change it everytime the nms will change the member or method names, too :P So there is no advantage.

The spigot libs are just for builds, I can remove them if I want to ...

`playEffect` is displaying more than just 1 particle and plays a fully effect animation. With NMS you can create single particles.

**Comment by Yannici** [comment]
Seriously, I made a lot of thoughts how I will implement these things ;) And that was the best solution for me.

**Comment by sgdc3** [comment]
> Also I need to change it everytime the nms will change the member or method names, too :P So there is no advantage.

https://github.com/ConnorLinfoot/TitleAPI/blob/master/src/main/java/com/connorlinfoot/titleapi/TitleAPI.java It doesn't look too complicated ;)

**Comment by Yannici** [comment]
Not for Titles, but for eg. Villager shops it's much more complicated. And if method/member names changes, I need to refactor this every time :P I think there is no need to drop the NMS code.
