### ISSUE TITLE
Join Sign auf anderen Server

### ISSUE THREAD

**Issue by HerrBockwurst** [Yannici/bedwars-reloaded#412]
Hi,

ich habe einen BungeeCord Server und folgendes Setup

Main Lobby (Eigenständiger Server)
BW-1 (Eigenständiger BW Server, game bw-01)
BW-2 (Eigenständiger BW Server, game bw-02)
....

Wenn ich die Games in BW-1 etc erstelle, kann ich in der Main Lobby kein Join Sign erstellen (No games found). Habe ich beim Setup was falsch gemacht?

EDIT hab es jetzt mit einen Dritten Plugin hinbekommen. Nur noch eine Frage: Wie kann ich in die Modt einen Zeilenumbruch erzwingen? Für das TeleportSign brauch ich mehrere Zeilen.

Hier mal meine Konfiguration
http://pastebin.com/QiiAy7aM

**Comment by sebastianbinder** [comment]
In deiner Config nutzt du doch bereits zwei Zeilen?…

**Comment by HerrBockwurst** [comment]
Hab gerade noch etwas rumgetestet, es scheint wirklich am TeleportSigns Plugin zu liegen, welches die 2 Zeilen nicht richtig erkennt.

**Comment by Yannici** [comment]
Um zwei Zeilen in TeleportSigns nutzen zu können musst du in TeleportSigns 2x MOTD konfigurieren (untereinander). Dann werden auch 2 Zeilen angezeigt.

**Comment by HerrBockwurst** [comment]
Ich weiß nicht genau, ob es an BW oder TS oder an mir liegt :D Meine Config ist wie gehabt:

```
    lobby: |
      Line 1
      Line 2
```

und meine TeleportSings Config sieht so aus:

```
#message when a player tries to connect to offline server
offline-message: '&cServer ist offline!'
show-offline-message: true
#time between pings/signupdate in seconds
interval: 5
#signs updates per tick
sign-updates: 20
#connect timeout
timeout: 1500
#cooldown for being teleported (milliseconds)
cooldown: 2000
#debugmode
debug: false
#specify your servers here
servers:
  bw-01:
    address: '127.0.0.1:25610'
    displayname: '&5[BedWars]'


#placeholders:
#%numpl% = online players
#%maxpl% = max players
#%motd% = motd
#%displayname% = displayname
#%isonline% whether the server is online or offline
layouts:
  #you can change the default layout but don't delete it!
  default:
    teleport: true
    layout:
      - '%displayname%'
      - '%motd%'
      - '%motd%'
      - '%motd%'
    online: '&aOnline'
    offline: '&cOffline'
    offline-int: '-'
  info:
    teleport: false
    layout:
      - '%displayname%'
      - '&c%numpl%&a/&c%maxpl%'
      - '&6&fInfosign'
      - ''
    online: 'Online'
    offline: 'Offline'
    offline-int: '-'
  game:
    teleport: true
    layout:
      - '&n&fPvP-Match'
      - '%motd%'
      - '&1%numpl%&a/&1%maxpl%'
      - '%isonline%'
    online: '&a+++'
    offline: '&c---'
    offline-int: '-'
```

Trotzdem wird mir nur Line 1 angezeigt.
![unbenannt](https://cloud.githubusercontent.com/assets/7777672/12840983/0b517af6-cbe8-11e5-93d1-92788b69a79a.png)

**Comment by Yannici** [comment]
Man kann nicht mehr als 2 MOTDs anzeigen lassen in TeleportSigns.

**Comment by HerrBockwurst** [comment]
Habs mal mit folgenden Probiert:

```
    layout:
      - '%displayname%'
      - '%motd%'
      - '%motd%'
      - 'test'
```

Aber leider zeigt er die 2te Zeile trotzdem nicht an :(

![unbenannt](https://cloud.githubusercontent.com/assets/7777672/12841072/0a2cba5e-cbe9-11e5-9124-4dae2dbef046.png)

**Comment by sebastianbinder** [comment]
@HerrBockwurst füge bitte mal deinen Server in deinem Minecraft-Client in der Serverliste (Multiplayer) hinzu. Solltest du hier beide Zeilen der MOTD dann sehen, dann funktioniert Bedwars-Rel korrekt und du musst dich an den Support von TeleportSigns wenden. Jegliche weitere Konversation hier hätte nämlich keinen Sinn, wenn es nicht an Bedwars-Rel liegt.
Solltest du in der Serverliste auch nur eine Zeile sehen, dann können wir uns weiter darum kümmern.
Bitte gib uns diesbezüglich Feedback. Danke dir!

**Comment by HerrBockwurst** [comment]
Das hatte ich auch schon ausprobiert. Und im Serverbrowser bei Minecraft wird es auch korrekt angezeigt, sowohl mit der einen als auch der anderen Schreibweise. Drum dachte ich mir auch das es mehr an TeleportSigns liegen muss. Manchmal haben ja hier andere ihre Server so eingerichtet das es klappt, drum hab ich mir Erfahren oder andere Config-Möglichkeiten Erhofft wo es funktioniert. Danke Trotzdem.

**Comment by Yannici** [comment]
`lobby: "Line 1\nLine 2"` so sollte es in TeleportSigns eigentlich funktionieren, wenn du nur 2x `%motd%` in der TeleportSigns-Config verwendest.

**Comment by sebastianbinder** [comment]
@HerrBockwurst - wenn sich die Sache erledigt hat, bitte Issue schließen oder weiter Rückmeldung geben, wenn wir noch etwas für dich tun können. Danke.

**Comment by HerrBockwurst** [comment]
```
  default:
    teleport: true
    layout:
      - '%displayname%'
      - '%motd%'
      - '%motd%'
      - ''
    online: 'Online'
    offline: 'Offline'
    offline-int: '-'
```

und 

`lobby: "Line 1\nLine 2"`

zeigt mir leider nur die Erste Zeile. Zumal das BW Plugin die config umschreibt zu

```
    lobby: |-
      Line 1
      Line 2
```

Habt ihr noch Ideen?

**Comment by sebastianbinder** [comment]
@HerrBockwurst - Wie schon gesagt, ist diese Schreibweise valides YML, was ja auch vom Server unterstützt wird. Wieso Teleport Signs damit nicht klarkommt, können wir dir leider nicht sagen.
