### ISSUE TITLE
Kits

### ISSUE THREAD

**Issue by Koby99** [Yannici/bedwars-reloaded#413]
Wie währe es mit kits in der warte lobby welches man mit points oder wie man es nennen möchte die man bei kills und Bett abbauen bekommt?

**Comment by sebastianbinder** [comment]
Meiner persönlichen Meinung nach, würde dies zu weit von "Bedwars" abweichen. Es gibt einen bereits einen Feature Request bzgl. mehrerer "Rewards" im Shop (https://github.com/Yannici/bedwars-reloaded/issues/321) - damit könnte man eine Art "Kit" dann im Spiel realisieren, aber bereits mit einem Kit aus der Lobby zu starten, fände ich nicht mehr toll…
Wie siehst du das @Yannici ?

**Comment by cubenex** [comment]
@sebastianbinder 
Sorry, dass ich mich einmische, aber genau das selbe hatte ich mir auch gewünscht :D 
Kits wären schon ne feine Sache. :)

**Comment by Yannici** [comment]
Wäre auch eher dafür, dass man dann eher #321 umsetzt. Damit kann man dann seine Kits selbst erstellen. Mit einem neuen Punktesystem Kits kaufen zu können weicht von einem reinen BW-Plugin ab. Da muss ein Server dann schon eher selbst eingreifen und umprogrammieren ;-)
