### ISSUE TITLE
Pomoc!

### ISSUE THREAD

**Issue by RebelVole** [Yannici/bedwars-reloaded#42]
Hello, it just does not work your sourc do not know what it may be that we would like if you could plug me the data into version and send it to email: kuchar111@seznam.cz
This plugin should have version 1.7-1.8 thank you

**Comment by RebelVole** [comment]
and please to java

**Comment by Yannici** [comment]
Sorry, I don't understand anything.

**Comment by Yannici** [comment]
This is not an issue. Please send pn at spigotmc.org

**Comment by RebelVole** [comment]
I apologize for my spigot PM goes some way to send when you send a first
http://www.spigotmc.org/members/theusgamer.27783/

**Comment by RebelVole** [comment]
Could you please make par plugin specially adapted to BungeeCord that it contained motd and much more what your ma plugin "bedwars-reloaded"

**Comment by RebelVole** [comment]
And could you please give me your skype or facebook through it would not easily solved

**Comment by RebelVole** [comment]
Can you please send the email to the plugin
