### ISSUE TITLE
Kill players in spectator mode

### ISSUE THREAD

**Issue by Yannici** [Yannici/bedwars-reloaded#423]
Das hier kommt von einer Nachricht von Spigot @sebastianbinder, vielleicht mal anschauen:

Hi. I have your plugin and It's absolutely good, but We found several bugs that Are becoming annoying to The players.

We had to use one of The older versions of The plugin because The last one had a bug with The spectator mode. When a player died or joined The server as a spectator he could kill The players that were still playing.

Please fix this as soon as possible!!!
Thank you!!

**Comment by sebastianbinder** [comment]
@Yannici - kannst du bitte zurückfragen, welche exakte Version benutzt wird? Dann lässt sich der Fehler nochmal eingrenzen. Ich denke mal, dass der Spectator nicht im Gamemode 3 landet, wie ja auch @Block-Build immer mal wieder das Problem hat. Wobei ich leider einfach überhaupt nicht nachvollziehen kann, wieso das auftritt. Bei mir auf dem Server habe ich nämlich das Problem absolut noch nie beobachten können :/
Daher wären wirklich die genauen Versionen interessant, welche gehen und welche nicht gehen. Je mehr Infos ich habe, umso besser kann ich den Fehler suchen, finden und beheben.

**Comment by sebastianbinder** [comment]
@Yannici kam hier nochmal was?
