### ISSUE TITLE
Players are getting kicked randomly on bungeecord.

### ISSUE THREAD

**Issue by Phreag** [Yannici/bedwars-reloaded#427]
Hey, i got a weird problem:
My Network has a Minigames Server with Bedwars-Rel running on it.
Sometimes players are getting kicked back to hub with the message 
"The Server you were previously on went down..."
This only affects a few players in the game, all others can still play. There are no lags or other causes for this except Bedwars-Rel, because it only happens if you are in a bedwars game.

**Comment by sebastianbinder** [comment]
You are using AAC for Anti-Cheat, aren't you?

**Comment by Phreag** [comment]
Yes i do

**Comment by sebastianbinder** [comment]
Then try to set `forcefield.magic.send_damaged_animation` to `false` in you AAC config. This should solve the issue.

**Comment by sebastianbinder** [comment]
@Phreag - did this solve your issues?
If no: Give us feedback!
If yes: Please close this issue :)

**Comment by Phreag** [comment]
Seems to work for now, i had no report of this issue after changing aac config.
