### ISSUE TITLE
Some placed block cannot be destroyed.

### ISSUE THREAD

**Issue by xyblues** [Yannici/bedwars-reloaded#428]
I apologize for my poor English.
Why is this so?
It is bug?
Please Tell Me,thank

**Comment by sebastianbinder** [comment]
@xyblues - please have a look on https://github.com/Yannici/bedwars-reloaded/wiki/HowTo:-Write-an-Issue - then we might be able to help you.

**Comment by Granik24** [comment]
@xyblues Actualy, this happening if your server crash or if you stop your server as "hard" way (kill the process). This happened for me too, but now I restroing map backup at every server start, so the problem is gone. ;)
