### ISSUE TITLE
Unsichtbare Spieler

### ISSUE THREAD

**Issue by luctv** [Yannici/bedwars-reloaded#430]
Hey, ich habe das Plugin auf meinem Netzwrk installiert, auf bungeecord.

Aber wenn spieler joinen sind sie unsichtbar, aber nur immer ein spieler,
woran kann das liegen?

LG

**Comment by sebastianbinder** [comment]
Hi @luctv 
Wir benötigen mehr Informationen von dir. Bitte schau dir doch mal https://github.com/Yannici/bedwars-reloaded/wiki/HowTo:-Write-an-Issue an.

**Comment by luctv** [comment]
Hey,

Ich benutze die Plugin Version 1.2.8 Build 250.
Meine Plugins: Bedwars Reloaded, Bungeeperms, Tablist und Multiverse Core 2.5
Mein Server läuft auf einem einzelnen Spigot Server der mit Bungeecord verbunden ist!

In der Konsole gibt es keine Fehlermeldungen.

**Comment by sebastianbinder** [comment]
Hey @luctv 
Probier mal bitte [diese Version](http://ci.sebastianbinder.com/job/Bedwars-Rel/25/artifact/dist/BedwarsRel-1.2.8-50b714bc0c8b3c5b382261dffce46ce74c538c33.jar) hier aus - diese wird bald als finale Version 1.2.8 veröffentlicht und enthält viele Fixes. Das sollte das Problem beheben.

**Comment by luctv** [comment]
Hey, danke es hat alles Funktioniert!

Aber es gibt noch ein Problem,
Das Plugin funktioniert mit keinem Nick Plugin

**Comment by sebastianbinder** [comment]
hi @luctv 
bzgl. der Kompatibilität zu Nick-Plugins gibt es bereits andere Issues. Es ist im Hinterkopf, aber derzeit nicht von höchster Priorität.
