### ISSUE TITLE
Lobby Teleport

### ISSUE THREAD

**Issue by Boy132** [Yannici/bedwars-reloaded#433]
Version: 1.2.8 - REAL UPDATE
Andere Plugins: worldguard, worldedit
config.yml: normal, nichts bearbeitet
Errors etc. in der Konsole: keine

Problem:
Wenn ich auf ein Join Schild klicke werde ich nicht zur Lobby teleportiert.

**Comment by Yannici** [comment]
Schau in den server.properties, ob da spawn-protection auf 0 ist ;-)

**Comment by Boy132** [comment]
Ja, spawn-protection ist auf 0

**Comment by Yannici** [comment]
Dann müssen wir das wohl beheben. Wird sobald es geht behoben ;-)

**Comment by sebastianbinder** [comment]
Hi @Boy132 
Ich habe hier mal auf die Schnelle versucht das Problem zu fixen. Kannst du bitte mal http://ci.sebastianbinder.com/job/Bedwars-Rel/34/artifact/dist/BedwarsRel-1.2.8-82417b96ede8897b1039d6109b2cc7a2c505819c.jar testen, ob der Fehler damit bei dir behoben ist? Danke!

**Comment by Boy132** [comment]
Geht soweit, aber wenn ich jetzt das Spiel verlasse werde ich auch zur Lobby teleportiert^^

**Comment by sebastianbinder** [comment]
@Boy132
Ist das so falsch? Wo wolltest du hinteleportiert werden?

**Comment by Boy132** [comment]
Zu meiner letzten Position; eben da wo ich auf der Join Schild geklickt habe. (So wie es vorher auch war^^)

**Comment by Yannici** [comment]
@sebastianbinder Er meint wohl eher die BW-Lobby, in die er teleportiert wird. Das darf ja nicht sein wenn man das Spiel verlässt ;-)

**Comment by Boy132** [comment]
Jaa, genau das meine ich :+1:

**Comment by sebastianbinder** [comment]
@Boy132 @Yannici 
Jetzt hab auch ich es kapiert - Danke xD
Bitte testen: http://ci.sebastianbinder.com/job/Bedwars-Rel/36/artifact/dist/BedwarsRel-1.2.8-dff074d5e117805e29c34ad55c278dfad57ad547.jar

**Comment by Boy132** [comment]
Okay, jetzt gehts alles :D Danke

**Comment by sebastianbinder** [comment]
@Boy132
Super :) Kein Problem :)
