### ISSUE TITLE
Erfolge

### ISSUE THREAD

**Issue by Koby99** [Yannici/bedwars-reloaded#436]
Ich wollte fragen was ich von einem erfolgesystem haltet wo man halt Erfolge wie "First blood" oder "Builder" (Bestimmte Anzahl an Blöcken gebaut).
Oder findet ihr das dann schon ehr was für falsch hier? Hoffe auf Rückmeldung.
MFG Koby

**Comment by sebastianbinder** [comment]
Duplicate #73
