### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by elitru** [Yannici/bedwars-reloaded#437]
Ich habe einen Nicht so kleinen MiniGames-Server und benutze auch BedwarsRel. Ich habe BungeeCord und alles funktioniert super und jetzt meine Frage ich bräuchte eine SkyWars Plugin fast gleich wie auf gommehd.net und anderen Servern. Ich liebe eure Plugins könntet ihr mir eine coden so bis spätestens 3 Wochen ich bezahle auch bitte alle funktionen wie Map-Reset VIP-Premission motd für BungeeCord einstellbar eigentlich wie bie BedWarsRel Danke
Elias

**Comment by sebastianbinder** [comment]
Hi @elitru,
das hier ist kein Issue, also kein Problem des Bedwars-Plugins - somit ist diese Anfrage hier fehl am Platz. Außerdem wirst du niemanden finden, der dir innerhalb von 3 Wochen ein solches Plugin erstellen kann und ganz ehrlich, ich glaube auch nicht, dass du den Stundenlohn eines Entwicklers, der für dich ein solches Plugin schreibt, mal so locker bezahlen kannst. Schreibe deine Anfrage in das SpigotMC-Forum oder kontaktiere dort einzelne Entwickler direkt - da wirst du bestimmt jemanden finden. Aber mehr gehe ich auf deine Anfrage hier nicht ein.
