### ISSUE TITLE
@ and spectator chat don't completes a sentence

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#44]
What im writing: Já díky. ;)
What chat writing: Já díky. ;

**Comment by Yannici** [comment]
Fixed in https://github.com/Yannici/bedwars-reloaded/commit/33a4eaed9025160fe05d18663ff88d6fd625d852

**Comment by Granik24** [comment]
Same problem with start of sentence. 
Hello = ello

**Comment by Yannici** [comment]
Okay, I'll fix that
