### ISSUE TITLE
Teleport with compass (player tracker)

### ISSUE THREAD

**Issue by Yannici** [Yannici/bedwars-reloaded#442]
Von einer PN aus dev.bukkit.org:

Man kann als Admin des Servers im Game mit Compass sich überall hin beamen...sollte nicht sein. Bei den normalen Playern ist das nicht so.

Ich sehe es auch so, dass man das nicht können sollte, selbst als Admin nicht. Das Tool sollte ja nur zur Anzeige verwendet werden können (Vorteil von Admins gegenüber Spielern sollte so gering wie möglich gehalten werden).

**Comment by sebastianbinder** [comment]
@Yannici Das ist ein Kompatibilitätsproblem mit WorldEdit. Da kann ja der Kompass eben für dieses "Beamen" verwendet werden. Der Spieler muss einfach auf diesem Server WorldEdit entfernen oder sich die Permission von WorldEdit nehmen (da gibt es eine speziell für den Kompass) oder den Kompass aus dem Shop nehmen...

**Comment by Yannici** [comment]
Danke ;-)
