### ISSUE TITLE
Spectators have GM1

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#45]
Spectators can break and place blocks. You can set GM2 to spectators maybe. .)

BTW. 150 players on our server! AND IT WORKS! :333

**Comment by Yannici** [comment]
Nice :) Fix will coming soon.

**Comment by Yannici** [comment]
Fixed in https://github.com/Yannici/bedwars-reloaded/commit/33a4eaed9025160fe05d18663ff88d6fd625d852
