### ISSUE TITLE
Different Hologram plugin support?

### ISSUE THREAD

**Issue by deltaflyer4747** [Yannici/bedwars-reloaded#451]
Hello, since Holographic Displays was not updated for almost a year, will it be possible to support different hologram plugin that is already updated for 1.9 - https://www.spigotmc.org/resources/holograms.4924/ ?

**Comment by sgdc3** [comment]
I think that HD will be updated very soon

**Comment by sebastianbinder** [comment]
filoghost said he's gonna update his plugin soon.
![image](https://cloud.githubusercontent.com/assets/5227469/13452849/f69cb1ac-e04b-11e5-9623-ed3c8437e506.png)
