### ISSUE TITLE
Fehler im Welt Reset

### ISSUE THREAD

**Issue by Icecrown-wow** [Yannici/bedwars-reloaded#457]
Beim Welt Reset werden Gras und Wasser die schon davor auf der Map waren nicht wiederhergestellt. sondern Gras bleibt weg und Beim Wasser kommt dort, wo der Sandstein war eine Strömung.

**Comment by sebastianbinder** [comment]
Hi @Icecrown-wow 
Oft funken andere Plugins wie bspw. WorldGuard dazwischen. Besteht das Problem noch? Wenn ja, dann bräuchten wir noch mehr Informationen. Schau am besten auch mal auf https://github.com/Yannici/bedwars-reloaded/wiki/HowTo:-Write-an-Issue
