### ISSUE TITLE
Its broken with 1.9

### ISSUE THREAD

**Issue by partydragen** [Yannici/bedwars-reloaded#458]
Can this plugin be updated to 1.9 its not working for 1.9 :/
When its starting in 10 sec its just spamming the Starting in 10 sec message
And scoreboards show the teams self we have not started
and i think potions is broken for 1.9

Running a network (Using bungeecord)
Running latest Spigot on every servers without bedwars them use 1.8 only since its not work with spigot 1.9

Bedwars:
Bedwars config: Bungeecord mode
Latest spigot
Offline mode
Spigot setting: Bungeecord: True

**Comment by Granik24** [comment]
Are you blind? o.O
https://github.com/Yannici/bedwars-reloaded/issues/447

**Comment by partydragen** [comment]
No but i see people saying its working for 1.9 without potions and things but for me its not starting

And i can't see the todo list to fix its to work

**Comment by sebastianbinder** [comment]
I think everything is said.
