### ISSUE TITLE
1.9 Bug with GameLobbyCountdown 

### ISSUE THREAD

**Issue by partydragen** [Yannici/bedwars-reloaded#459]
Game not starting auto its just spamming starting in 10 sec but when i start manually its working
Error with GameLobbyCountdown http://pastebin.com/SAGSYxW9 for 1.9

And i see this error when i try to use the shop when i started manually http://pastebin.com/iYhyhHhe buts its maybe already knowed and fixed idk

Bedwars Config: Bungeecord mode
Bedwars Config: Using Database
Server Prop: Offline mode
Spigot: Bungeecord: true
Running Spigot 1.9

**Comment by sebastianbinder** [comment]
Already has been fixed in https://github.com/Yannici/bedwars-reloaded/commit/1fd5f10fb9fea8ff6a9e760f6896ba294b37a556
