### ISSUE TITLE
Custom Resources?

### ISSUE THREAD

**Issue by Bangari** [Yannici/bedwars-reloaded#460]
I've been trying to add custom resources to the game to make it look more like money walls but I couldn't, I tried adding Diamonds and Emeralds btw. Please help me

**Comment by Granik24** [comment]
How the way you tried to add it? :P

**Comment by Bangari** [comment]
https://gyazo.com/4d44a3bf24719783583ae43424798470

**Comment by Bangari** [comment]
https://gyazo.com/4d44a3bf24719783583ae43424798470

**Comment by Bangari** [comment]
@Granik24 https://gyazo.com/4d44a3bf24719783583ae43424798470

**Comment by Granik24** [comment]
You can't change names of default ones. You just can change item and name of item. :P

**Comment by Bangari** [comment]
So you can't add new items?

**Comment by Granik24** [comment]
For sure, you can! Just keep the name "bronze, iron and gold" in config.

**Comment by Bangari** [comment]
Yeah but I added Emerald and nothing came out of the generators

**Comment by Granik24** [comment]
I think because of bronze missing.

**Comment by Bangari** [comment]
Okay, thanks. I'll try it out right now. Thanks for your help so far!

**Comment by Granik24** [comment]
No problem, just hit me up with progress! :)

**Comment by Bangari** [comment]
Oh my god, you're my saviour! I don't know how to thank you man!
Thank you so much, you've made my day! But one quick question though (if it isn't difficult, can you have a mob instead of a bed and have the players kill the mob to make a team lose?) THANKS

**Comment by Granik24** [comment]
No, you can have only block. Entity is not supported I think.
No problem! :)

**Comment by Bangari** [comment]
And can you make your villager shop not move? I'm sorry I'm bothering you with these questions btw.

**Comment by Granik24** [comment]
Any villager doesn't move as default for me o.O
No problem :D

**Comment by Bangari** [comment]
Huh, that's odd. But are you supposed to spawn the villager after the game starts or before?

**Comment by Granik24** [comment]
Everytime, we spawned it before game. Never had any problem with villagers move.

**Comment by Bangari** [comment]
Well, that's odd.

**Comment by Bangari** [comment]
Have you ever heard of the game money walls before? I'm trying to make it like that

**Comment by Granik24** [comment]
Never, sorry

**Comment by Bangari** [comment]
Ah. It's a really cool game, you should check it out sometime :)

**Comment by Granik24** [comment]
Ooookay then, I will. :)

**Comment by HobbyzockerLP** [comment]
I already played this game, but this game has nothing to do with bedwars.

**Comment by Bangari** [comment]
It kinda looks like it though.

**Comment by HobbyzockerLP** [comment]
Bedwars is different. Money Wall is an other game. This plugin hasn't the features of money walls.

**Comment by Bangari** [comment]
Yeah, but I'm coding it so it looks exactly like it. I couldn't find any money walls plugins either so I thought this would do.

**Comment by HobbyzockerLP** [comment]
This is not a good idea, because it isn't your plugin!

**Comment by Bangari** [comment]
But I'm not releasing it or anything, It's for private use.

**Comment by HobbyzockerLP** [comment]
I won't discuss about this.

**Comment by Bangari** [comment]
Okay then.

**Comment by Granik24** [comment]
This plugin is opensource and anyone can do anything with this, if it's under license. So..

**Comment by Bangari** [comment]
And quick final question, how do you customize the shop items? I can't seem to do it.

**Comment by Granik24** [comment]
Just edit shop.yml

**Comment by Bangari** [comment]
It didn't work, I changed everything and added a few stuff and the shop came out as blank with only the options of changing the old shop and the shift option

**Comment by Granik24** [comment]
So you have bad config. Check out all settings or vaild yaml. ;)

**Comment by Bangari** [comment]
Thanks!

**Comment by Granik24** [comment]
No problem :P
