### ISSUE TITLE
Bug of blocks

### ISSUE THREAD

**Issue by elpedriyo** [Yannici/bedwars-reloaded#465]
Sometimes players can't break the blocks they have placed.

**Comment by sebastianbinder** [comment]
Hey @elpedriyo - please have a look on https://github.com/Yannici/bedwars-reloaded/wiki/HowTo:-Write-an-Issue and provide more details.

**Comment by elpedriyo** [comment]
### General Information
- **Version of BedwarsRel**: ``1.2.7``
- **Server Setup**: ``Bungee``
- **Installed plugins**: ``http://prntscr.com/ahnltf``
- **shop.yml**: http://pastebin.com/jRStxtxY
- **config.yml**:  http://pastebin.com/x91cVZjh
- **Errors on the Console**: no errors

### Problem

The one I said above, maybe could be happenning because of lagg tps issues?

**Comment by sebastianbinder** [comment]
@elpedriyo 
At first, please update BedwarsRel to version 1.2.8 - that's the latest and only version being supported at the moment.

**Comment by Granik24** [comment]
@elpedriyo Also, what version of AAC you have?

**Comment by elpedriyo** [comment]
@sebastianbinder even using the new bedwars rel version, I think the bug will continue hapenning, because I do not see any change of bug resolve to that in the changelog version updates.
@Granik24 about that I do not know what version I am using, but I think that could be the problem, because before using AAC I was not having that bug I think, so probably could be that.
But although it is an AAC problem I think the dev of that plugin won't give me support for a bug on bedwars rel plugin

**Comment by Granik24** [comment]
@elpedriyo I'm not supported of BW, so I can help you. I had this problem before too. Try to update your AAC to latest version and then reset config to default. Try if this will work. ;)

**Comment by sebastianbinder** [comment]
@elpedriyo Update to 1.2.8 AND remove all plugins from your server except the needed dependencies. If if it is still not working, we'll have a look on it. If it is working, another plugin is causing the issue, then we cannot help you.

**Comment by elpedriyo** [comment]
@sebastianbinder If I find out that the issue is caused because of another plugin what should I do? I mean, I can not go and tell the author of another plugin that yours is not working fine :/

**Comment by sebastianbinder** [comment]
@elpedriyo 
BedwarsRel doesn't modify any block breaking of player placed blocks at all. Only blocks that belong to the map are protected. We cannot guarantee compatibility with all those other plugins out there, we are just trying to make everything as "standard" as possible. So checking which block has been there before and which one has been placed by a player is a very "standard" way so it should be compatible with other plugins.
So please update to latest BedwarsRel and check if BedwarsRel really is responsible for the issue you are talking about.

**Comment by elpedriyo** [comment]
It seems to be a problem with AAC I will make more testing to be sure why is happening this

**Comment by sebastianbinder** [comment]
@elpedriyo Any updates on this? Can the issue be closed?

**Comment by Aeri-un** [comment]
Please help i can't place blocks i am playing in 1.8.8 and  I can use 1.3.6, 1.3.5 and 1.3.4 pls help me. I have not saying that there is a problem in BedwarsRel but I don't know how to solve this problem. Maybe there is a problem with my acc or something else I don't know but pls do help me.

**Comment by yeppiidev** [comment]
same, i've also been facing this issue, this issue needs to be reopened.

**Comment by iamceph** [comment]
This plugin is dead, deal with it xd
