### ISSUE TITLE
Custom scoreboard

### ISSUE THREAD

**Issue by LiMixLP** [Yannici/bedwars-reloaded#470]
Please add custom scoreboard. For example Hearts instead of ticks.

**Comment by sebastianbinder** [comment]
Hey @LiMixLP 
What exactly do you mean by that? Can you provide us any better examples?

**Comment by LiMixLP** [comment]
@sebastianbinder For example, HryoŽivot had BedWars scoreboard like that had hearts in front of team name.

**Comment by sebastianbinder** [comment]
HryoŽivot is using BedwarsRel, so the feature you are talking about is either already implemented or we need to ask @Granik24 if he can help you. I'm sorry, but personally I still don't really get what you are talking about.

**Comment by Granik24** [comment]
You can close this issue, because we're using just special character in config. :)

**Comment by LiMixLP** [comment]
@Granik24 už som to urobil, ďakujem :)

**Comment by Granik24** [comment]
@LiMixLP Close this issue ;)

**Comment by LiMixLP** [comment]
@Granik24 už ho zatváram :)
