### ISSUE TITLE
I have a translation to dutch

### ISSUE THREAD

**Issue by jensie1996** [Yannici/bedwars-reloaded#471]
Hello i made for the locale map a dutch version for your plugin and tested it, it works.
I hope you inplement it into your plugin.

Im from Belgium so my English is not so good.

website (dropbox): https://www.dropbox.com/s/x6x6aeq82o9q9gt/nl.zip?dl=0

**Comment by sebastianbinder** [comment]
@jensie1996 Thank you very much <3
I'm gonna add this one in the next release.

**Comment by jensie1996** [comment]
if there are some faults in the translation you can send me a message if someone is telling there are some faults in it
