### ISSUE TITLE
Frage und Bug gefunden [BungeecordBug]

### ISSUE THREAD

**Issue by ThetimeGames** [Yannici/bedwars-reloaded#472]
Hey also erstmal spitze Plugin :) aber ich habe eine Frage: undzwar wie oder wo schreibe ich den Maperbauer hin damit er im Title angezeigt wird?

Jetzt zum Bug. Ich lasse das ganze auf Bungeecord laufen, wenn das Game zuende ist startet der Server neu jedoch wir bei meinem Bungeecord netzwerk einfach ein weiterer server Gestartet und der alte nicht gestoppt somit laufen auf einem Port 2 Server und einen muss ich immer Stoppen. Vorallem wenn der Server dann mal Publik ist was tu ich dann wenn BW 70-80 mal am Tag gespielt wird dann sind da 70-80 server auf dem selben port...

Wäre cool wenn Ihr das fixt

und eine weitere Frage noch... XD

warum kann man alleine mit dem "Start Game" Item die Runde starten. Ich meine das hat keinen Sinn ich bin ja noch alleine. Naja ansonsten schöne Grüße und haltet das PL auf dem Laufenden :)

**Comment by sebastianbinder** [comment]
Hi @ThetimeGames!
> wie oder wo schreibe ich den Maperbauer hin damit er im Title angezeigt wird?

https://github.com/Yannici/bedwars-reloaded/wiki/Commands#bw-setbuilder-game-name

> Jetzt zum Bug. Ich lasse das ganze auf Bungeecord laufen, wenn das Game zuende ist startet der Server neu jedoch wir bei meinem Bungeecord netzwerk einfach ein weiterer server Gestartet und der alte nicht gestoppt somit laufen auf einem Port 2 Server und einen muss ich immer Stoppen. Vorallem wenn der Server dann mal Publik ist was tu ich dann wenn BW 70-80 mal am Tag gespielt wird dann sind da 70-80 server auf dem selben port…

Das ist definitiv kein Bug des Plugins - da solltest du dich wohl eher mal in die Thematik von Startskripten und Screen/Tmux, etc. einlesen oder deine Plugin-Config richtig anpassen.

> warum kann man alleine mit dem "Start Game" Item die Runde starten. Ich meine das hat keinen Sinn ich bin ja noch alleine.

Das ist durchaus für Admins ein sinnvolles Feature um das Plugin zu testen :)

Viele Grüße!

**Comment by ThetimeGames** [comment]
Danke erstmal für deine schnelle antwort das mit der Mauer habe ich auch kurz nach dem schreiben des Tickets gefunden :)

Ich werde da mit dem Start script nicht so schlau...xD was soll ich den in welcher Confiq umstellen?

Und stimmt zum Testen ist es gut aber ich würde das halt gerne VIP Usern geben

**Comment by sebastianbinder** [comment]
> Ich werde da mit dem Start script nicht so schlau...xD was soll ich den in welcher Confiq umstellen?

Basis-Kenntnisse in Administration müssen definitiv vorhanden sein, wenn du einen Server betreiben willst. Im Zweifel hilft dir da wohl nur einlesen. In der ``config.yml`` kannst du einstellen, was der Server nach einer Bedwars-Runde machen soll. Ob Neustart oder nicht, usw.

> aber ich würde das halt gerne VIP Usern geben

Kannst du doch. Mit der Permission ``bw.setup`` oder mit OP kannst du das Spiel jederzeit starten, mit ``bw.vip.forcestart``nur wenn die Countdown-Rule erfüllt ist.

**Comment by ThetimeGames** [comment]
Ah herzlichen Dank ich habe inzwischen alles gefunden :) was brauche ,mancham hilft es doppelt raufzuschauen :) und mein restart script war schuld da war nen bug drinne :)
