### ISSUE TITLE
Vorschlag für ein Update

### ISSUE THREAD

**Issue by ThetimeGames** [Yannici/bedwars-reloaded#473]
Hey also mir ist ebend mal so aufgefallen das der Command zum Leaven ja /bw leave ist wie wäre es wenn man aliase hinzufügt? Da bei mir alles über Bungeecord läuft würde der Command /leave voll reichen und ich würde Ihn auch toller finden 

Viele Grüße TheTimeGames

**Comment by sebastianbinder** [comment]
Hey. ``/bw leave`` macht für Spigot durchaus Sinn und reicht vollkommen aus. ``/leave`` des Bungeecords kannst du selbst mittels Bungeecord-Plugin einfügen.
