### ISSUE TITLE
Bungecoord

### ISSUE THREAD

**Issue by JayJay150902** [Yannici/bedwars-reloaded#475]
Könntest du mir sagen was auf das Schild muss wenn ich mit Bungeecord arbeite? 

Bitte schnell...
Danke schonmal

**Comment by sebastianbinder** [comment]
@JayJay150902 Die Schilder sind nur für reine Spigot-Server. Für BungeeCord-Installationen kannst du die Schilder nicht verwende.

**Comment by JayJay150902** [comment]
Doch, hab nen Weg gefunden! So nen Plugin, hab leider keinen Link, zeigt die Modt des Server so kann man ein Schild damit machen, außerdem joint man so auf die Server.

**Comment by sebastianbinder** [comment]
Ja klar - über andere Plugins geht das natürlich.

**Comment by jkoan** [comment]
Nice, danach hatte ich gerade gesucht 👍
