### ISSUE TITLE
Kann man das Plugin mit Iconomy Verbinden

### ISSUE THREAD

**Issue by NajBoy** [Yannici/bedwars-reloaded#480]
Hallo ich hätte da mal eine frage nämlich kann man Bedwars Rel mit dem Plugin IConomy verbinden also wenn man eine Runde gewinnt bekommt man dann z.B. 3.50€. L.G.NajBoy

**Comment by sebastianbinder** [comment]
Du kannst in der ``config.yml`` Reward-Commands einstellen: https://github.com/Yannici/bedwars-reloaded/blob/master/config.yml#L667
Problem damit gelöst?
