### ISSUE TITLE
BunggeCord 

### ISSUE THREAD

**Issue by superminerlol** [Yannici/bedwars-reloaded#485]
Ich möchte gerne BedWarsRel mit BungeeCord benutzen und und weiß auch, dass ich dafür TeleportSigns brauche, doch ich weiß nicht,wie ich diese einrichten soll und der plugin ist mit meinem Bunggecord aus irgendeinem Grunde nicht kompatibel. Kann man mir helben?

PS: Ich benutze die 1.8.8 version.

**Comment by sebastianbinder** [comment]
@superminerlol 
Es ist lediglich von Nöten, dass das TeleportSign dich auf deinen Bedwars Server verbindet und du in der config.yml von BedwarsRel den Bungeecord-Modus aktivierst.

**Comment by superminerlol** [comment]
Und wie kann ich einstellen: in welche Map ?
Am 12.04.2016 15:44 schrieb "Sebastian Binder" <notifications@github.com>:

**Comment by sebastianbinder** [comment]
Auf einem Bungeecord-Server hast du immer nur eine Map pro Server.

**Comment by superminerlol** [comment]
Und woher weiß er welche Map?
Am 12.04.2016 16:19 schrieb "Sebastian Binder" <notifications@github.com>:

**Comment by sebastianbinder** [comment]
Wer ist "er"?

**Comment by superminerlol** [comment]
Ich meinte damit den Server, aber ich habe jetzt alles hinbekommen. Nur bei
der Start.sh zum neustarten weiß ich nicht was ich da schreiben soll und wo
sie liegen soll.

**Comment by sebastianbinder** [comment]
Ich denke, du solltest dir zu allererst grundlegende Administrations- sowie BungeeCord- und Spigot-Kenntnisse zulegen, bevor du hier weitermachst. Denn offensichtlich ist dein Wissen hier noch recht defizitär. Das wäre in meinen Augen der beste Weg.
