### ISSUE TITLE
Mitte geht nicht

### ISSUE THREAD

**Issue by dieBertigs** [Yannici/bedwars-reloaded#486]
vielen Dank für dieses wundervolle, wirklich GEILE Plugin. Ich habe aber ein Problem. Mein Spigot Server läuft auf der 1.8.8 und wenn man nicht OP ist dann kann man bis 2 Blöcke bis vor der Mitte nix bauen und auf der MItte auch nicht. Ich bitte um Antwort

**Comment by superminerlol** [comment]
Du musst in den Servereinstellungen den Spawnschutz auf 0 stellen.
