### ISSUE TITLE
Kein Hunger?

### ISSUE THREAD

**Issue by ThetimeGames** [Yannici/bedwars-reloaded#487]
Hey man bekommt in bedwars keinen hunger frage ist nur wo das problem liegt? Nutze Bungeecord

**Comment by sebastianbinder** [comment]
Hi. Wir bräuchten an dieser Stelle mehr Details von dir. Also schau doch bitte mal auf https://github.com/Yannici/bedwars-reloaded/wiki/HowTo:-Write-an-Issue und lass uns so viel wie möglich über dein Setup wissen.
