### ISSUE TITLE
a bug?!

### ISSUE THREAD

**Issue by icehenrik** [Yannici/bedwars-reloaded#488]
Hi!
when i restart my game crash the server and in the console its come upp: Startup script './start.sh' does not exist! Stopping server. so its that a bug or somthing?

**Comment by sebastianbinder** [comment]
Obviously your start.sh does not exist. What's the problem here?

**Comment by icehenrik** [comment]
yes when i start a game, and when its over its saying start.sh does not exist! and then it crash the server. So what are the problem, so i can fix it?

**Comment by sebastianbinder** [comment]
Create your start.sh or configure BedwarsRel for not restarting the server.

**Comment by icehenrik** [comment]
ok in know that, but am not god at this so where can i do this in the config?

**Comment by sebastianbinder** [comment]
The config with its options is properly explained in the file in the code section.

**Comment by icehenrik** [comment]
i can`t find it in the config so can i be another place or something?
