### ISSUE TITLE
Game doesn't start instead it spams 5

### ISSUE THREAD

**Issue by RedCoder4** [Yannici/bedwars-reloaded#491]
When trying to start the game all it does in spam 5,5,5,5 etc. this is really annoying as I have run this before and since the 1.9 update it's not working. I own a server with over 350 players on average and having to keep it down is killing the server.

**Comment by sebastianbinder** [comment]
Hi. There is still no 1.9 version of BedwarsRel available. The Release Candidate is ready, it just needs to be published by @Yannici
At the moment, the only possibility for you is building the 1.3.0 branch yourself and using the plugin as a dev version at your own risk.
