### ISSUE TITLE
1.9 Shop

### ISSUE THREAD

**Issue by Timmitechniker** [Yannici/bedwars-reloaded#492]
Der BedWars Shop in der Version 1.9 funktioniert nicht. Ich hoffe dass dieser Bug bald gefixt wird.

LG HighwayLP

**Comment by sebastianbinder** [comment]
@Timmitechniker Bis dato wurde keine Version von BedwarsRel für die 1.9 veröffentlich. Warte auf das Update. Solltest du einen Dev-Build verwenden, dann wäre interessant, was genau nicht funktioniert.
