### ISSUE TITLE
Not playing 1.9 sounds (wrong sound names?) And 1.9 potions in shop.

### ISSUE THREAD

**Issue by Sollembum78** [Yannici/bedwars-reloaded#497]
On destroying bed or some other activities there is no sound and console shows:
No enam constant org.bukkit.sound.ENDERDRAGON_GROW
I think you should use something like ENTITY_ENDERDRAGON_GROWL and other sounds from this list:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html

Also, how do I add potions to shop now? Old potion ids doesn't work.

**Comment by sebastianbinder** [comment]
About the sound: Yes, we know about that, but we can only offer one default config :) And since it is only a default config, you are free to use the right sound :)

About the potions: Use latest spigot, then potion meta will work again.
