### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by icehenrik** [Yannici/bedwars-reloaded#499]
21.04 19:33:28 [Server] INFO ... 15 more
21.04 19:33:28 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[d-spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 19:33:28 [Server] INFO at io.github.yannici.bedwars.BedwarsCommandExecutor.onCommand(Unknown Source) ~[?:?]
21.04 19:33:28 [Server] INFO at io.github.yannici.bedwars.Commands.ListGamesCommand.execute(Unknown Source) ~[?:?]
21.04 19:33:28 [Server] INFO at io.github.yannici.bedwars.Main._l(Unknown Source) ~[?:?]
21.04 19:33:28 [Server] INFO Caused by: java.lang.NullPointerException
21.04 19:33:28 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
21.04 19:33:28 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [d-spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 19:33:28 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [d-spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 19:33:28 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [d-spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 19:33:28 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [d-spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 19:33:28 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [d-spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 19:33:28 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
21.04 19:33:28 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
21.04 19:33:28 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [d-spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 19:33:28 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [d-spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 19:33:28 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [d-spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 19:33:28 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [d-spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 19:33:28 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [d-spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 19:33:28 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[d-spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 19:33:28 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[d-spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 19:33:28 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[d-spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
21.04 19:33:28 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'bw' in plugin BedwarsRel v1.2.8

this was the problem afte a game was ended and i was not able to use the bedwars plugin after that so what are the proble?

**Comment by sebastianbinder** [comment]
Hi. We need some more details from you. Please have a look on https://github.com/Yannici/bedwars-reloaded/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.

**Comment by icehenrik** [comment]
Plugin info: is the last update on the plugin.
Spigot version: 1.8.9
config file: http://pastebin.com/6fkwzXnx
i have not do anything in the shop 
installed plugins: essentials, Perworldplus, ViaVersion, EmptyWorldGenerator, WorldEdit, WorldGuard, Multiverse-Core, 
problem see the first i send

**Comment by Yannici** [comment]
Nope you have 1.2.8. Please update to 1.3.0 to check if your problem then has fixed.

**Comment by icehenrik** [comment]
ok i have update to 1.3.0 and i see its no bug longer but i am saying if its a problem

**Comment by icehenrik** [comment]
one question, and that is: how do i change the language on the shop? its a command or do i need to change it manualt?

**Comment by Yannici** [comment]
Manual. Just edit the shop.yml
