### ISSUE TITLE
[Idea] Diamond blocks & items

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#5]
Hi, i have little idea. Can you add to your plugin Diamond Spawners? It can be cool! :+1: 
No, seriously, it can be good, if you can add to shop Diamond sword, Diamond chestplate and others.. I think, it could play a lot better.

**Comment by Yannici** [comment]
You mean a fourth ressource "diamonds"?

**Comment by Granik24** [comment]
Yea. It could be good :)

**Comment by Yannici** [comment]
You can configure the shop by yourself. So, you can add an trade eg. 5 Gold for 1 Diamond. And for that diamond you can buy some other stuff. That's an idea without adding a ressource spawner.

**Comment by Granik24** [comment]
I know that, but I think it can be good have something different in this plugin

**Comment by Granik24** [comment]
Leave a comment
