### ISSUE TITLE
Signs

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#50]
Hi, can you please add arena names to signs?
http://gyazo.com/f2aa5a97e18f224a11b035934a50e640 - BedWars_1 replace to name of arena. Thanks. 
Also, you can set Spectators to GM 3 (for 1.8)

**Comment by Granik24** [comment]
And maybe, this is little buggy
In gama with 0 players? Sorry, no.
http://gyazo.com/2c2bea26445fba0923c5cb50541e18b1

**Comment by Granik24** [comment]
I think, it's still buggy. Signs get lags and after that not reloading data.

**Comment by Yannici** [comment]
I can't reproduce the sign bugs. Arena name will be added soon.

**Comment by Yannici** [comment]
Added and fixed with commit https://github.com/Yannici/bedwars-reloaded/commit/6933d79a12c02203999c07d242eee15360b7a116
