### ISSUE TITLE
BedWars Glitch

### ISSUE THREAD

**Issue by Orangeric88** [Yannici/bedwars-reloaded#500]
Hi, This is an extremly well made and thought out plugin, but since the 1.9 update/patch I noticed two glitches. The first one has to do the scoreboard for the teams. When you break a teams bed, the scoreboard doesn't get updated, and it shows that the team still has their bed. The second bug is how when you break the bed, there is no sound. I haven't changed any configure files at all. Before in the 1.8 version their wasn't those bugs, but ever since of 1.9, I noticed them happening. Is their a new configure file that should know of, or is this straight out a glitch? Please patch this. This is an extremly fun minigame.

~. Orangeric88

**Comment by sebastianbinder** [comment]
Check your log file, then you should see the error being responsible for that. For simply updating the plugin to the current version, no changes are needed. But for upgrading your server to 1.9 you need to change the bed destroy sound to a 1.9 known sound.
