### ISSUE TITLE
Using points for economy / vault

### ISSUE THREAD

**Issue by matzepeople** [Yannici/bedwars-reloaded#501]
Hi,
i setup the plugin including mysql. Everything works fine so far.
Can I use the points for an economy plugin ? I tried to install vault and the MySQL Economy Bridge Plugin. But nothing happens so far.
It is not an real issue, more then an idea....
Rgds
matzepeople

**Comment by Yannici** [comment]
In config.yml you can add reward commands which will get executed when points gets distributed.

**Comment by matzepeople** [comment]
Danke für die schnelle Antwort - hab gesehen ihr sprecht auch Deutsch. Könnt Ihr mir bitte ein Beispiel für so einen Reward geben ? In der config steht player-win:         - /example {player} 200
Wie gebe ich das ein, dass der Spieler, der gewonnen hat eben 200 coins bekommt ?
Danke schon mal im Voraus - ihr macht einen Wahnsinns Job !

**Comment by sebastianbinder** [comment]
I have no idea about such foreign plugins. We already gave you an example - as you have already seen in the config. But I'm sure that it's not too hard to find out if there was a command adding 200 coins to a player's account for your economy plugin. Just search for it... http://bfy.tw/5Q8o
