### ISSUE TITLE
Gamemode 0 , when a player comes out of an arena

### ISSUE THREAD

**Issue by Toshka17** [Yannici/bedwars-reloaded#502]
When players die, they become observers in gamemode-3 and when they come out of the arena, they are again in the gamemode-0. At the moment they received gamemode-0 but still do not manage to go to a different server, they can hit the player and knock him. A lot of players are complaining about this bug. Please fix it. Let the players not to get gamemode-0 when they exit the arena.

**Comment by sebastianbinder** [comment]
Hi. We need some more details from you. Please have a look on https://github.com/Yannici/bedwars-reloaded/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.

**Comment by sebastianbinder** [comment]
@Toshka17 any news?
