### ISSUE TITLE
[Bug] - BedWars

### ISSUE THREAD

**Issue by Orangeric88** [Yannici/bedwars-reloaded#512]
Hello,
This is an extremely fun and well coded mini game though I have noticed some bugs with the new 1.9 update. I noticed that the shields aren't really blocking the arrow shots like they do in vanilla Minecraft. Also since the 1.9 update, I noticed that the bows aren't taking knock back. If you are hit with a punch bow, you don't get knocked back. I don't know if this is from BedWars or overall Bukkit/Spigot themselves.

**Comment by sebastianbinder** [comment]
Hi. The things you are talking about aren't caused by BedwarsRel.
