### ISSUE TITLE
[Bug #2] - Bedwars slow to respond

### ISSUE THREAD

**Issue by Orangeric88** [Yannici/bedwars-reloaded#515]
Sorry for interruption you guys again,
I have noticed yet another glitch, the one I said yesterday was indeed not from Bedwars,"[Thanks for clearing that up.] Ok so the bug is when you try to reload or end the server, it would just be stuck at this message: 

[20:49:51 INFO]: [TitleManager] No update was found.
[20:49:56 INFO]: Stopping the server
[20:49:56 INFO]: [BedwarsRel] Disabling BedwarsRel v1.3.0

The message would be there for about 2 min then the server would end up crashing, since their is no response. I have checked and it doesn't have to do with my server at all. (I run the server with 4GB of ram)  Before, when I only had three bedwars game, this would go relatively fast, but now since I have 6 games, its been slow shutting/restarting the server. When you start the server, it goes fast, but when you restart/stop the server, like I said before, it is very slow.

**Comment by Orangeric88** [comment]
Sorry for submitting two bugs in a row, I understand if this is a hassle.

**Comment by sebastianbinder** [comment]
Hi. We need some more details from you. Please have a look on https://github.com/Yannici/bedwars-reloaded/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.
