### ISSUE TITLE
Trade Style Shop

### ISSUE THREAD

**Issue by MageTech** [Yannici/bedwars-reloaded#539]
> [`I`](_url_)

 was thinking it would look a lot better if there was a trade style shop. This is basically the only thing that wants me to go to the other bed wars plugin: http://dev.bukkit.org/bukkit-plugins/bedwars/
But I prefer some parts of this plugin like the fact that I can change what the the spawn block and stuff. Would it be too difficult to add this trade like system to the shop, like in the above alternate bed wars plugin or like in the eggwars plugin?
I think it would be a lot better and if it was implemented it would definitely tip my choice into this plugin.
Thanks

**Comment by sebastianbinder** [comment]
Your players can choose which shop style they wanna use. We offer both :)

Go to the Villager and make a right click to start trading
![bildschirmfoto 2016-05-14 um 12 20 15](https://cloud.githubusercontent.com/assets/5227469/15267883/66ebf010-19ce-11e6-8894-10b0468e0d64.png)

Click on the Slime Ball to use the other shop.
![bildschirmfoto 2016-05-14 um 12 20 21](https://cloud.githubusercontent.com/assets/5227469/15267885/6996f350-19ce-11e6-9560-70706088745a.png)

Select a Category.
![bildschirmfoto 2016-05-14 um 12 20 29](https://cloud.githubusercontent.com/assets/5227469/15267886/6caadbc4-19ce-11e6-9a6a-1dcd76c35d6d.png)

Start trading :)
![bildschirmfoto 2016-05-14 um 12 20 38](https://cloud.githubusercontent.com/assets/5227469/15267887/6e9ab9fe-19ce-11e6-92ac-fc23fdf859e0.png)
