### ISSUE TITLE
 Can the shop reward support command ?

### ISSUE THREAD

**Issue by qiuDar** [Yannici/bedwars-reloaded#542]
Can I add the command to shop reward?

**Comment by Yannici** [comment]
What?

**Comment by qiuDar** [comment]
I'm sorry my English is poor.
I mean, the reward can use the command in the shop?
example
shop:
  armor:
    item: DIAMOND_CHESTPLATE
    name: "Armour"
    order: 10
    permission: bw.base
    lore:
    - "Protect yourself with armor! Click here."
    offers:
    - price:
      - type: CLAY_BRICK
      reward:
      - give %player% 1 1
      - give %player% 2 1

**Comment by Robotia** [comment]
Basically:
Can you use commands in the rewards section of the configuration file?

**Comment by Yannici** [comment]
No! But this isn't really what the shop should support ...
