### ISSUE TITLE
spigot 1.8.8 Suport

### ISSUE THREAD

**Issue by LeRamboMc** [Yannici/bedwars-reloaded#551]
hello I post this message because the plugin has some problems.
when I play a part of the inventory bugs ( we only change inventory on the shops ) and suddenly when I made ​​it puts me right click the items that was in that slot before thank you kindly settle this bug

cordially LeRamboMC

**Comment by sebastianbinder** [comment]
Hey @LeRamboMC. Unfortunately I'm not able at all to understand what you are talking about. We need some proper English here… Otherwise we won't be able to help you.

**Comment by LeRamboMc** [comment]
désoler je suis français et je ne parle pas trés bien anglais si vous voulez je réédite ma question en français 

( j'ai traduit avec google traduction )

**Comment by sebastianbinder** [comment]
Pas de problème. On peut essayer en français… Peut-être je peux comprendre le problème mieux que par google traduction… Mais il y a beaucoup de détails manquants: https://github.com/Yannici/bedwars-reloaded/wiki/HowTo:-Write-an-Issue

*#GoodOldSchoolFrenchSkills*

**Comment by LeRamboMc** [comment]
ok merci alors mon bug est un bug d'inventaire quand je suis en jeux mon inventaire bug c a dire que je peut uniquement organiser mon inventaire a travers la boutique sinon quand je fait un click droit sur litem cela me remet celui qui ce trouvait précédemment dans le slot

**Comment by LeRamboMc** [comment]
j'oubliait le serveur est sous spigot 1.8.8, la version du plugin est la 1.3.1 et je n'ait pas d'erreur dans la console

**Comment by Yannici** [comment]
English or nothing. It's nice that you can speak french @sebastianbinder but English should be really standard. Why are there so much french people which don't wanna learn english but think everyone should understand french instead. Grrrrrrrrrrrrrrrrrrr!

**Comment by sebastianbinder** [comment]
@LeRamboMc - sorry, but I still don't get your problem. Cannot help you :/ Sorry...
