### ISSUE TITLE
Spectaten geht auf Bungeecord nicht richtig 

### ISSUE THREAD

**Issue by chrischivlog** [Yannici/bedwars-reloaded#555]
Hi wir haben dein plugin auf unseren server getan, es ist das Beste was es für Bedwars gibt.
Doch wenn Leute von außen spectaten wollen dann werden diese zu erst in die Game-Lobby geleitet, und müssen dann extra 
Wir bräuchten einen Guten rat.
Danke schon mal im Voraus für dieses plugin.

**Comment by sebastianbinder** [comment]
Hi. We need some more details from you. Please have a look on https://github.com/Yannici/bedwars-reloaded/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.

**Comment by sebastianbinder** [comment]
Any update on this?
