### ISSUE TITLE
Man kann nicht mit der 1.9.4 mit Schilder joinen und Items benutzen

### ISSUE THREAD

**Issue by CraftingDanielHD** [Yannici/bedwars-reloaded#558]
Ich spiele mit der 1.9.4 auf Bukkit und kann keine Schilder zum joinen in Runden oder Items verwenden. der command /bw join (rundenname) geht schon aber die Items z.b der Diamant oder das Bett zur Teamauswahl nicht.

Daher hoffe ich auf einen schnellen Support dass mein Server mit diesem wundervollem Bedwars Plugin weiterlaufen kann
MFG. CraftingDanielHD

**Comment by sebastianbinder** [comment]
Hi. We need some more details from you. Please have a look on https://github.com/Yannici/bedwars-reloaded/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.

**Comment by superminerlol** [comment]
Ich spiele auf der 1.9.2 umd dort geht alles super.

-------- Ursprüngliche Nachricht --------
Von: CraftingDanielHD <notifications@github.com> 
Datum:04.06.2016  20:19  (GMT+01:00) 
An: Yannici/bedwars-reloaded <bedwars-reloaded@noreply.github.com> 
Betreff: [Yannici/bedwars-reloaded] Man kann nicht mit der 1.9.4 mit Schilder
  joinen und Items benutzen (#558) 

Ich spiele mit der 1.9.4 auf Bukkit und kann keine Schilder zum joinen in Runden oder Items verwenden. der command /bw join (rundenname) geht schon aber die Items z.b der Diamant oder das Bett zur Teamauswahl nicht.

Daher hoffe ich auf einen schnellen Support dass mein Server mit diesem wundervollem Bedwars Plugin weiterlaufen kann
MFG. CraftingDanielHD

**Comment by sebastianbinder** [comment]
Any update on this?

**Comment by CraftingDanielHD** [comment]
No, I've got the newest.

**Comment by sebastianbinder** [comment]
@CraftingDanielHD please have a look on [this dev build](http://ci.sebastianbinder.com/job/BedwarsRel-DEV/30/io.github.yannici$BedwarsRel/artifact/io.github.yannici/BedwarsRel/1.3.2/BedwarsRel-1.3.2.jar) and let us know if the issue is fixed there.

**Comment by sebastianbinder** [comment]
@CraftingDanielHD any update?

**Comment by CraftingDanielHD** [comment]
No i've got The newest

Daniel Kollmannsberger

**Comment by sebastianbinder** [comment]
Since you don't provide us all the information I have asked for above, I am not able to help you.
