### ISSUE TITLE
BungeeCord

### ISSUE THREAD

**Issue by Fages** [Yannici/bedwars-reloaded#559]
Hello, I can not connect via BungeeCord. The hub server sing writes that the game could not be found . Please, help.

**Comment by Yannici** [comment]
The hub server don't know the game which is actually saved on the bedwars server. The hub server just need to teleport the players to the bedwars server. The plugin will then add the players directly to the game. You can create Join-Signs easily with e.g. the plugin TeleportSign.

**Comment by Fages** [comment]
Thank you so much. I have another problem . In spectator mode, I gm 3 , but it seems to me that there must be 1 gm , how do I implement it ?

**Comment by sebastianbinder** [comment]
Gamemode 3 is Spectator Mode - so everything is fine there :)
