### ISSUE TITLE
Default config for each spigot version

### ISSUE THREAD

**Issue by Yannici** [Yannici/bedwars-reloaded#561]
We need default configurations for each 1.8 and 1.9. Just check the version on first start and then save the correct default config. This could be the easiest way to fix all setup problems for everyone having spigot 1.9 or 1.8

**Comment by sebastianbinder** [comment]
Don't know if my commit solves the sound problem… Didn't test it, maybe one of you guys could have a look on it...

**Comment by Yannici** [comment]
I don't think this will solve the problem since the default config will be the file which gets copied from the jar. The `addDefault` is only for guys which are updating from a version which didn't get these config keys.

**Comment by sebastianbinder** [comment]
That's why I have been adding this part:
```yml
try {
      Sound.valueOf(
          Main.getInstance().getStringConfig("bed-sound", "ENDERDRAGON_GROWL").toUpperCase());
    } catch (Exception e) {
      if (Main.getInstance().getCurrentVersion().startsWith("v1_8")) {
        Main.getInstance().getConfig().set("bed-sound", "ENDERDRAGON_GROWL");
      } else {
        Main.getInstance().getConfig().set("bed-sound", "ENTITY_ENDERDRAGON_GROWL");
      }
    }
```

**Comment by Yannici** [comment]
Oh, I didn't see that. Yeah, should be okay then.
