### ISSUE TITLE
Blöck in der Farbe des Teams!

### ISSUE THREAD

**Issue by ZockerWelt** [Yannici/bedwars-reloaded#563]
Ich habe einen Vorschlag das, dass Team mit seiner jeweiligen farbe blöcke zum bauen bekommt wie halt bein der lederrüstung. Man könnte "gefärbten Ton" als Baublock nehmen in der jeweiligen farbe halt! Wäre cool wenn sich da was machen lässt!! :) ;)

**Comment by sebastianbinder** [comment]
Bitte das nächste mal die Suchfunktion nutzen… https://github.com/Yannici/bedwars-reloaded/issues/552
