### ISSUE TITLE
Verzauberrungsproblem

### ISSUE THREAD

**Issue by ZockerWelt** [Yannici/bedwars-reloaded#564]
Kann man mir mal bitte sagen was man als verzauberung angeben muss für effiziens? Blicke nämlich nicht das verzauberungssystem vom pugin. Danke im voraus!! :)

**Comment by Yannici** [comment]
https://github.com/Yannici/bedwars-reloaded/wiki/shop.yml#examples-of-special-itemstacks-enchantments-or-potions
