### ISSUE TITLE
If you place blok instead of vine or lilipad, you can't break it

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#57]
No description needed

**Comment by Yannici** [comment]
I dont understand :/

**Comment by Granik24** [comment]
http://gyazo.com/222bfc3a4a4b7370f365f299063dd49f If I place block instead of liane or lilipad, I can't break it.

**Comment by Granik24** [comment]
And if you want, I'm on server.. Just come to us :)

**Comment by Yannici** [comment]
Fixed with commit https://github.com/Yannici/bedwars-reloaded/commit/3077472596aba247eb2a02887fcf6e6dc7c8c68b
