### ISSUE TITLE
1.10 Compatibility

### ISSUE THREAD

**Issue by sebastianbinder** [Yannici/bedwars-reloaded#571]
ToDo:
- [x] Move all pending issues from Milestone 1.3.2 to 1.3.3
- [x] Wait for Spigot 1.10 compatibility…
- [x] Add NMS-Code
- [x] Add API
- [x] Fix Code
- [x] Test by @Yannici 
- [x] Test by @Block-Build
- [x] Test by @sebastianbinder

**Comment by Yannici** [comment]
Ich teste das gleich.

**Comment by sebastianbinder** [comment]
@Yannici - any feedback on your tests?

**Comment by sebastianbinder** [comment]
?

**Comment by Yannici** [comment]
Everything is fine.

**Comment by sebastianbinder** [comment]
Opened pull request.
