### ISSUE TITLE
LOCALE_NOT_FOUND

### ISSUE THREAD

**Issue by dreamenemy** [Yannici/bedwars-reloaded#577]
hello dear i allways build a sign for bedwarsrel game but every time third lane on game sign say LOCALE_NOT_FOUND please help me

**Comment by sebastianbinder** [comment]
Seems like you have specified a wrong locale. But we need some more details from you in order to give you proper support. Please have a look on https://github.com/Yannici/bedwars-reloaded/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.
