### ISSUE TITLE
Setup command

### ISSUE THREAD

**Issue by he0828** [Yannici/bedwars-reloaded#578]
Maby add a setup command to help admins setup games easier

**Comment by Granik24** [comment]
Setup command? Eh? There are much of setup commands o.O

**Comment by he0828** [comment]
like one /bw setup where you can change settings set spawns set materialspawners and beds

**Comment by Granik24** [comment]
Reference for this https://github.com/Yannici/bedwars-reloaded/issues/121

**Comment by he0828** [comment]
ok :dancer:

**Comment by Granik24** [comment]
Close this one please, because it's on the plan with that issue^^
