### ISSUE TITLE
Remove spectators from scoreboard

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#59]
If you die ingame, it could be good to remove you from scoreboard. Not after leave, but immediately.

**Comment by Yannici** [comment]
What's the problem? I don't understand. If you spectator, you're hidden in scoreboard.

**Comment by Granik24** [comment]
If your team die ingame, you're be specator. After that, plugin don't remove you from scoreboard.

**Comment by Yannici** [comment]
Oh, okay. How you said on your server.

**Comment by Yannici** [comment]
Can't reproduce that. After a team dies it will remove the player (spectator) from scoreboard.

**Comment by Yannici** [comment]
Maybe a problem with other plugins you're using?

**Comment by Granik24** [comment]
I'll check it out. :)

**Comment by Yannici** [comment]
I will close that ... reopen it again, when it happen!
