### ISSUE TITLE
Disable EnderCrystal breaking

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#64]
It can be cool do disable EnderCrystal breaking :)

**Comment by Yannici** [comment]
Maybe I will add configurable protected blocks per game/region.

**Comment by Granik24** [comment]
Nice. We have "TheCrystal" map and Crystals not regenerate after reset..

**Comment by Yannici** [comment]
EnderCrystal isn't a block right?

**Comment by Granik24** [comment]
Yea

**Comment by Yannici** [comment]
I don't know if I'll at that feature.

**Comment by Yannici** [comment]
Shouldn't be breakable anymore.
