### ISSUE TITLE
Map reset don't remove Iron, Gold and Bronze

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#65]
^ see title

**Comment by Yannici** [comment]
I'll check that. But I never recognized something like that. Every restart of a game, it removes all entitys.

**Comment by Granik24** [comment]
http://imgur.com/DuSZhZi Ehm, this is.. LITTLE bug.. :D

**Comment by Yannici** [comment]
I don't think this is a plugin issue ...

**Comment by Granik24** [comment]
![2015-04-19_01 55 38](https://cloud.githubusercontent.com/assets/4377405/7217618/39e7b322-e637-11e4-9804-1e5d880fa295.png)
I think, this is bug in your plugin o.O
At same place after map reset

**Comment by Yannici** [comment]
How the map looks when it's correct?

**Comment by Granik24** [comment]
Water is in that building at left. If you want, you can join to server

**Comment by Yannici** [comment]
I tried it already, all worked ... :/

**Comment by Yannici** [comment]
@helptiger Do you have these problems, too?

**Comment by Granik24** [comment]
In latest build is everything fine.
