### ISSUE TITLE
Add respawn protection

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#66]
^ no description needed :D

**Comment by Yannici** [comment]
Theres no respawn-protection at all, at the moment :D But I will add it.

**Comment by Granik24** [comment]
Wut, we have spawn-protection.. Maybe other plugin

**Comment by Yannici** [comment]
This must be a other plugin, yes. Please check your issues if they caused by other plugins.

**Comment by Yannici** [comment]
I'll add configurable spawn protections! (Milestone https://github.com/Yannici/bedwars-reloaded/milestones/Version%201.1.0)
