### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by PatrikCZ** [Yannici/bedwars-reloaded#68]
Hello, I have a problem too somehow does not work your plugin could you send me the file in JAVA I wrote to you on the spigot aji but somehow you did not answer so you please send it to me?

**Comment by Yannici** [comment]
How can I send it to you?!

**Comment by PatrikCZ** [comment]
by email! Or on skype

**Comment by Yannici** [comment]
Skype name per pm in spigotmc.org please

**Comment by PatrikCZ** [comment]
I'm on the spigot and I wrote to you there but you snub me written off
