### ISSUE TITLE
If chunks unloaded in game world, it says error with beds

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#70]
We have plugin MultiWorld on our server.
If I saving map and Im at lobby, it says error with beds.
If I move to that world and write /bw save FloatingHouses, it will save seamlessly.

**Comment by PatrikCZ** [comment]
Ahoj,granik umiš česky?
rad bych kdyby jsi mi ten jeho Bedwars mohl dat do JAVA souboru a poslat mi to furt nfunguje

**Comment by Yannici** [comment]
I added Multiworld as softdependency in commit https://github.com/Yannici/bedwars-reloaded/commit/cb820e5b88a9beadc4bd7b22bb16b5dd4474b1e1 It should work now ...

**Comment by PatrikCZ** [comment]
and you can send it to me to put it somewhere I pulled you do not understand!
