### ISSUE TITLE
Problem with /spawn and /server lobby

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#71]
If player hit igame /spawn or /lobby (Bungee command /server lobby), player will stay in the game..

**Comment by Yannici** [comment]
I will add configurable allowed commands ingame.

**Comment by Granik24** [comment]
Yea, but some players are accustomed from GommeHD for /lobby. It maybe need to add fuse.

**Comment by Yannici** [comment]
Okay
