### ISSUE TITLE
Add regionname to "Game gamename started!"

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#74]
No description needed

Screen: http://gyazo.com/8aaba6fb02662ca7950efc5c2aa3faee

**Comment by Yannici** [comment]
Ok, I'll add that.

**Comment by Yannici** [comment]
Fixed in v1.0.1 => https://github.com/Yannici/bedwars-reloaded/commit/43c86d65f5c903fd1bc3709625e2e83a3baa167b
