### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by PatrikCZ** [Yannici/bedwars-reloaded#76]
Hello, Your plugin is too buggy and power do not understand him made by you and sent him tutorial would have me every update but the file java on spigot? on which version it works 100% prootže there brbne at version 1.7 to 1.7.10 I'd like it if you could give it to the version of aji and spigot thank you

**Comment by Yannici** [comment]
Please stop! I don't unterstand anything. Stop using google translator! I never tested it with bungeecord, which you're using, I think. This plugin isn't released so I don't really care of bugs with that plugin. Add the bugs to the issue tracker and I will fix them step by step. But please stop posting shit like  that.
