### ISSUE TITLE
Fire not 

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#77]
We have Fire placed on Netherrack. If player remove fire, after map-reset, no fire.
Screen after: gyazo.com/7595df7e40b11fefb78f8b41bfda0641
Screen before: gyazo.com/fa93ce6c3ca33609ad1b94d707668b78

**Comment by Yannici** [comment]
I'll try to make that work ..

**Comment by Yannici** [comment]
Should be fixed with https://github.com/Yannici/bedwars-reloaded/commit/9822ff2853b243a0d66f83ea93a7c5ed0127a94a
