### ISSUE TITLE
MOTD

### ISSUE THREAD

**Issue by PatrikCZ** [Yannici/bedwars-reloaded#79]
A does not work MOTD I thought that it is less buggy but it neva

**Comment by Yannici** [comment]
MOTD not working? Where? Do you use bungeecord? More details please.

**Comment by PatrikCZ** [comment]
MOTD does not work when the server switches can not see it

**Comment by Yannici** [comment]
MOTDs (server info) are for bungeecord signs (to show the game state of the bedwars game), not as a message after switching server.

**Comment by PatrikCZ** [comment]
yes it mislim why it does not work and could you send me update the plugin there and what version do I put a bug in the plugin vic Spigot

**Comment by Yannici** [comment]
Try to find someone who can write better english and let him translate it for you. I can't understand your sentences. For me the MOTDs working like a expected.

**Comment by PatrikCZ** [comment]
Oh ok so I have not disturb I'll wait to fix it all

**Comment by Granik24** [comment]
@PatrikCZ Please, write me your bugs. I can translate it to Yannici. Your English is so bad. Jsem z Česka, takže Ti rád pomůžu. ;)

**Comment by PatrikCZ** [comment]
aha ok to se mi hodi mi nefunguje MOTD když se chcu připojit na server a zobrazi se mi me servery kde mam aji ten plugin ale u toho mi nefunguje MOTD neviš čim to je ?
