### ISSUE TITLE
Bed dropping after destroy, scoreboard symbols, death message and bad resources color

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#8]
If I destroy bed, it can drop to player. 

Also, I have problem with scoreboard - http://gyazo.com/66d6ddae375c71c0e0f855864fa45bb1
That symbols maybe can be ✔ and ✘

Next problem with message - http://gyazo.com/8dfff526ee61826bfd78e18e67249553
It can be good to disable Essentials prefixes and set Team colors.

Last problem: Bad colors and text formating: http://gyazo.com/072b29ebb71bf8825d91b5ca9e4d6a4f and http://gyazo.com/55f0667c363932d0d8c45ea036c75bbf

Sorry about that updates, I testing it now.. :D

**Comment by Yannici** [comment]
Yes, but I cannot figure out why this is happen :-1: But I'll still try to fix that.

The scoreboard symbols aren't a problem of the plugin. You're compiling by yourself and that's why the symbols aren't correct. You have to set the symbols in Game-Class by yourself and save it in unicode format.

I'll try to disable essentials chat prefixes while game is running. But I can't really promise it will be done soon.

**Comment by Yannici** [comment]
After a small update (you had an wrong color code in "bronz" translation) the colors are working for me: http://puu.sh/h9TM6/508fca88dd.png

Maybe a issue with your own compiled jar?

**Comment by Granik24** [comment]
It seems yea, it's issue with my jar. How I can fix it?

**Comment by Yannici** [comment]
Try to change your encoding to eg. utf-8. This should help.

**Comment by Granik24** [comment]
Thank you so much. Everything is fine! :+1:

**Comment by Yannici** [comment]
You're welcome!

**Comment by Granik24** [comment]
I have another question, how about PermissionsEx? 
= bw.join and others?

**Comment by Yannici** [comment]
I don't know about PermissionsEx. What is needed for compatibility?

**Comment by Granik24** [comment]
You need to setup permissions for commands.
Exmaple: For /bw join you need to set permission to bw.join.

Plugin: http://dev.bukkit.org/bukkit-plugins/permissionsex/

**Comment by Yannici** [comment]
You can find possible permissions in plugin.yml. Permissions for every single command doesn't exists.

**Comment by Granik24** [comment]
Oh, cool. Thanks!

**Comment by Yannici** [comment]
I close that and add the bed destroy problem as an standalone issue.
