### ISSUE TITLE
Fully configurable ressource spawners

### ISSUE THREAD

**Issue by Yannici** [Yannici/bedwars-reloaded#85]
I want to make fully configurable ressource spawners. So a server can set own ressource spawners. When they don't like bronze, iron or gold, they can add more or change them!

**Comment by Granik24** [comment]
Woohoo, good idea :+1:

**Comment by Yannici** [comment]
Added with https://github.com/Yannici/bedwars-reloaded/commit/a6fed1bd9542ff650b81eef4770655d0d202ce13
