### ISSUE TITLE
Players after respawn 

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#93]
Some players after respawn beginning invisible. Randomly, I Don't know why.

**Comment by Yannici** [comment]
What means "beginning"? Are they invisible for some seconds or what? But this is very strange, I can't imagine how that should happen.

**Comment by Granik24** [comment]
Yea, only for X seconds.. After some while, we can see him. It seems to Clientside problem.. I can't see him but my friend yes.. (and conversely)

**Comment by Yannici** [comment]
Ok, I don't know if it's a plugin problem then.

**Comment by Yannici** [comment]
Reopen please if occuring again.
