### ISSUE TITLE
Every new game set XP bar to 0

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#94]
^^ Title

**Comment by Yannici** [comment]
I don't understand. Ingame XP bar is 0, of course. After leaving the bedwars game it will reset the xp bar to the xp which the player had before.

**Comment by Granik24** [comment]
No. If YouTuber hit "Star game" diamond, XP bar will freeze at remaining time.

**Comment by Yannici** [comment]
Oh, I see, thanks! I will fix that.

**Comment by Granik24** [comment]
Still not fixed.

**Comment by Yannici** [comment]
Really? :cry:

**Comment by Granik24** [comment]
Yea :(
